### ISSUE TITLE
Tell Me More link doesn't work

### ISSUE THREAD

**Issue by rosagp** [OnionBrowser/iOS-OnionBrowser#101]
I'm using an iPhone SE running 9.3.4. On the third screen that says "Sometimes you need a bridge to get to Tor" when you tap on the words TELL ME MORE, nothing happens. There is no additional information.

**Comment by tladesignz** [comment]
Thanks @rosagp for pointing this out. This was sort of intentionally left blank.

I guess we have to make a decision now.

a) Do we drop that?
b) Do we put a page behind this button?

If b)
- Maybe show an excerpt of this page: https://www.torproject.org/docs/bridges

I happily implement it, if one of you decides, what to put there.
@mtigas, @n8fr8, @cstiens ?

**Comment by cstiens** [comment]
@tladesignz Since we have information about Tor bridges on the configuration page, I think we can remove the 'Tell me more' link.

**Comment by tladesignz** [comment]
Fixed with commit https://github.com/guardianproject/poe/commit/b551aff59c68c36bad6844eacbcc8411a78d5463.
