### ISSUE TITLE
[2.X] Settings/bookmarks migration from OB 1.X

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#105]
Will need this for 2.X release.

I’ll fill this out with technical details once I get a chance.

**Comment by mtigas** [comment]
Sorry for the delay here.

# Bookmarks

## 1.X

It's a CoreData model (Bookmark; [.h](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/OnionBrowser/Bookmark.h), [.m](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/OnionBrowser/Bookmark.m)). I don't think my [implementation](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/OnionBrowser/BookmarkTableViewController.m#L75-L88) is unusual at all, so that's where that all exists.

## 2.X

Haven't looked too closely at the Endless implementation, but see the Bookmark [.h](https://github.com/mtigas/OnionBrowser/blob/2.X/Endless/Bookmark.h)/[.m](https://github.com/mtigas/OnionBrowser/blob/2.X/Endless/Bookmark.m) for that

# Browser Preferences

## 1.X

https://github.com/mtigas/OnionBrowser/blob/41746fe50d0df34234426b0e69965601b2799ba6/OnionBrowser/OnionBrowser/AppDelegate.m#L587-L704

I put a bunch of things (homepage, etc) into a plist.

## 2.X

For the initial 2.X release, we probably need the homepage setting.

I think we _could_ try to migrate the content blocking (`javascript` key) into the "default" site preference (in the 2.X UI, the thing where you can set host-based settings). I'm less sure about the other things

# Bridges

## 1.X

CoreData (Bridge; [.h](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/OnionBrowser/Bridge.h), [.m](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/OnionBrowser/Bridge.m)).

## 2.X

Don't totally remember the implementation, but it's the `customBridges` value that [OnionManager.swift](https://github.com/mtigas/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L97-L122) uses a bunch.

**Comment by tladesignz** [comment]
Other settings which could be migrated:

- Do-Not-Track Header
- User Agent String
- TLS version (new options: `TLS 1.2, 1.1 or 1.0` and `TLS 1.2 Only`)

**Comment by tladesignz** [comment]
As discussed, User Agent String will not be migrated, as this would make users stand out over time. DNT and TLS version setting migration now added.
