### ISSUE TITLE
Supporting IPv6

### ISSUE THREAD

**Issue by igornazarov1991** [OnionBrowser/iOS-OnionBrowser#108]
Apple requires to support IPv6 DNS64 / NAT64 networks (https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html). 

I've tested this environment and Tor does not work. I see error after trying to connect (see screenshot attached):
 
![attachment-5096342865851767925screenshot-1230-151628](https://user-images.githubusercontent.com/12492634/34525479-c1b62716-f0a7-11e7-93e0-0de649bd52e0.png)

Can you please suggest what to do in this case?

**Comment by JRomainG** [comment]
This issue was also addressed in #73 (which is closed now), but it still happens to me (and Apple apparently) too.

**Comment by tladesignz** [comment]
A new version is out which should fix some IPv6 issues. Can you check, if it now works?

**Comment by igornazarov1991** [comment]
The issue has been fixed. It works now if to use a bridge. Thank you!

**Comment by tladesignz** [comment]
Great! Thanks for re-checking!
