### ISSUE TITLE
New Logo Proposal 

### ISSUE THREAD

**Issue by auliausu** [OnionBrowser/iOS-OnionBrowser#109]
Dear Developers 
i have made some contribution for your project by creating new logo, maybe you will be interest to it ;) 
you check on this link of blog 👍: 
https://steemit.com/utopian-io/@auliausu/new-logo-proposal-for-onion-browser

![cover](https://user-images.githubusercontent.com/9031884/34595472-ebfff61e-f20a-11e7-95d3-57fa1cb9b9d6.png)

![presentation](https://user-images.githubusercontent.com/9031884/34595476-f1b48c3c-f20a-11e7-9524-d127245f58b9.png)

**Comment by joshlittel23** [comment]
Good job. I like it

**Comment by auliausu** [comment]
thanks @joshlittel23

**Comment by tladesignz** [comment]
@auliausu Thank you very much for this nice piece of work!

Unfortunately, this came at the totally wrong time - in the midst of finishing version 2.0.

I'm sorry, but, as you can see, the 2.0 release has a completely refurbished look-and-feel with a new icon. This was done months ago, but the release took a while.

I guess you can understand, that we won't change our logo just now again. Sorry!
