### ISSUE TITLE
Onion Browser 2.0 may be leaking DNS requests

### ISSUE THREAD

**Issue by Cauchon** [OnionBrowser/iOS-OnionBrowser#112]
When using Onion Browser 2.0, I'm seeing that non-onion domains are appearing in my DNS' log (using pi-hole). When using the Tor Browser on Mac, those same domains aren't appearing.

**Environment & Steps:**
iPhone X, iOS 11.2.2

1. Connect to my VPN (passes through a pi-hole)
2. Visit a non-Onion URL using Onion Browser 2.0
3. Notice that the site and the calls from that site are appearing in the pi-hole log

**Comment by Baccount** [comment]
If this is indeed occurring when using OnionBrowser 2, this should be considered a high priority security vulnerability. ISPs can easily keep track of DNS request, and handover those logs to governments. @Cauchon  **does this also occur on onion sites?**

**Comment by Cauchon** [comment]
@Baccount As far as I can tell, it does not happen on Onion sites - no DNS records shown. On non-Onion sites, I do see the domains coming through the DNS.

**Comment by Baccount** [comment]
@Cauchon Send the Dev a email as fast as possible. 
Click link below for the devs email.
https://www.google.com/recaptcha/mailhide/d?k=01aYSfVmgqG26v17kO0wSinQ==&c=JgagO5nRsS3pKpIFHZvlZQ==

**Comment by Baccount** [comment]
Security Issues
If you've found a security issue in one of our projects or in our infrastructure, please email tor-security@lists.torproject.org. You can get the GPG public key for the list by contacting tor-security-sendkey@lists.torproject.org or from pool.sks-keyservers.net. Here is the fingerprint:

	gpg --fingerprint tor-security@lists.torproject.org
	pub   4096R/1A7BF184 2017-03-13
	      Key fingerprint = 8B90 4624 C5A2 8654 E453  9BC2 E135 A8B4 1A7B F184
	uid                  tor-security@lists.torproject.org 
	uid                  tor-security@lists.torproject.org 
	uid                  tor-security@lists.torproject.org 
	sub   4096R/C00942E4 2017-03-13

**Comment by tladesignz** [comment]
Please, relax. We're reading this thread. Don't bother Tor Project, because this is not an official Tor project. We're looking into it.

**Comment by mtigas** [comment]
Currently investigating.

My best guess after taking a quick peek is that it has to do with one of the Endless features that tries to prevent access to LAN or localhost resources, but looks like it uses a DNS lookup as part of that check
https://github.com/mtigas/OnionBrowser/blob/7cc6c9c98493c86fb9ec6a88de7e10584140f5aa/Endless/LocalNetworkChecker.m (`addressesForHostname`).

**Comment by tladesignz** [comment]
Ah! You can easily test, if that causes the issue, through disabling that feature: 
-> Host Settings
-> Default Settings
-> Block external LAN requests
-> Set to "No"

**Comment by mtigas** [comment]
About to test by running the unbound dns resolver locally and setting my DNS to `127.0.0.1` and seeing what queries go through unbound’s log when running in the simulator. (I’ve had some success doing this before.)

But yes, my guess is that we can even _completely_ disable that feature in code since we’re going to SOCKS5 proxy _everything_. But will report back after some testing.

**Comment by mtigas** [comment]
Confirmed that it's the "Block external LAN requests", with a `getnameinfo` call here https://github.com/mtigas/OnionBrowser/blob/7cc6c9c98493c86fb9ec6a88de7e10584140f5aa/Endless/LocalNetworkChecker.m#L68 . Looks like it's the only spot that the function is called, which is good.

Anyway, roughly disabled that setting and all that code in a56f07bb9e964cd5c46d2e196bba6d90adb8692b . Building/uploading now.

**Comment by n8fr8** [comment]
Should we publish an advisory on how to turn that setting manually? I suppose it comes down to how fast we think the Apple approval process will go

**Comment by tladesignz** [comment]
To me, it looks like, that [`CFHostStartInfoResolution`](https://developer.apple.com/documentation/cfnetwork/1426672-cfhoststartinforesolution?language=objc) in [LocalNetworkChecker.m#L47](/mtigas/OnionBrowser/blob/2.X/Endless/LocalNetworkChecker.m#L47) does also start a DNS resolve.
You disabled all the code using that class, so that's not a problem, but I rather comment this also, so it doesn't get used accidentally in the future.

**Comment by Cauchon** [comment]
Hi guys,

Any update on when this fix will make it to end users?

**Comment by tladesignz** [comment]
Arrrrgl. We're currently fighting with Apple to get the update through the review. It's always the same story with them: You give them a new version which they just let through and then you need to push some bugfixes and every time they look at it, they find some new faults and harrass you about it.

So: We're working on it...

**Comment by Cauchon** [comment]
I got the update in the App Store today and can confirm that I’m not seeing the DNS leak anymore. Thanks!

**Comment by tladesignz** [comment]
Well, thank you for alerting us about this so quickly!
