### ISSUE TITLE
Onion Browser gets stuck in bootstrapping when on data network

### ISSUE THREAD

**Issue by alisonLFP** [OnionBrowser/iOS-OnionBrowser#114]
iPhone 6, carrier T-Mobile

**Comment by tladesignz** [comment]
A new version is out which should fix some IPv6 issues. Can you check, if it now works?

**Comment by tladesignz** [comment]
Related: #108

**Comment by alisonLFP** [comment]
It's working in the new version! Thanks!

**Comment by tladesignz** [comment]
Great! Thanks for re-checking!
