### ISSUE TITLE
Options disappear when Onionbrowsr is in "NON-Dark mode" and Darken colors are enabled in IOS settings

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#115]
Options disappear when Onionbrowsr is in "NON-Dark mode" and Darken colors are enabled in IOS settings.

1.Make sure onion browser is net to Light mode "NON-Dark mode"
2. Force close onion browser and ope IOS settings and go to `General-> Accessibility-> Increased contrast` and enable darken colors.
3. Open OnionBrowser and when it is connected, the only thing that shows up is the url bar and all the settings options and the tabs button is gone.
Tested on IOS 11.2.5 on a iPhone 7 and iPad Pro 10.5 inch. Onionbrowser 2
@mtigas
Photo showing the bug on iPad Pro 10.5 inch
![image-1-1](https://user-images.githubusercontent.com/10781882/35362724-6058dd04-011b-11e8-94fa-c1734c3a2352.jpg)
@mtigas

**Comment by tladesignz** [comment]
Interesting. Can confirm on iPhone 7, iOS 10.3.3. The icons are just gone. One can press there, anyway, and menu/tabs are still working.

**Comment by tladesignz** [comment]
Thanks for finding all these bugs, @Baccount!
