### ISSUE TITLE
Request: Nextcloud Bookmarks support

### ISSUE THREAD

**Issue by sunjam** [OnionBrowser/iOS-OnionBrowser#116]
Hi,
    
This is a request for integrating support for [Nextcloud Bookmarks](https://github.com/nextcloud/bookmarks), which is a fully open source, self-hosted bookmarks sync server using [REST API.](https://github.com/nextcloud/bookmarks/blob/master/appinfo/routes.php)

**Comment by tladesignz** [comment]
@m4mb01t4l14n0, I implemented a first shot at this:

In Bookmarks scene, press "Sync":

![Simulator Screen Shot - iOS 12 4 @ iPhone 6 - 2020-02-27 at 10 06 24](https://user-images.githubusercontent.com/117089/75428781-ffa8ee80-5948-11ea-95e5-dab6b2bd3811.png)

Which brings you to this scene, where you can enter the server hostname, your username and password and then press "Synchronize" to do an initial synchronization.

As long as valid credentials are stored here, creation, edit and deletion of bookmarks will be synchronized to the server.

Do you feel this is a good-enough implementation, and if so, can @kckthx have a look at it and maybe improve the UI?

![Simulator Screen Shot - iOS 12 4 @ iPhone 6 - 2020-02-27 at 10 09 47](https://user-images.githubusercontent.com/117089/75428966-4f87b580-5949-11ea-9916-fc23afdea78f.png)

**Comment by m4mb01t4l14n0** [comment]
@tladesignz great first shot at this!!!  Question: Obviously this is a niche feature.  It seems like exposing the Sync option to all users, therefore, might be asking for trouble.  How about a setting (in Settings) that enables/disables Sync? If enabled, that action shows.  

@kckthx we will likely have a set of smallish UX items for you this round.  Let me collect those and analyze before you engage (since budget is small)

**Comment by tladesignz** [comment]
> @tladesignz great first shot at this!!! Question: Obviously this is a niche feature. It seems like exposing the Sync option to all users, therefore, might be asking for trouble. How about a setting (in Settings) that enables/disables Sync? If enabled, that action shows.

Huh. That sounds like a lot of hiding. People won't be able to find it, unless they specifically search for that feature.

Nothing can happen in that scene, as long as they don't enter *valid* credentials to a Nextcloud server running the Bookmarks plugin. (They can't even press the "Synchronize" button, as long as they don't enter anything.)
Placing it there seemed logical (bookmarks...) and is a nice advertisement, I think.

**Comment by kckthx** [comment]
ok @tladesignz I've started working this out a bit and have a few questions

1.  What happens after the user taps “sync”? Will this screen have an option to “un-sync”? or “log out?”

2. If the immediate sync fails, how would the user go about re-syncing? Do they have to un-sync their next cloud account and re-sync?

**Comment by tladesignz** [comment]
> 1. What happens after the user taps “sync”? 

1. All entries from the server are read.
2. They are matched against the currently existing.
3. If an entry is not existing locally, it is created.
4. All entries from the device are created on the server, *if* they don't exist.

> Will this screen have an option to “un-sync”? or “log out?”

No.

> 2. If the immediate sync fails, how would the user go about re-syncing? 

Just press "Sync" again.

> Do they have to un-sync their next cloud account and re-sync?

No.

When bookmarks are created locally, they will be sent to the server immediately. If there's an error, then local and server are out-of-sync. No retries.

When a bookmark is deleted locally, it will be tried to delete it on the server, too.
If there's an error, local and server are out-of-sync. No retries.

So, if you press sync later, all locally-but-not-remotely deleted bookmarks come back.

I know, this is a very cheap implementation. I figured, we maybe try if this is enough, and see how the user feedback goes.
I'm not sure, if it's worth to throw a lot of work into a sync queue with retry mechanisms.
@m4mb01t4l14n0, what's your take on this?

**Comment by tladesignz** [comment]
@kckthx, BTW: *All* of what I just rephrased is written in the scene itself. You can see it in the screenshots.

**Comment by kckthx** [comment]
ok @tladesignz here we go. I didn't rebuild out the bookmark screen since that's already done, so there's just a blank screen with "sync" at the bottom. ;)

I think the best move is to put the alert for a failed sync to be only seen when the sync actually fails, so it's less confusing. 

![OB-Sync_Nextcloud](https://user-images.githubusercontent.com/36669955/76988601-f2ad6880-6912-11ea-9087-59a5c485975f.jpg)

**Comment by tladesignz** [comment]
Thanks, @kckthx! Now implemented!
