### ISSUE TITLE
Can not connect with reCAPTCHA

### ISSUE THREAD

**Issue by JamesMatt** [OnionBrowser/iOS-OnionBrowser#120]
![023b6bf8-ae44-46b7-ade9-d62124a34ed0](https://user-images.githubusercontent.com/25457860/35774965-c82eef44-09b9-11e8-8b72-f74aaa493813.jpg)
Onion Browser 2.0.2 can not connect with reCAPTCHA, even though I have disabled **apis.google.com** rule. Please fix it, thanks!

**Comment by tladesignz** [comment]
Ok, I tested this with the latest dev version, no special settings needed, no explicit whitelisting.

- goo.gl is sunsetted. Cannot test there anymore.
- Recaptcha v2 Demos at https://www.google.com/recaptcha/api2/demo and https://recaptcha-demo.appspot.com seem to work just fine. 
- Sometimes, one gets an exit node with an IP, which annoyed Google earlier. Then, there's no way to get authorized. Wait until Google isn't annoyed anymore, or you get a new exit node.

Can't fix from my point of view now. Please feel free to re-open, in case you have more insights.
