### ISSUE TITLE
When I dismiss the bridge screen, there are on screen artifacts that appear for a second.

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#121]
When I dismiss the bridge screen, there are on screen artifacts that appear for a second. Here is a video showing the bug.
[video_showing_the_bug.MP4.zip](https://github.com/mtigas/OnionBrowser/files/1702407/ScreenRecording_02-07-2018.01-26-23.MP4.zip)

**Comment by tladesignz** [comment]
Yeah, I know this. Unfortunately, that's a side effect of how we put the POE library and Endless together. Don't think, we will fix this soon, since we don't want to move too far away from Endless.

But I can leave this open for now.

**Comment by tladesignz** [comment]
Sorry, didn't want to close. @mtigas please review!

**Comment by tladesignz** [comment]
Ah. That's a stupid "fix". It breaks code. There's a reason, why it is like that. I have an idea. Perhaps I can change POE, so that it accepts an explicit delegate.

**Comment by mtigas** [comment]
Sorry I didn't get a chance to look at this over the weekend, but the updated fixes look good to me! (That delegate is going to be _super_ helpful, I think.)
