### ISSUE TITLE
Reset app rating in next release

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#122]
Because OnionBrowser 2 is such a large release you reset the app rating in next release so users can see reviews for version 2 and onward. Here is the instructions from Apple.
https://help.apple.com/itunes-connect/developer/#/devfb7e87af8

**Comment by tladesignz** [comment]
@mtigas Was this done or does this still need to be done or will we not do it because of reasons?

**Comment by DavidMOliver** [comment]
I want to assign this to milestones 2.2

**Comment by tladesignz** [comment]
@DavidMOliver: Let's first see what @mtigas has to say. (See my question above.) This is a matter of minutes. Just some clicks in iTunesConnect, not real work.

**Comment by tladesignz** [comment]
I'll close this now.
