### ISSUE TITLE
[2.x] Please separate javascript from images

### ISSUE THREAD

**Issue by dingos1** [OnionBrowser/iOS-OnionBrowser#123]
In 1.x, we could disable Javascript and other active content while allowing images ("block all active content"). In 2.x, the "strict" setting not only blocks JavaScript and video but also images. Are there any security implications of allowing static images (jpeg, png, gif, etc.)? Tor browser with noscript allows this combination so I hope not...

This is a problem obviously for sites with images but also for sites with reCAPTCHA. On the strict setting, the reCAPTCHA images never appear while on the medium setting reCAPTCHA detects JavaScript and gives a different type of challenge with fails due to the lack of something. reCAPTCHA works fine on the permissive setting, but that's not very useful if the goal is to hide your IP behind TOR.

Thanks again for all your work developing Onion Browser, we appreciate it and have been long-time users, even back before it was free.

**Comment by mtigas** [comment]
Can't believe I haven't noticed that I didn't whitelist [`img-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src) the way I whitelist `style-src`.

This'll be in the next update. cf12cf9874bf905581f23f6397f745dbb33e8bb0

**Comment by VectorABC** [comment]
As of 2019 this exact same bug has returned as a huge security hole since it forces JavaScript use just to see image-based captchas.

**Comment by tladesignz** [comment]
Thanks a ton for catching this - again!
It's a bug from upstream (Endless) which I reintroduced accidentally by merging the latest code from Endless.

I now pushed the change to a pull request to Endless, so this hopefully won't happen again.

**Comment by dingos1** [comment]
Sorry, despite the patch, this doesn't seem to be fixed on 2.X right now (or maybe I'm doing it wrong). I can build and run just fine, and the CSPheader seems to be set correctly, but no images show up in strict mode (works fine in other modes).

`[HostSettings] [Tab 0] CSP header is now connect-src 'none'; default-src 'none'; font-src 'none'; media-src 'none'; object-src 'none'; sandbox allow-forms allow-top-navigation; script-src 'none'; style-src 'unsafe-inline' *; image-src 'unsafe-inline' *; report-uri;`

**Comment by tladesignz** [comment]
D'oh! It's `img-src`, not `image-src`.
Also did some evaluations and removed superfluous and broken policies.
