### ISSUE TITLE
Video playing problem

### ISSUE THREAD

**Issue by codaman** [OnionBrowser/iOS-OnionBrowser#126]
I can't play any videos. Videos nor starting and playing.

**Comment by Baccount** [comment]
Change your content policy under host settings, default settings and content Policy, try the different options and see if any of them cause the videos to start playing.

**Comment by tladesignz** [comment]
Please note:

"- Multimedia often bypass Tor and compromise your privacy; video files and video streams are blocked by default and are not supported by Onion Browser."

Source: https://itunes.apple.com/at/app/onion-browser/id519296448?mt=8

**Comment by codaman** [comment]
Thank you so much. I solved this
