### ISSUE TITLE
No support for onion v3 hidden services

### ISSUE THREAD

**Issue by hsn10** [OnionBrowser/iOS-OnionBrowser#127]
Tor needs to be 0.3.2.1 or higher

**Comment by tladesignz** [comment]
Worry not, there will be a new release next month containing the latest Tor.

**Comment by mtigas** [comment]
2.1.0 now live in the App Store! Confirmed that v3 onions are now working (tested against the Qubes documentation site @ qubes-os.org and sik5nlgfc5qylnnsr57qrbm64zbdx6t4lreyhpon3ychmxmiem7tioad.onion ) Closing.
