### ISSUE TITLE
Polish browser UI adopted from Endless

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#131]
Adapt to color scheme of POE, nicer icons, other touch-ups.

Offer improvements back to Endless, when done.

**Comment by nxame** [comment]
@tladesignz @mtigas I would like to help on UX/UI Polishing work. Please let me know more.

**Comment by tladesignz** [comment]
https://github.com/xmartlabs/Eureka

**Comment by tladesignz** [comment]
- Browser chrome improvements
  - toolbar at bottom instead of dropdown?
  - Get rid of the url-bar-at-bottom feature?
  - copy Safari completely?
- Reorganize settings, maybe change wording

**Comment by tladesignz** [comment]
Check issue #132 for the Tor circuits stuff.

**Comment by tladesignz** [comment]
Followed up in #210, #211, #212.
