### ISSUE TITLE
When Clear all when in background is enabled, does not work as expected

### ISSUE THREAD

**Issue by gitatmax** [OnionBrowser/iOS-OnionBrowser#135]
When Clear all when in background is enabled, and I switch apps and return to OnionBrowser, the last thing I had opened is visible behind the startup page.

Running on iOS (latest public), on iPhone X.

**Comment by tladesignz** [comment]
Actually, when testing with the latest test build, the feature works as intended. 
Also, when I test with the (still current) 2.1.0 release, I can't reproduce this.

Maybe, there needs to be a special combination of things to do? Or one of the latest iOS updates fixed something, which didn't work well together with OnionBrowser?

@mtigas, can you reproduce this somehow?

**Comment by gitatmax** [comment]
@tladesignz, I should've commented when I closed the issue—I tried again recently and couldn't reproduce whatever I had done before so closed it.

Thanks!

**Comment by mtigas** [comment]
Great! I'm going to mark this closed. We'll open a new ticket if that behavior starts happening again.

**Comment by tladesignz** [comment]
@maxwelljordanwhite: No worries!
