### ISSUE TITLE
"Report a bug" doesn't do anything in Settings

### ISSUE THREAD

**Issue by gitatmax** [OnionBrowser/iOS-OnionBrowser#136]
Running on the latest public release of iOS, on an iPhone X.

**Comment by tladesignz** [comment]
Seems you got frustrated with us, and I'm sorry for that. Organizing the funding and the time for further development took more time then everybody liked, but now we started again. 

I'm sorry.

Anyway, I can confirm this is actually still a problem so I will reopen and fix!
