### ISSUE TITLE
Add "Implementing an iOS Settings Bundle"

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#139]
Adding support for advances settings the show up in IOS settings may be useful for extra experimental  features. Here is information on how to implement it.

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html

**Comment by tladesignz** [comment]
Issue #74 could be an interesting candidate for this.

**Comment by tladesignz** [comment]
Note to myself:
- investigate how OB is notified about changes in Settings.app while it runs (iPad side-by-side!)

**Comment by tladesignz** [comment]
So, while redesigning the settings it turned out that it's way too complicated to add yet another dimension to the question of where to put what, esp. with the constraints that a Settings Bundle puts upon its settings.

Therefore, we decided to not implement this idea. Sorry. :-/
