### ISSUE TITLE
Changing custom bridges after launch is ignored

### ISSUE THREAD

**Issue by teor2345** [OnionBrowser/iOS-OnionBrowser#140]
When I try to change onion browser's custom bridges after launch, the change is silently ignored.

Steps to reproduce:
1. Wait until onion browser displays a web page
2. Try to add a custom bridge
3. Close the settings
4. Reopen bridge settings

Actual Result:
The new custom bridge is not added

Expected Result:
The new custom bridge is added

Notes:
This happens when changing from direct connection to a custom bridge, and when changing an existing bridge line.

**Comment by tladesignz** [comment]
This actually seems connected to #121.

**Comment by tladesignz** [comment]
Fixed with commit e1f42fbfa1ab7ee37c40f0e50d9006d8b2bca4fb.
