### ISSUE TITLE
New network framework in the latest IOS 12

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#141]
A new network framework was added in IOS 12 and I wonder if this would help OnionBrowser. Here is some information about it with links to documentation.

**Network Framework**
[The new Network framework makes it easier to create network connections to send and receive data using transport and security protocols.](https://developer.apple.com/ios/whats-new/)

> You can use it to replace calls to low-level socket APIs in your apps, see the Network framework developer documentation.

https://developer.apple.com/documentation/network
@tladesignz

**Comment by tladesignz** [comment]
Hey, thanks for the hint. However I don't see, how this could help us. We use the original Tor client, written in C. All problems are related to that, esp. that Tor still can't be stably restarted in-process.
See my blog article about it: https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

Making use of the Network Framework would mean to do a complete rewrite of Tor (at least the client part) in Swift. Would be a really nice idea, but unfortunately we don't have enough funding for that. Not the initial founding nor the funding to sustain its continued development.

Or do I overlook something here? I'm happy to consider any further ideas you can come up with!

**Comment by DavidMOliver** [comment]
I want to assign this to milestone 2.3

**Comment by tladesignz** [comment]
@DavidMOliver: Actually, I think we're going to close this, as this seems to be a dead end. (See my comment above.)
