### ISSUE TITLE
Adding customer brigde with camera doesn't work

### ISSUE THREAD

**Issue by Byte1122** [OnionBrowser/iOS-OnionBrowser#142]
The camera functionality for adding customer brigde doesn't work. The QR code can't be recognize and there is also now confirm button in iOS 11.4.  Version 2.1.0 Onion Browser.

**Comment by tladesignz** [comment]
Awesome, Apple! https://stackoverflow.com/questions/46639519/avcapturemetadataoutputobjectsdelegate-not-called-in-swift-4-for-qr-scanner
