### ISSUE TITLE
Adding a new host setting enables JavaScript regardless of defaults

### ISSUE THREAD

**Issue by starchturrets** [OnionBrowser/iOS-OnionBrowser#143]
Steps to reproduce:

- In Host Settings, set default policy on web content to Strict. 

- Go to browserleaks.com/JavaScript. It should show all scripts as being blocked.

- Tap host settings and add browserleaks.com. Do not change any settings for scripts, cookies, or SSL. Use defaults.

- Refresh. JavaScript will be enabled.

- Expected result: Since the JavaScript Settings are set to use default for browserleaks.com, then JavaScript should remain disabled.

- Actual result: JavaScript is enabled.

- Device: iPhone 5s, iOS 12 Beta 1.

Note: This issue also affects Endless Browser.

**Comment by DavidMOliver** [comment]
I want to add this to milestone 2.2

**Comment by jcs** [comment]
Commit in Endless:

https://github.com/jcs/endless/commit/bd485b7acaedd05a0a964f193d1eb1d2e1f109d1

**Comment by tladesignz** [comment]
Oh, great! Thank's a lot @jcs, to mention this here. Would probably have spent some hours to find this myself, since an Endless pull is currently scheduled for a later milestone...

**Comment by tladesignz** [comment]
Will be fixed with #128

**Comment by tladesignz** [comment]
Fixed by fixing #128.
