### ISSUE TITLE
videos dont load anymore

### ISSUE THREAD

**Issue by barryason** [OnionBrowser/iOS-OnionBrowser#147]
Hello, please help. 
Since update no video on any site works. Everytime theres coming Error Loading ‚Retry‘. Whats wrong, it works fine for 1 Year?.. iPad fault or gameover for videos on tor?

iOS iPad Pro 11.3
greetings

**Comment by tladesignz** [comment]
Just checking this during development. 

Works fine for me with Youtube. Content Policy needs to be set to "open", of course, otherwise, no video.

In your case, there could also be a lot of different other issues standing in the way. No address provided, no further investigation possible.
