### ISSUE TITLE
Support swapping over to .onion if there's an appropriate alt-svc header

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#148]
Given an HTTP header in the response (on a clearnet website, for example `www.propublica.org`) that looks like this:

```
Alt-Svc: h2="www.propub3r6espa33w.onion:443"; ma=86400; persist=1
```
(ma being "max age")

The client _should_ either automatically use (or give the user the option to use?) the onion domain (in this case `www.propub3r6espa33w.onion`) instead.

---

[Tor Browser Bundle 8](https://blog.torproject.org/new-release-tor-browser-80) supports alt-svc:
* https://trac.torproject.org/projects/tor/ticket/26365
* https://trac.torproject.org/projects/tor/ticket/24553

Right now there's [no indication in TBB's UI](https://trac.torproject.org/projects/tor/ticket/27590) that the underlying connection is using the onion service, but in addition to [that ticket](https://trac.torproject.org/projects/tor/ticket/27590) to at least show that in the circuit list, [there are some ideas on UX for making it user-optional](https://trac.torproject.org/projects/tor/attachment/ticket/21952/21952.png).

More:

* Some info from a CloudFlare demo site: https://perfectoid.space/
* Brave ticket: https://github.com/brave/brave-browser/issues/1121
* Some quick notes from me on the tor-onions list: https://lists.torproject.org/pipermail/tor-onions/2018-September/000301.html

**Comment by tladesignz** [comment]
Just read through this:
https://write.privacytools.io/jonah/securing-services-with-tor-and-alt-svc

and found this:

> The domain name stays the same. Instead of adding a .onion domain to Nginx, we're sending all requests using the same hostname. If you're familiar with the OSI 7 layer model, we're replacing the Transport (layer 4) TCP layer with a .onion connection while not touching anything on the Application layer (layer 7).

And, indeed, `write.privacytools.io` provides the following header:

`alt-svc: h2="privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion:443"; ma=86400; persist=1`

But when you use that address, you will see `www.privacytools.io`, instead of `write.privacytools.io`.

Since we're manipulating HTTP requests in Onion Browser, I don't see a way to get into the TCP packet and just change that address. Do you?

I mean, we could do a redirect for the HTTP request to the .onion address and add a HTTP `Host` header containing the original address. But is that actually the same?

@mtigas, what do you think about this?

**Comment by mtigas** [comment]
Yeah I think my original read of this when writing the ticket was wrong and it 1) shouldn't redirect and 2) it should automatically happen if the onion works, without prompting the user.

> And, indeed, `write.privacytools.io` provides the following header:
> 
> `alt-svc: h2="privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion:443"; ma=86400; persist=1`
> 
> But when you use that address, you will see `www.privacytools.io`, instead of `write.privacytools.io`.

I wonder what happens when making that connection over `.onion`, but still sending `Host: write.privacytools.io`?

> Since we're manipulating HTTP requests in Onion Browser, I don't see a way to get into the TCP packet and just change that address. Do you?

Not in the current way that things are set up.

> I mean, we could do a redirect for the HTTP request to the .onion address and add a HTTP `Host` header containing the original address. But is that actually the same?

I've thought about this, but think this isn't going to be the right behavior in some cases.

I think the right behavior for us is something like:
* If we see an `alt-svc` with an onion, have some kind of `plain domain -> onion domain` mapping that we keep (through the expiration time) and put it in there.
* Find some way to decouple the connection host from the HTTP `Host: ...` header, so we change one but not the other. We replace the plain domain with onion when making the connection; but we force `Host` to stay as what we had before.

Maybe?

...Though I think this is probably a feature we put off until we have a network extension or some solution for WKWebView.

**Comment by tladesignz** [comment]
Ah. Why wait. I'll try it out.

**Comment by tladesignz** [comment]
😭 Almost got it working. Still have issues with TLS certificates not containing the .onion domain, but I guess that would have been solvable.

Real dealbreaker however is this:

https://developer.apple.com/documentation/foundation/nsurlrequest#overview

> Reserved HTTP Headers
>
> The URL Loading System handles various aspects of the HTTP protocol for you (HTTP 1.1 persistent connections, proxies, authentication, and so on). As part of this support, the URL Loading System takes responsibility for certain HTTP headers:
> [...]
> Host

Can't modify the host header, so can't reach virtual hosts on a server using them. (Like... all, nowadays...)

**Comment by tladesignz** [comment]
Ok, no new input on this. I'll close it for now.
