### ISSUE TITLE
Connect to Tor in background when opening app.

### ISSUE THREAD

**Issue by kamil6x** [OnionBrowser/iOS-OnionBrowser#152]
When starting the app. allow the user to start typing the internet address, while connecting to the Tor network in the background.  This will allow the user to start typing instead of having to wait for the Tor connection.

**Comment by tladesignz** [comment]
Sorry, this won't happen anytime soon. This would mean a complete redesign of the app. To my knowledge, there's no budget for this, currently and I'm not even sure, it's really doable, considering the different usage scenarios.

However, we will release v2.2.0 soon, which will finally support background restart of Tor, when the app is revisited. That will probably alleviate a lot of your pain.

**Comment by kamil6x** [comment]
Noted thanks for replying.
