### ISSUE TITLE
OB leaks real time zone, update list of caveats

### ISSUE THREAD

**Issue by MarkCallow** [OnionBrowser/iOS-OnionBrowser#153]
browserleaks.com shows that Onion Browser leaks my actual time zone.

**Comment by tladesignz** [comment]
Sorry that it took us so long, however, here's at least *some* answer, unsatisfyingly, though:

As per @mtigas:
> There's an entire class of things that are nearly impossible to defend against since we can't exactly block webkit's JS engine from responding correctly with a bunch of things. The app isn't fingerprint-resistant because we can't do a lot about WebKit.

However, we most definitely need to update our communication and add this to our list of caveats.

**Comment by PsiPhiTheta** [comment]
Where is the list of caveats? I can go ahead and fix this with a PR

**Comment by ghost** [comment]
> Where is the list of caveats? I can go ahead and fix this with a PR

@PsiPhiTheta 
https://github.com/OnionBrowser/onionbrowser.github.io/blob/master/index.html
