### ISSUE TITLE
Twitter playback

### ISSUE THREAD

**Issue by Lwxc0** [OnionBrowser/iOS-OnionBrowser#155]
first of all thanks for the great app, you have no idea how much it helps people like me.
Second of all recently i had a funny problem with twitter as i use the browser mainly to browse it due to the censorship in my country and to avoid any legal problem. anyway when i open a small video 6 or 7 sec max it works fine but when i try to open any video exceeds this it tells me "We cannot play the video in this browser. Please try a different web browser." i tried to open youtube videos as a test and it worked fine in the browser. i really wish you can fix it soon it would help so much.

**Comment by tladesignz** [comment]
Hey, thanks for the feedback!

We're releasing version 2.2.0 soon. Could you please check again with that version, when it's available? 
Thanks for your patience until then!
