### ISSUE TITLE
Facebook over Onion browser does not log in

### ISSUE THREAD

**Issue by mireksochor** [OnionBrowser/iOS-OnionBrowser#156]
Login over Onion browser on https://www.facebookcorewwwi.onion does not perform the login action (login button go back to idle state) . Desktop Tor browser does not have that issue.

**Comment by tladesignz** [comment]
Can verify that behaviour with current version 2.1.0. 
However, I can also very, that it will also work with the latest, soon-to-be-released, version 2.2.0.

Please be patient a few more weeks.
