### ISSUE TITLE
Homepage onions are currently broken (kCFErrorDomainCFNetwork error 120)

### ISSUE THREAD

**Issue by nbrsrk** [OnionBrowser/iOS-OnionBrowser#164]
Since recent update getting error 120. 
On iOS 12.2 6s Not jailbroken
“kCFErrorDomainCFNetwork error 120.”
Version 2.2.0

**Comment by tladesignz** [comment]
I guess, you're talking about this:

![kCFErrorDomainCFNetwork](https://user-images.githubusercontent.com/117089/55001125-35748300-4fd4-11e9-9b7c-194445b82703.png)

I'm sorry, I got so used of clicking that away, that I totally forgot to follow up on it.

@mtigas Do you have an idea, why that happens?

Some of our preloaded favorites are affected, too:

http://tigas3l7uusztiqu.onion/
http://3heens4xbedlj57xwcggjsdglot7e36p4rogy642xokemfo2duh6bbyd.onion/
http://expyuzz4wqqyqhjn.onion/

**Comment by n8fr8** [comment]
Same issue with nytimes onion

![IMG_1527](https://user-images.githubusercontent.com/30851/55001793-be2af900-4fab-11e9-9ef3-c4e39c4ade9d.PNG)

**Comment by n8fr8** [comment]
however, notice the onion site still loads!

**Comment by mtigas** [comment]
The onions for the default homepage(s) and those preloaded bookmarks (like my site) hit the same proxy server that I run -- I'll look today to make sure that these "error 120" things aren't actually being caused server-side on my end.

**Comment by tladesignz** [comment]
@n8fr8 The error message is from the initial page load, which doesn't work. Notice the URL. Not the same as NYT, but identical to the one in my screenshot.

**Comment by mtigas** [comment]
ok, i *think* the issues with `3heens4xbedlj57xwcggjsdglot7e36p4rogy642xokemfo2duh6bbyd.onion` and etc are fixed now. as i suspected, it was an issue on my end and not in the app itself.

please feel free to comment here or open a new ticket if you encounter any continuing issues with onion sites that you can confirm to be working elsewhere

**Comment by tladesignz** [comment]
This one shows a 404:
http://tigas3l7uusztiqu.onion/onionbrowser/

Should we remove that from the bookmarks?

**Comment by nbrsrk** [comment]
confirmed. issue resolved. excellent. thanks!
