### ISSUE TITLE
Captcha looping after update

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#166]
Captchas don’t work anymore

**Comment by tladesignz** [comment]
Do you have an example?
Because this works: https://recaptcha-demo.appspot.com
And Recaptcha v2 is currently the most used captcha on the web.

**Comment by ingfabby** [comment]
I don't,  a user posted it yesterday in the Apple App Store,  but l will
ask him.

**Comment by tbugfix** [comment]
The captchas worked when the strict No Java settings were on before the update, now they won’t work unless you have the  No XHR/ WebSocket setting on. The recaptcha demo may work but any captcha on tor, including all of the dark markets that require one...  you can’t see the captchas or any images. Did the Strict no Java not work on the last version or is there something wrong with the new update?

**Comment by tladesignz** [comment]
Followed up in #174.
