### ISSUE TITLE
Unique fingerprint

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#167]
I have tried to protect from fingerprinting by disabling Javascript and spoofing useragent to Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0
However, the fingerprint is still unique because of extremely uncommon HTTP_ACCEPT Headers
Please check the issue on https://panopticlick.eff.org and implement an option to change HTTP_ACCEPT Headers to text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 gzip, deflate, br en-US,en;q=0.5

**Comment by tladesignz** [comment]
Sorry that we never answered this.
Yeah, it is well known.

As per @mtigas:

> There's an entire class of things that are nearly impossible to defend against since we can't exactly block webkit's JS engine from responding correctly with a bunch of things. The app isn't fingerprint-resistant because we can't do a lot about WebKit.

Related: #153
