### ISSUE TITLE
Open in Background Tab

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#168]
The last update has a problem with embedded images and proper spacing between the search bar and iOS info such as time and date.

**Comment by VectorABC** [comment]
Same bug as here in which disabling JavaScript also disabled images?:

https://github.com/OnionBrowser/OnionBrowser/issues/123#issuecomment-478248235

**Comment by VectorABC** [comment]
...also, with JavaScript off we lose the popup menu option to open links in a new tab. That is an internal browser function, not JavaScript! Please enable it always and add a *background* tab option to make it practical.

**Comment by tladesignz** [comment]
> The last update has a problem with embedded images 

You mean #123? I just fixed it.

> and proper spacing between the search bar and iOS info such as time and date.

You mean #169? I fixed that yesterday.

**Comment by tladesignz** [comment]
> ...also, with JavaScript off we lose the popup menu option to open links in a new tab. That is an  internal browser function, not JavaScript! Please enable it always 

Sorry, I can't reproduce that. I long-tap on a link and the expected pop-up pops up just fine. Can you take a second look and if your experience persists, can you give me more details? Device, iOS version, website used, exact link trying to be tapped, exact expected behaviour? Thanks a lot!

> and add a background tab option to make it practical.

That's a great idea. I'll add that immediately!

**Comment by VectorABC** [comment]
This is a big deal. Thanks immensely.

>> and add a background tab option to make it practical.
>
> That's a great idea. I'll add that immediately!

**Comment by tladesignz** [comment]
You're welcome!

**Comment by VectorABC** [comment]
The open in background tab only appears with JavaScript enabled.

**Comment by tladesignz** [comment]
@VectorABC: Thanks!

I already experienced this and we're tracking the root cause here: #196
