### ISSUE TITLE
Address bar overlaps status bar on ipad.

### ISSUE THREAD

**Issue by HiddenAlx** [OnionBrowser/iOS-OnionBrowser#169]
You can see on the [picture](https://www.dropbox.com/s/6fz1yp2j24ovu85/IMG_0183.PNG) 
iPad pro 10.5 inches, iOS 12.0, Onion Browser v2.2. Bug appears only in album orientation of iPad. There is no this bug in previous Onion Browser versions.

**Comment by tladesignz** [comment]
Thanks for recognizing this!
