### ISSUE TITLE
Make homepage onion services more resilient

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#170]
@mtigas, isn't this your server?

http://3heens4xbedlj57xwcggjsdglot7e36p4rogy642xokemfo2duh6bbyd.onion/

That address seems broken again. Can you look into this?

**Comment by tladesignz** [comment]
![Simulator Screen Shot - iOS 12 2 @ iPad Pro - 2019-04-03 at 10 29 09](https://user-images.githubusercontent.com/117089/55464392-53a53900-55fb-11e9-86da-bbde535e3d11.png)

**Comment by tladesignz** [comment]
Did you fix it? Because it's working again.

**Comment by mtigas** [comment]
this corresponded with a provider outage that went about 12 hours. i think things have been back to stable since then.

**Comment by mtigas** [comment]
It's down again and I think I know what it is, but I'm literally unable to fix that specific server until Monday. (I'm out of town visiting family and I don't have the necessary SSH key on any devices here.)

I'm going to see if i have a backup copy of the hidden service key so i can at least get _something_ running again.

**Comment by mtigas** [comment]
Fixed, and I've got a copy of the `hs_ed25519_secret_key` so provisioning replacements shouldn't take too long in the future.

I'll look into putting up OnionBalance so I can get some redundancy which wouldn't require human intervention.

**Comment by tladesignz** [comment]
And again, @mtigas!

**Comment by mtigas** [comment]
Should be up again now. I'm gonna re-do things so that the actual page content comes from https://github.com/OnionBrowser/onionbrowser-homepage and will also set up another repo with the actual tor hidden service (+ nginx proxy) config and some tooling for spinning up containers that run the hidden service.

**Comment by tladesignz** [comment]
@mtigas Your Tor services are down again since a long time...

**Comment by mtigas** [comment]
It's working for me now. A few months ago I moved it to containers such that it _should_ restart if Tor or nginx die. (I wonder if it's doing something where it stops working but the process doesn't exit yet. I probably could whip something up that will kill the containers / spin up new ones every 12 hours or something, as a safety measure.)

**Comment by tladesignz** [comment]
I think that was a mirror of onionbrowser.com in the past. Not anymore I guess? Should I remove that from the default bookmarks? Do you want to create a new .onion domain for onionbrowser.com?

![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-03-23 at 21 02 48](https://user-images.githubusercontent.com/117089/77358185-afeff400-6d49-11ea-866f-72cc37d9e94c.png)

**Comment by tladesignz** [comment]
Sorry, @mtigas, I removed all links to that domain now (3aabaaa7cd58f25ab1bd0d5030f87e34073b8908), as it is down for months on end now.
