### ISSUE TITLE
 Browser doesn’t display properly on 11 inch iPad

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#172]
Also, for some sites to work the browser needs to be completely opened up which could be problematic.

*We got this from a user at the Apple Store, I do not have an 11 Inch iPad so I can't test that.

**Comment by tladesignz** [comment]
Well, unfortunately, this is not very precise.
Maybe #169 was meant. That is fixed.

Regarding the "completely opened up". Not sure what's that supposed to mean. Maybe the split view/slide over features?

Look good to me with the latest developer version.


![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 48 30](https://user-images.githubusercontent.com/117089/56664625-b80e6200-66a8-11e9-98a4-eb5245b078a7.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 48 33](https://user-images.githubusercontent.com/117089/56664626-b80e6200-66a8-11e9-9b7f-9e49bf9bd1a5.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 48 37](https://user-images.githubusercontent.com/117089/56664628-b80e6200-66a8-11e9-9276-72a450461207.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 50 08](https://user-images.githubusercontent.com/117089/56664630-b8a6f880-66a8-11e9-8a17-87b81dfc160b.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 50 11](https://user-images.githubusercontent.com/117089/56664632-b8a6f880-66a8-11e9-8cb6-06b1cec48603.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 50 20](https://user-images.githubusercontent.com/117089/56664633-b8a6f880-66a8-11e9-8757-693003a31c9e.png)
![Simulator Screen Shot - iOS 12 2 @ iPad Pro 11  - 2019-04-24 at 15 50 23](https://user-images.githubusercontent.com/117089/56664634-b93f8f00-66a8-11e9-8144-81bcefdc54d3.png)

**Comment by tladesignz** [comment]
(And, yeah: Not every website likes it, if it doesn't have enough width. Nothing, which OB could change, though...)
