### ISSUE TITLE
Captchas Not Working After Update(Strict No Java)

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#174]
The captchas worked when the strict No Java settings were on before the update, now they won’t work unless you have the No XHR/ WebSocket setting on. You can’t see the captchas or any images on some sites. Did the Strict no Java setting not work on the last version or is there something wrong with the new update?

**Comment by tladesignz** [comment]
Sorry, but this is too vague. As long as you can't provide an example/a URL of an example, we can't help you.
Besides, it may well be, that a captcha just doesn't work without JavaScript. However, you can't have the cake *and* eat it.

Same counts for images. There are sites, which use JavaScript for image loading.

Unfortunately, please be advised, that the iOS platform is not fully secure with JavaScript enabled. Read #117 for details.

Feel free to reopen, when you have an example!

**Comment by ghost** [comment]
Even the test url from thread #166 doesn’t work without java script enabled on OB. I tried it last night.

**Comment by tladesignz** [comment]
That example doesn't work on *any* browser without JavaScript. Recaptcha just doesn't work without JavaScript. Probably many don't, nowadays. That's annoying, but there's no way around that, for a browser.
