### ISSUE TITLE
Orbot does not stop

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#175]
Device  Huawei nova 3i device
Android 9
  Orbot still running event when I push the stop button on the background and cannot access to any website

**Comment by n8fr8** [comment]
Please post on the Orbot issues. This is Onion Browser.


n Sun, Apr 21, 2019, at 8:27 PM, ingfabby wrote:

**Comment by ingfabby** [comment]
Thanks,  sorry about that.
