### ISSUE TITLE
Add support for making Onion Browser the system default browser

### ISSUE THREAD

**Issue by Jeehut** [OnionBrowser/iOS-OnionBrowser#176]
I've just read [this article](https://medium.com/spacebrowser/how-to-set-the-default-browser-on-ios-6d8ebc9cc9b) where the developers of [Space Browser](https://www.spacebrowser.io/) found an interesting way how users can actually set their default browser in iOS with a small trick. Basically, the steps required are:

1. Open the Settings app
2. Tap "Screen Time"
3. Tap "Content & Privacy Restrictions"
4. Tap "Allowed Apps"
5. Turn off "Safari"

This way, Safari won't be opened any more when links are clicked in any app starting with `http://` or `https://`. But currently clicking links won't do anything with this setup, even with OnionBrowser installed.

To make this work, OnionBrowser needs to add `http://` and `https://` as custom URL schemes according to the post. I haven't tried it myself yet, but they report it's working and since it wouldn't hurt to add these custom schemes anyway, I feel it's worth a try.

**Comment by mtigas** [comment]
i commented in matrix:

> i think if doesn't see any obvious (or not-so-obvious) downsides to this, then i'm OK with it. so let's do it, then we can at least test that out in some builds and afterward write up some documentation for this "default browser" feature.

**Comment by tladesignz** [comment]
Turns out: This is more common than you would think. I had to delete 2 other apps, to finally make Onion Browser the one to catch the links.

Now we might need a good UI explaining that feature. @m4mb01t4l14n0 ?

**Comment by tladesignz** [comment]
So this went into the 2.3.0 release, already. People can use it. They just need to find it. I'll close it for now, if there's no interest to explain it.
