### ISSUE TITLE
Browsing Issue

### ISSUE THREAD

**Issue by Satyendrabhati** [OnionBrowser/iOS-OnionBrowser#179]
How to connect or use Onion Browser Without Connecting Tor.I am little bit Confused to Establish Connection With browser Without tor.

**Comment by tladesignz** [comment]
Sorry, Onion Browser cannot be used without Tor. That's the whole point of it. May I ask, what's your reason to want this?

**Comment by Satyendrabhati** [comment]
Our Development team integrated all the functionality of onion browser and add more features to make our product batter.it will work fine but our client need is that search the urls without tor also so we have facing this issue and this is not possible to deliver the same project on time with other browsers.

**Comment by mtigas** [comment]
Please see [Endless](https://github.com/jcs/endless), which is the base browser that Onion Browser is based on. It contains the same user interface and some of the same privacy settings, but it does not include Tor. Onion Browser is explicitly designed as a browser which integrates Tor.

**Important note**, since it appears that you are utilizing this for some manner of product: The license for both Endless and Onion Browser **do not allow you to distribute binaries** of any app based on Endless (regardless of it is free or commercial), unless you get permission from the author of Endless:  
https://github.com/jcs/endless/blob/master/LICENSE

> (NOTE: This is not a BSD/ISC/MIT license.  You are permitted to use this
> source code, with or without modification, in source or binary form, on
> your devices however you see fit.  You are not permitted to redistribute
> binaries of this source code, with or without modification.  In other
> words, you cannot put this application or any application derived from
> it, on the Apple App Store, Cydia, or any other binary-only distribution
> channel.)
> 
> [...]
> 
> Redistribution and use in source form, with or without modification,
> and use in binary form, is permitted provided that the following conditions
> are met:
> 
> 1. Redistributions of source code must retain the above copyright
>    notice, this list of conditions and the following disclaimer.
> 2. The name of the author may not be used to endorse or promote products
>    derived from this software without specific prior written permission.
> 
> Redistribution of this project in binary form, with or without modification,
> is NOT permitted without the explicit written permission of the Endless
> copyright holder.

**Comment by Satyendrabhati** [comment]
So what’s the plan or pricing for purchase the licence of onion or endless.

**Comment by mtigas** [comment]
Please contact @jcs directly, as he is the author of Endless. See the Endless readme https://github.com/jcs/endless/blob/master/README.md ; there is a link to his contact information there.

**Comment by Satyendrabhati** [comment]
Hello Mike,
          Good afternoon,
          Trust you are doing good, We have a problem may you help us out.Problem is that we need to search URL's With and without tor also in my app and we have already implemented project with Onion Browser.We will definitely purchase the licence but you already told that Onion is not work without tor and Endless Does't Support tor functionality.

I Will wait for the best suggestion.
