### ISSUE TITLE
Settings Menu - move "informational settings" to subordinate menu

### ISSUE THREAD

**Issue by r3ckd** [OnionBrowser/iOS-OnionBrowser#181]
"URL Blocker" and "HTTPS Everywhere" are lists of URLs that are either being blocked (first) or are part of HTTPS Everywhere (second).  There are no actual user actions to take relative to these items.  So, it is useful information but not actionable.  Create a sub-menu for these.

**Comment by tladesignz** [comment]
Results of UX research/redesign found in #210
