### ISSUE TITLE
Endless UX: how to properly show certification (and onion) information?

### ISSUE THREAD

**Issue by r3ckd** [OnionBrowser/iOS-OnionBrowser#182]
Current exposure of cert information not too informative to user.  Mechanism for accessing security status (onion or HTTPS) information not well-designed from user perspective.  Tor Browser for desktop is good role-model for this UX (Firefox itself also good).

**Comment by r3ckd** [comment]
Firefox on iOS -- useful as a mobile app example (instead of Tor desktop app)

**Comment by tladesignz** [comment]
Related to #132 .
Ultimately, all Tor and TLS aka. SSL aka. HTTPS infos should be available here.

**Comment by tladesignz** [comment]
Onion info now implemented as per issues #223, #132, #195, #67

**Comment by tladesignz** [comment]
Well, we still have two screens for TLS certificates and Onion circuits, but as far as I see, there's no plans to improve that for now, so I close this issue.
