### ISSUE TITLE
Endless UX: review of toolbar and drop-down menu design 

### ISSUE THREAD

**Issue by r3ckd** [OnionBrowser/iOS-OnionBrowser#184]
improvements to the opening "scene" of OB.  
a. can toolbar "fade away" when scrolling
b. "toolbar on bottom" setting (global settings) does not work properly in some releases. 
c. should there be two toolbars a la Safari?  
d. iPad vs iPhone difference or not?

**Comment by tladesignz** [comment]
Results of UX research/redesign found in #210
