### ISSUE TITLE
App crashes everytime I start after I configure bridge 

### ISSUE THREAD

**Issue by GentleNi** [OnionBrowser/iOS-OnionBrowser#187]

**Comment by GentleNi** [comment]
![image](https://user-images.githubusercontent.com/8778040/57602608-29e41800-7592-11e9-966e-c6ce4bc844fc.png)

**Comment by tladesignz** [comment]
Unfortunately, this is not a crash, but the Tor connection attempt timing out. I'd say, the bridge you're using is blocked in your country.
Are you in mainland China?
Which bridge where you using?

**Comment by GentleNi** [comment]
> Unfortunately, this is not a crash, but the Tor connection attempt timing out. I'd say, the bridge you're using is blocked in your country.
> Are you in mainland China?
> Which bridge where you using?

Thanks for your reply.
Yep I'm in China.
The bridge is deployed on a U.S. server， which use obfs4 plugin. But I can connect to tor on Windows Tor Broswer using this bridge.

Also I can connect  on ios by using meek plugin  why not obfs4?

**Comment by mtigas** [comment]
@GentleNi After configuring your obfs4 bridge, can you try to [force-quit the app](https://support.apple.com/HT201330) and open it again? (We previously had an issue, #140, where if you change the bridges, the setting does not actually take effect until the app is quit and then started again. It was fixed, but maybe we might be having that issue again.)

We'll also do some more research over the next few days.

**Comment by tladesignz** [comment]
Ok, did some testing. It seems, changes to the bridge configuration aren't properly adapted anymore.

That's definitely something to fix.

Anyhow, @GentleNi, can you try changing to your preferred obfs4 bridges, then force-quit the app (pushing the app card out of the app overview) and then restart? It should work then. Would be nice, if you could check that. Thanks!

**Comment by GentleNi** [comment]
I re-download the onion broswer again, and follow your steps.
It crash again. 
Here is my steps:
1. re-download app
2. click setting button-> select "custom bridge"->paste my bridge config->click back button
 -> click Done button 
3. force quit the app
4. restart app, then it crash again




------------------ 原始邮件 ------------------
发件人: "Benjamin Erhart"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 晚上9:55
收件人: "OnionBrowser/OnionBrowser"<OnionBrowser@noreply.github.com>;
抄送: "倪锦涛"<562391834@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [OnionBrowser/OnionBrowser] App crashes everytime I start after Iconfigure bridge  (#187)




Ok, did some testing. It seems, changes to the bridge configuration aren't properly adapted anymore.
 
That's definitely something to fix.
 
Anyhow, @GentleNi, can you try changing to your preferred obfs4 bridges, then force-quit the app (pushing the app card out of the app overview) and then restart? It should work then. Would be nice, if you could check that. Thanks!

**Comment by GentleNi** [comment]
and my device is iphone7, ios 12.2

**Comment by tladesignz** [comment]
Since this is 3/4 of a year old, I'll close it.

Please try the latest published version. (2.5.0 is out since a few days.) I fixed some issues in conjunction with bridges. Also the error scene from the screenshot above is gone.
