### ISSUE TITLE
Unable to turn off JavaScript

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#192]
App Version 2.2.1
Reported on May/24/18 on the Apple app store

**Comment by mtigas** [comment]
Javascript can be disabled inside the "Host Settings" menu.
* To disable Javascript globally, the "Default Settings" item should be selected.
* To disable Javascript for a specific site, the plus (+) sign can be used to add a domain.

Inside this menu, settings "Content policy" to "Strict" will disable Javascript and other features which may cause information leaks.

Just tested this and can confirm the feature is still working. I'll respond to that App Store review.

**Comment by mtigas** [comment]
Should probably have some text inside the "Global Settings" page that notes this, though.
