### ISSUE TITLE
Lock Screen from Home Button

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#194]
user comment:  the ability to lock/unlock the browser screen with the Home button like the DuckDuckGo browser does. Blurring the backgrounded snapshot is very good, but anyone can tap it and immediately see the web page you were reading. (Yes, there are plenty of users who still have and use the home button.)

**Comment by mtigas** [comment]
Right. This is not unlike the "Screen Lock" feature in Signal, which locks the app when you switch out of it, and then requires either your PIN/passcode or Touch ID / Face ID (if enabled).

I've had it as a low priority (and I've been on the fence as to whether it's even an effective feature or not), and just kind of forgot about it. So let's leave this one open so we don't forget.

**Comment by m4mb01t4l14n0** [comment]
Is this something we'd like carries input on in terms of user experience or
is this pretty straightforward for you to do?

**Comment by tladesignz** [comment]
Implemented!
