### ISSUE TITLE
Switch to ("rotate among") Tor circuits when Tor is slow

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#195]
user comment: Also needs the feature to auto-select or rotate to a different TOR connection if the one in use is very slow.

**Comment by mtigas** [comment]
This is a sub-task of #132 (menu thing to show the current tor circuit). It's the "new circuit" button here:
![Screenshot from 2019-06-06 14-12-14](https://user-images.githubusercontent.com/53129/59056073-54f61a80-8865-11e9-884e-c26b205e10c0.png)

(Not sure if we just want to close this one and make sure this is part of the spec for working on #132.)

**Comment by m4mb01t4l14n0** [comment]
Okay Mike that's great. I will close or delete that task.

**Comment by tladesignz** [comment]
Fully implemented with a9a78ca!
