### ISSUE TITLE
Update App Store screenshots (new: iPhone 6.5-inch and iPad 12.9-inch 3rd Gen)

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#197]
Looks like we've got to get some new assets into https://github.com/OnionBrowser/OnionBrowser/tree/2.X/AppStore/Screenshots

Will try to do some of these over the weekend so I can submit 2.2.1 for review. I've got Search Ads already configured based on David's notes from last time we ran them (just paused the campaign after I configured it), so I think everything else is ready to go.

---

*edit: adding a checklist here*

The required sizes are 12.9 inch iPad Pro (2nd Gen), 12.9 inch iPad Pro (3rd Gen), 6.5 inch iPhone, 5.5 inch iPhone. After looking at the App Store metrics, it looks like App Store impressions in Russia actually outpace those in the U.S. Additionally, I think the Middle East is another focus area for our work. We didn't have an Arabic or a Russian localization when we last went through these, so I've added those to this checklist too.

**New sizes:** (If not complete, App Store will fall back to English screenshots.)

6.5 phone (Xs Max, Xs, etc. replaces 5.8 inch size for X/Xs):  
- [x] English
- [ ] Arabic
- [ ] Dutch
- [ ] French
- [ ] German
- [ ] Japanese
- [ ] Norwegian
- [ ] Portuguese (Brazil)
- [x] Russian
- [ ] Spanish (Spain)

12.9 iPad Pro 3, etc:  
- [x] English
- [x] Arabic
- [x] Dutch
- [x] French
- [x] German
- [x] Japanese
- [x] Norwegian
- [x] Portuguese (Brazil)
- [x] Russian
- [x] Spanish (Spain)

**Updates to sizes we had before:** (asterisk `*` indicates that we don't have an old version of this size, so App Store will default to English if we haven't uploaded screenshots for this language)

5.5 phone (8 Plus, 8, etc):  
- [x] English
- [x] Arabic*
- [ ] Dutch*
- [ ] French
- [ ] German
- [x] Japanese*
- [ ] Norwegian
- [x] Portuguese (Brazil)*
- [x] Russian*
- [ ] Spanish (Spain)

12.9 iPad Pro 2, etc:  
- [x] English
- [ ] Arabic*
- [ ] Dutch*
- [ ] French
- [ ] German
- [ ] Japanese*
- [ ] Norwegian
- [ ] Portuguese (Brazil)*
- [x] Russian*
- [ ] Spanish (Spain)

**Comment by mtigas** [comment]
OK, just to keep track; this is where it's at as of the v2.2.1 that I just tagged on 87902a7cde55977154f1a6d4cc0cc34aff458e09

---

**New sizes:** (If not complete, App Store will fall back to English screenshots.)

6.5 phone (Xs Max, Xs, etc. replaces 5.8 inch size for X/Xs):  
- [x] English
- [ ] Arabic
- [ ] Dutch
- [ ] French
- [ ] German
- [ ] Japanese
- [ ] Norwegian
- [ ] Portuguese (Brazil)
- [x] Russian
- [ ] Spanish (Spain)

12.9 iPad Pro 3, etc:  
- [x] English
- [x] Arabic
- [x] Dutch
- [x] French
- [x] German
- [x] Japanese
- [x] Norwegian
- [x] Portuguese (Brazil)
- [x] Russian
- [x] Spanish (Spain)

**Updates to sizes we had before:** (asterisk `*` indicates that we don't have an old version of this size, so App Store will default to English if we haven't uploaded screenshots for this language)

5.5 phone (8 Plus, 8, etc):  
- [x] English
- [x] Arabic*
- [ ] Dutch*
- [ ] French
- [ ] German
- [x] Japanese*
- [ ] Norwegian
- [x] Portuguese (Brazil)*
- [x] Russian*
- [ ] Spanish (Spain)

12.9 iPad Pro 2, etc:  
- [x] English
- [ ] Arabic*
- [ ] Dutch*
- [ ] French
- [ ] German
- [ ] Japanese*
- [ ] Norwegian
- [ ] Portuguese (Brazil)*
- [x] Russian*
- [ ] Spanish (Spain)

**Comment by tladesignz** [comment]
Maybe we should spend some time and do another try to automate that with http://fastlane.tools ?

Last time, though, there were race conditions and thread blocks during the Tor startup phase. In general, I'm not very impressed with Fastlane. Everytime I tried to use it, it generated more work than it should relieve me of. The only thing which works great is the app icon generator plugin. :-/

**Comment by tladesignz** [comment]
Let's forget about this. I removed all non-english screenshots. English screenshots are now for all, these are up-to-date.
