### ISSUE TITLE
Localize / refactor in-app donations

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#198]
I pulled in some old in-app purchase code in 0c4191f75619832cf110cf681f1c1f14698bd8d9 that seemed to be lost along the way. I know I had it in some very early 2.0 release, but I must've been deploying off of a branch or something?

This should totally be rewritten first of all. Second, it'd maybe be a good idea to make the paragraph content live external to the app (possibly same `.onion` service that hosts the homepage?) and localize it.

Just dropping this ticket here so I don't forget. No milestone attached yet.

**Comment by tladesignz** [comment]
Done with commit 4ee850035c7cb0428a89261b6031318635da4594.
