### ISSUE TITLE
Seeking guidance...

### ISSUE THREAD

**Issue by Fonta1n3** [OnionBrowser/iOS-OnionBrowser#199]
Hi, thanks for the great app and general work, it is greatly appreciated.

I have been developing an open source, free bitcoin wallet that allows passionate bitcoin users to connect directly to their full node to power the backend of the app.

The dream is to allow connectivity by Tor hidden service as this is optimal for bitcoin usage.

I am using Tor.framework to do this and have gotten as far as successfully making the connection to and controlling the node via a V3 hidden service in my app BUT its only working on the simulator. I can NOT get a .onion url request to go through on the device itself.

In Onion Browser I can input the url and get a response though. Since Onion Browser is using Tor.framework you guys must know what the work around is. 

Can you nudge me in the right direction? 

I have spent a lot of time going over the code but I can not pinpoint the exact location in your code where the NSURL session is being called, or what code you have used to allow connecting to hidden services.

Any guidance would be greatly appreciated.

**Comment by tladesignz** [comment]
In OnionBrowser, we use a (deprecated, yes, we know) `UIWebView` and intercept its calls with https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Endless/URLInterceptor.m

https://github.com/OnionBrowser/OnionBrowser/blob/4ee850035c7cb0428a89261b6031318635da4594/Endless/AppDelegate.m#L38-L39

Check it out, if that can help you!

**Comment by Fonta1n3** [comment]
Thanks for the hint! Greatly appreciated. Interestingly I found another framework CPAProxy and others have had the same issue I am having with that framework. Will check this out and revert.

**Comment by Fonta1n3** [comment]
Finally able to start working on this again. I will give the simplified interceptor at the bottom a go. 

My question is what is the difference between running Tor on the ios device as compared to simulator that requires me to use an interceptor in the first place?

**Comment by tladesignz** [comment]
> My question is what is the difference between running Tor on the ios device as compared to simulator that requires me to use an interceptor in the first place?

See my comment on my other thread. You will *always* need an interceptor, otherwise you don't reroute the traffic to your running Tor thread.

If you still connect via Tor on the simulator, then that's because you probably run a MacOS Tor daemon which gets the traffic from the simulator.

BTW, check out Psiphon's interceptor:

https://github.com/Psiphon-Inc/endless/tree/master/External/JiveAuthenticatingHTTPProtocol

That's way more modern than what we have in OnionBrowser currently. In fact, I'm in the process of adapting that to OnionBrowser.

**Comment by Fonta1n3** [comment]
so even if I am making my url request directly through the tor client like so: 

`let task = self.torClient.session.dataTask(with: request) { (data, response, error) in`

I will still need an interceptor?

Thanks for the info and the link.

**Comment by tladesignz** [comment]
Aaah, you mean you created a URLSession as per the example in the readme?

Hm. True, that *should* work, as long as TorController.getSessionConfiguration() actually creates the correct configuration. Well, if it doesn't, I'm happy for any pull requests. :-)

**Comment by m4mb01t4l14n0** [comment]
This seems to end the conversation, so I'm going to close this issue
