### ISSUE TITLE
Unable to access Duckduckgo

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#201]
After the last update when trying to access Duckduckgo a "forbidden" message shows on the screen.

iPad mini 
6/25/19

**Comment by r3ckd** [comment]
It seems like this is just crying out for a better UX for Tor connection failures.  From @n8fr8 (chat): it seems like there needs to be an easy "Try Again" type button, that creates a new circuit... it could be shown whenever there is a non 200 response code from the webpage... i suppose like 403 Forbidden

**Comment by m4mb01t4l14n0** [comment]
try using DuckDuckGo over their own Onion address?
