### ISSUE TITLE
Unable to perform a search on Google

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#202]
iPad Mini

I get this screen whenever I try to search for
![604D619D-F788-487B-9656-7AD6E1C4234A (1)](https://user-images.githubusercontent.com/28932186/60291249-2c9b9200-98e0-11e9-926a-6c21b23b1261.png)
 something on Google using the browser.

**Comment by n8fr8** [comment]
This is a standard message that Google often shows if you are using Tor and trying to search. 

The issue here is that we aren't showing the captcha "pick all images of cars" step for some reason.

**Comment by wilsonjw4** [comment]
Easy fix. Go to settings on onion browser, then host settings, default settings, change content policy to open.
