### ISSUE TITLE
Open link in new tab missing

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#203]
Reported on the Apple App Store 
Version 2.2.1

After the update, the option " Open link in a new tab" is missing.

**Comment by tladesignz** [comment]
This happens, when Content-Policy is set to "strict", because also our injected JavaScript (which helps with that pop-up menu) is blocked.

However, I reworked all of this and fixed that issue during the whole OCSP-issue rewrite. So will be fixed with next release.
