### ISSUE TITLE
public ip is displayed. how to hide? 

### ISSUE THREAD

**Issue by Losason** [OnionBrowser/iOS-OnionBrowser#206]
Have visited the site https://browserleaks. com/; with the Onion Browser on the iPad. Why does webRTC Leak Test show my IP address at Public IP address? And what can I do about it?
(I find the browser somewhat pointless, if then my real IP is indicated. )
much thanks
kind regards

**Comment by tladesignz** [comment]
Duplicate of issue #117.

Yeah, we know. It's difficult. Please check open issues before creating new ones. Thanks!
