### ISSUE TITLE
Settings Workflow

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#211]
How settings are organized and how to change them.
@tladesignz 

![Settings](https://user-images.githubusercontent.com/36669955/65891424-1af7d980-e36a-11e9-82d4-bcd7d91e1d70.jpg)

**Comment by tladesignz** [comment]
Questions to @kckthx, @mtigas, @r3ckd:

1. We dropped the features "dark interface" and "toolbar at bottom" and "custom home page", that's cool. But what happened to "Mute audio with mute switch"? Should I drop that, too?

2. Cookie handling: Currently, there's the "cookie auto-sweep interval" feature. Cookies are always deleted after that number of minutes, except, if there's a per-site setting, that they shouldn't. How does the new "Allow Persistant Cookies" feature relate to that? How do you want that to work? And what's with 3rd-party cookies and the like?

3. Why are cookies and local storage seperate things? What's the benefit in deleting cookies but not local storage of a website? Why not treat that together as it is until now?

4. What happened to the "Allow 3rd party keyboards" feature? Should I drop that?

5. With the new interceptor from Psiphon, we lost the ability to set TLS versions per-site. This will be a general options feature!

6. What happened to the "Allow ignoring TLS errors" option? This was meant as a switch to provide safety from accidentally accepting websites with TLS errors. Should I ditch that? Should it always possible to override a TLS error and look at the website anyway?

**Comment by kckthx** [comment]
A few revised flows will be at the end of this to clarify my responses. @tladesignz 

1, 4 & 6 were oversights on my end — I combined the “Mute Audio” and “Allow 3rd Party Keyboards" to a section. “Allow TLS Errors” has been added to “Privacy and Security”

2. “Allow Persistent Cookies” was not supposed to be on the global settings list, my apologies for that, but it is currently available as a host setting. 
I've removed it from the "Default Security," and added it only in the "Custom Site Security." I can see now that this is a site specific setting to disable the auto-sweep. 

@mtigas can you give your input on “3rd Party Cookies” and if they should be handled separately?


3. I combined these in new view

@mtigas can you give input on if Local Storage and Cookies should be handled separately? If so, I will upload an updated view.

4. I added the “Allow TLS Errors” (oversight on my end), but the current global settings state underneath that “When enabled, a per-host option to ignore further TLS errors is shown in the TLS error dialog”  — can you elaborate on this? Is this referring to the “TLS Version” that was a per-site setting that you stated is global now? 

![Settings 2](https://user-images.githubusercontent.com/36669955/66942406-a3cf7000-f00e-11e9-9314-bb56be156203.jpg)

**Comment by tladesignz** [comment]
Oh, I see. So there weren't any implied feature requests/changes, but just oversights.
Thanks for the updated design template!

> “Allow Persistent Cookies” was not supposed to be on the global settings list, my apologies for that, but it is currently available as a host setting.
>    I've removed it from the "Default Security," and added it only in the "Custom Site Security." I can see now that this is a site specific setting to disable the auto-sweep.

Ah, don't worry. I'll rather leave it in in the "Default Security" as it currently is. If we keep the cookie handling as-is, this should also stay as-is. That way, all (new) cookies are kept and never swept.

> @mtigas can you give your input on “3rd Party Cookies” and if they should be handled separately?

That shouldn't be necessary, if we leave cookie handling as-is.

> @mtigas can you give input on if Local Storage and Cookies should be handled separately? If so, I will upload an updated view.

I recommend handling it together. Safari also does this.

>  I added the “Allow TLS Errors” (oversight on my end), but the current global settings state underneath that “When enabled, a per-host option to ignore further TLS errors is shown in the TLS error dialog”  — can you elaborate on this? Is this referring to the “TLS Version” that was a per-site setting that you stated is global now?

Nope. "TLS Version" and  "Allow TLS Errors" are different things. If you set the latter and browse to a site with a broken certificate (e.g. out of date), you are shown an option to ignore that error. If this is not set, you won't see that option.

Surf to http://badssl.com to see this feature in action.

Maybe this is overly cautious. I could remove it. Not sure anymore why I actually invented it this way. Guess, getting it past jcs for upstreaming it to Endless played a role in that decision.

**Comment by tladesignz** [comment]
@kckthx One other thing: I would need the purple shield for the security level presets as an SVG file!

**Comment by kckthx** [comment]
great! here you go, @tladesignz 
[Shields.zip](https://github.com/OnionBrowser/OnionBrowser/files/3736582/Shields.zip)

**Comment by tladesignz** [comment]
@kckthx Sorry, the use of a singular was too subtle, obviously. Please just a single shield, without the numbers. Tried to remove them, but the whole thing is a single path.

**Comment by kckthx** [comment]
Ok. 
[Shield.svg.zip](https://github.com/OnionBrowser/OnionBrowser/files/3739357/Shield.svg.zip)
