### ISSUE TITLE
Facebook onion site

### ISSUE THREAD

**Issue by businessasusual22** [OnionBrowser/iOS-OnionBrowser#215]
I'm trying to log into m.facebookcorewwwi.onion, and the page just refreshes without giving me access to my account. Facebook detects a login attempt, and I have confirmed with them that it was was a legitimate login, but the onion browser continues not to go past the login page. Is there a setting I need to change to allow the login process to complete?

**Comment by tladesignz** [comment]
When I lift the "Content Policy" to "open" for that site, it works for me. Also needed to do an e-mail security code check.

Please close, if that helped you!

**Comment by businessasusual22** [comment]
I think that did it. Thanks.
