### ISSUE TITLE
Browser Icons

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#216]
@tladesignz let me know if you want these anywhere else!
[Browser Icons.zip](https://github.com/OnionBrowser/OnionBrowser/files/3785714/Browser.Icons.zip)

**Comment by tladesignz** [comment]
Thanks a lot!

I have only 2 complaints :-):
- An "insecure" icon is missing.
- The "refresh" icon is cut off on right and bottom, when I convert to PDF. Guess, there's something broken in the SVG background or image size compared to the content. Didn't have time to investigate, yet.

Anything else looks good.

For the future: You don't need to do selected/unselected icons. That will be done programmatically. In fact, these images will only ever be used as templates (converted to a bitmask) and then colored. So you can as well do them in just black. Doesn't really make a difference here, though, so don't worry about it for now.

**Comment by kckthx** [comment]
oh ok! Thanks for that info. 
Here is a new refresh, insecure, and a new "secure" icon also -- it looked a little squished before. 


[refresh-in-secure.zip](https://github.com/OnionBrowser/OnionBrowser/files/3789236/refresh-in-secure.zip)
