### ISSUE TITLE
Media Files 

### ISSUE THREAD

**Issue by swefib101** [OnionBrowser/iOS-OnionBrowser#217]
Hi! i wonder if Media Files are blocked by default by onion browser? For privacy

**Comment by tladesignz** [comment]
Not, not really. "Media files" in that context is a little difficult. Actually, images are media files, too. And I'm pretty sure, nobody would be happy if we stopped images from loading.

What *is* blocked by default is:
- WebRTC (at least, if an attacking webpage isn't trying too hard)
- XHR, WebSocket and Video
- mixed encrypted and unencrypted content
