### ISSUE TITLE
Unable to close tabs

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#218]
iPad Mini
iOS 13.2.3

I'm able to navigate between many tabs open at the same time, but when I touch the "X" on the left top of a tab, the screen maximizes instead of closing the tab.

**Comment by tladesignz** [comment]
- There's currently no X, but 3 dots (...) in the left corner. That's a bug and is fixed in the current dev branch.
- I can close it, but one needs to hit very exactly. Should be better with the redesign.
