### ISSUE TITLE
Edit and re-order tabs feature is not working

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#219]
iPad mini 
iOS 12.4.1
On the Bookmarks screen the features "Tap to edit" and "Hold to re-order" are not working.
![83593](https://user-images.githubusercontent.com/28932186/69923166-3e252f00-1468-11ea-877a-a98eb8417ba3.jpg)

**Comment by tladesignz** [comment]
This is the old UI. Was completely redesigned and reimplemented. I hope, it gets released soon. (see #210)
