### ISSUE TITLE
Lost tabs when iPad locks

### ISSUE THREAD

**Issue by ingfabby** [OnionBrowser/iOS-OnionBrowser#220]
iPad Mini 
iOD 12.4.1

If the device is locked while using the Onion Browser all the tabs are lost when I unlock it.
I'm not sure if we actually want this to happen.

**Comment by tladesignz** [comment]
That's actually a feature which' setting you can change. Look for "Tab Security"!

**Comment by ingfabby** [comment]
It makes sense.  Thanks for letting me know Benjamin.
