### ISSUE TITLE
Swiping down on the connecting screen causes the app to stop responding

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#221]
1. Open onion browser on an iPad.
2. When the connecting window appears swipe down on it to dismiss it, the app no longer responds after that action is taken.
iOS 13.3 developer beta 3
Onion browser  2.30
Video showing the bug occur. https://streamable.com/omv0k

**Comment by tladesignz** [comment]
Hey, thanks for pointing that out!
I fixed it: https://github.com/guardianproject/poe/commit/d37c2eba8a35c0663f6d20004a3136268ae11622

Will be in the next release.
