### ISSUE TITLE
Shield icon behavior (in navbar)

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#222]
#222: shield icon 
#223: onion icon  
prev settings work is in #211  
onboarding work in #212

**Comment by kckthx** [comment]
@tladesignz @mtigas 
Here is a flow of the shield icon at work. 
I'm aware some copy may still need to be fine tuned, but this is how it works. 

![OB-Shield Icon](https://user-images.githubusercontent.com/36669955/70096400-9edd7480-15ec-11ea-982b-4840ff430821.jpg)

**Comment by tladesignz** [comment]
@kckthx can you provide the new custom shield icon? As always: SVG, please!

**Comment by kckthx** [comment]
[Custom-shield.svg.zip](https://github.com/OnionBrowser/OnionBrowser/files/3969290/Custom-shield.svg.zip)
@tladesignz here you are

**Comment by tladesignz** [comment]
Implemented besides the content behind "Learn More". (Button hidden for now.)

Please, @m4mb01t4l14n0, @kckthx, @mtigas, provide that in a fresh issue, when you're ready.

I suggest implementing a help text like that as a web page. Can be on your server or inside the app, like I did with "about:onion-browser". (Yes, I gave the credits page a pseudo-URL!)
