### ISSUE TITLE
Empty Browser Home Page

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#228]
![Empty Browser Home](https://user-images.githubusercontent.com/36669955/71004244-5ec7c880-20a7-11ea-88d1-a895401fdb04.png)
Bookmarks would live here, if no bookmarks are set, default to onion sites.
@tladesignz

**Comment by tladesignz** [comment]
@kckthx, @mtigas, @m4mb01t4l14n0, please provide all links, as I don't have them all currently! And with *all* I also mean the one's at the bottom!

**Comment by tladesignz** [comment]
@kckthx, please provide icons of bottom links as SVG!

**Comment by kckthx** [comment]
@tladesignz 

**Learn More** onionbrowser.com
**Donate** donate page  -- it's currently https://onionbrowser.com/#support-project
**Newsletter** https://newsletter.torproject.org/

**Comment by tladesignz** [comment]
Thanks @kckthx!

I also need the parameters of the color gradient.
And don‘t forget the icons!

**Comment by kckthx** [comment]
Not sure about parameters of gradient, but the radial gradient colors are 
C32AFF
51036B
490161

[landingpageicons.zip](https://github.com/OnionBrowser/OnionBrowser/files/3979115/landingpageicons.zip)

**Comment by tladesignz** [comment]
@kckthx Do you want to provide a default icon? There's not always going to be an icon available for a number of reasons.

**Comment by tladesignz** [comment]
@kckthx 

> Not sure about parameters of gradient, but the radial gradient colors are
> C32AFF
> 51036B
> 490161

Not sure how to apply them. I see it's a circle gradient from the top left. Where should I use the color stops? I played around with these colors but didn't have a matching result.

I need something like this:

https://cssgradient.io

(Don't worry about the circle's center position for now.)

Missing icons:
- green arrow
- default favicon

**Comment by tladesignz** [comment]
Aaaaah, and did you ever think about how this will look resp. should look on an iPad, @kckthx?

**Comment by kckthx** [comment]
@tladesignz 
background: rgb(195,42,255);
background: radial-gradient(circle, rgba(195,42,255,1) 0%, rgba(81,3,107,1) 57%, rgba(73,1,97,1) 100%);


yes, top left. 

[landingpage-2.zip](https://github.com/OnionBrowser/OnionBrowser/files/3985038/landingpage-2.zip)
![onionbrowseriPad](https://user-images.githubusercontent.com/36669955/71198964-8e6b0200-225a-11ea-9cb4-dc9dec15e989.png)
