### ISSUE TITLE
Purple too dark in dark mode

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#234]
#3F2B4F is too dark in dark mode.

Please advise what color to use in dark mode instead. Should it be #A577BB or some other?

![Simulator Screen Shot - iOS 13 3 @ iPad Air 2 - 2020-01-09 at 13 31 24](https://user-images.githubusercontent.com/117089/72068308-091cbf80-32e5-11ea-8c01-fb954ed9c129.png)

**Comment by tladesignz** [comment]
![Simulator Screen Shot - iOS 13 3 @ iPad Air 2 - 2020-01-09 at 13 31 24](https://user-images.githubusercontent.com/117089/72068277-f4d8c280-32e4-11ea-84bf-3134f6a8f41d.png)

**Comment by kckthx** [comment]
Hey @tladesignz 
Let's do #C2A0CA. 
it's super close, but passes the accessibility contrast test on https://webaim.org/resources/contrastchecker/

**Comment by tladesignz** [comment]
Thanks, @kckthx!
