### ISSUE TITLE
Overlay States

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#236]
Hey @tladesignz 
Currently, tapping "customize" from the shield menu on ipad produces another flyover menu on top of it. 
![IMG_0008](https://user-images.githubusercontent.com/36669955/72185420-5e75d100-33b8-11ea-950a-39a85f5dd0b1.png)

Can we get this second state to appear as an overlay instead, so it takes up more screen space. This would also be how "Settings" works.

![IMG_0324](https://user-images.githubusercontent.com/36669955/72185654-f2e03380-33b8-11ea-9d8b-1a0a969942f0.PNG)
![IMG_0324](https://user-images.githubusercontent.com/36669955/72185655-f4a9f700-33b8-11ea-83b2-b80af5a18149.PNG)

**Comment by tladesignz** [comment]
Two times the same screenshot?

**Comment by kckthx** [comment]
![IMG_0323](https://user-images.githubusercontent.com/36669955/72189447-718d9e80-33c2-11ea-807e-678961fab38b.PNG)
sorry-- @tladesignz

**Comment by tladesignz** [comment]
Ah, ok. Yes, makes sense, will change.
