### ISSUE TITLE
Different Default Onion Screems

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#237]
@tladesignz 
On my iphone xr, I have the same 6 icons for default onion sites. On @m4mb01t4l14n0 ipad, it has different sites. Does this have to do with location?
![IMG_50AD060F998D-1](https://user-images.githubusercontent.com/36669955/72186072-fd4efd00-33b9-11ea-8963-a3bf8db057a7.jpg)
![ecccKfwUJmqmCRZbPzZiyefT](https://user-images.githubusercontent.com/36669955/72186073-fe802a00-33b9-11ea-860d-a23f7f47761e.png)

**Comment by tladesignz** [comment]
Yours is a fresh install, therefore a slightly updated bookmark list. I don't touch existing bookmarks.

**Comment by m4mb01t4l14n0** [comment]
I am running v 2.4.0 (build with last 4 digits 3906).  I just installed this 48 hours before the discussion with @kckthx.  It's the release TestFlight gave to me, no further new releases.  NOTE: I did update my iPad to iOS 13.3 (iPadOS) prior to loading this new build.

**Comment by tladesignz** [comment]
@m4mb01t4l14n0: If you ran an older version on that device, even on an older iOS version, the old bookmarks still exist and won't be touched.

You can go "edit" each single bookmark, then the favicon will be loaded and you start page will sport these.

Or you can erase Onion Browser and re-install. Then, you get an updated fresh bookmark list installed.
