### ISSUE TITLE
Crash when tapping the onion button while a website is loading

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#238]
1. Open the app and tap torproject’s onion link.
2. Then immediately tap the onion button on the toolbar and the app should crash every time. If it does not crash on the first time tap the onion again while the website is loading.
Onion Browser 2.4.0
Video showing the bug occur.
https://streamable.com/uogod
@tladesignz

**Comment by lanierband** [comment]
I validated this with other websites.  The behavior I get on iPad is that (a) progress on loading freezes (unrecoverable), then (b) I tap HOME and then when I try to restart the app, it reports the crash.

**Comment by tladesignz** [comment]
As per crash reports via AppStoreConnect, it seems, Tor.framework crashes when trying to make sense of the circuit info strings.
Did a shotgun debugging:

https://github.com/iCepa/Tor.framework/commit/c4c2aacac6fb11bbd6dee5576c5835439e618d85

Hope that will solve the issue.

Thanks a lot for reporting!
