### ISSUE TITLE
Security Levels -- Onboarding

### ISSUE THREAD

**Issue by kckthx** [OnionBrowser/iOS-OnionBrowser#241]
@mtigas @tladesignz @m4mb01t4l14n0 

I made a new Google Doc, so everything is clear and fresh. The copy in this doc is the most recent that I have written for the Secrity Levels views.

Please look through and make any edits needed so we can get the onboarding completed and pushed! Thank you!

https://docs.google.com/document/d/1I9z_FtAwxtUJ2KIKxTWr2YbUIgyFtDlZjKDiQVfv-80/edit?usp=sharing

**Comment by tladesignz** [comment]
Sorry, can't read, yet. Sent a request.

@m4mb01t4l14n0, @mtigas: Can you either
- approve the text as-is
- improve and then approve
- tell me to forget about it

So we can get the last thing in the new UI out of the way?

**Comment by tladesignz** [comment]
Ok, so @mtigas, I defaulted to text-accepted-without-changes and finally implemented this, so we can get it out of the way!

**Comment by tladesignz** [comment]
@kckthx Please provide template or style guide if you want this page better looking than this:

![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-02-03 at 15 27 55](https://user-images.githubusercontent.com/117089/73661145-de324b00-4699-11ea-91a5-93a91316302b.png)

**Comment by kckthx** [comment]
https://github.com/OnionBrowser/onionbrowser.github.io/issues/7
This is the style guide I made for the website

The colors and fonts are the same. albeit sizes will be dynamic.
@tladesignz

**Comment by kckthx** [comment]
![OB_DEL-ON-securitysettings](https://user-images.githubusercontent.com/36669955/73662860-29306c00-4662-11ea-844f-d6d25c0baae3.png)

**Comment by tladesignz** [comment]
Thank you, @kckthx!
