### ISSUE TITLE
Onionbrowser.com giving me a blank page and not loading

### ISSUE THREAD

**Issue by MikaelaArsenault** [OnionBrowser/iOS-OnionBrowser#246]
When I try to open onionbrowser.com in the Onion Browser app, it give me nothing but a blank page.

![F66F2836-D0BB-4768-99B7-70376875FB27](https://user-images.githubusercontent.com/59139947/74605202-e45df980-5093-11ea-94d9-7c81c2602ea0.png)

**Comment by MikaelaArsenault** [comment]
And the two Onion Browser links are not loading for me either.

![7C771981-F6E5-44EE-B198-04F5BFEAD79B](https://user-images.githubusercontent.com/59139947/74605328-32bfc800-5095-11ea-9390-67c967afc80b.png)

**Comment by tladesignz** [comment]
Thanks for reminding us! I don't know why, but the performance via Tor is horrible and it seems to blow up the UIWebView renderer as the pages cuts-off for me.

However, there's an ongoing effort to replace this page *completely* as you can see here:
https://github.com/OnionBrowser/onionbrowser.github.io/issues/2

Therefore, I'll close this issue now, but not before reminding @m4mb01t4l14n0, @kckthx and @mtigas to please get this website online ASAP! :-)

**Comment by m4mb01t4l14n0** [comment]
Thanks for the prompt here, @tladesignz. @MikaelaArsenault we've got some updates in the works to be deployed very soon.  Thanks for you patience.
