### ISSUE TITLE
Suggestion to add DuckDuckGo HTML or Lite to default search engines

### ISSUE THREAD

**Issue by nitrohorse** [OnionBrowser/iOS-OnionBrowser#247]
Hi! I really appreciate the work you all are doing with Onion Browser. I noticed that while on the "Secure" setting with JavaScript disabled, when I do a search on https://3g2upl4pq6kufc4m.onion, results unsurprisingly don't appear because the main DDG site relies on JS. I expect to get redirected to the HTML version of DDG but am not (could just be me?).

So I'm proposing adding these other versions of DDG to the search engine list for just a quality of life improvement for users so we could set either as a default for our searches:
- https://3g2upl4pq6kufc4m.onion/html (https://duckduckgo.com/html)
- https://3g2upl4pq6kufc4m.onion/lite (https://duckduckgo.com/lite)

**Comment by tladesignz** [comment]
Love it. Done!
