### ISSUE TITLE
Failure to open Landing Page

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#248]
![IMG_0011](https://user-images.githubusercontent.com/34868071/75782106-643ec180-5d2c-11ea-87bb-c3f0ade902c8.PNG)

I get this screen on my iPad on initial startup (first use), after tapping "start browsing".  Tapping OK brings me to a black screen (empty browser pane) from which I can enter URLs and pages do load. Once a page is acquired, the back button yields the purple "Onion Browser" landing page (which would be been expected after "start browsing".)  I have only iPad Mini 4 to test on.  iPadOS 13.3.1

**Comment by tladesignz** [comment]
Sounds like a race condition. The file is created on-the-fly. Everything is packed in one file (incl. the favicon images). That was the easiest route to not create security holes. It is recreated multiple times on first startup - every time a favicon is loaded.

This sounds, like you just found the moment, where the file was being recreated, but not fully done, yet.
I'll look into it.

**Comment by tladesignz** [comment]
Problem was, file got deleted to trigger re-rendering. Bad idea, because re-rendering and reading happens in different processes. Now just marked for re-rendering, no deletion anymore.
