### ISSUE TITLE
Onion Browser can't save anything. 

### ISSUE THREAD

**Issue by hokaneko** [OnionBrowser/iOS-OnionBrowser#25]
I feel like being in a dark net museum. You look, you don't touch !
Why is Onion browser the only browser in the apple store -- and the only browser I've ever met on any OS -- that allow you to browse but not to download anything? It's like walking in a super market and leaving empty handed. The Dark Net is a huge part of the whole internet and it's a real shame to discover interesting websites (everybody talk about guns, drugs and girls but illegal websites are a ridiculous part of what you can access there) without having the possibility to download any kind of file. The iOs menus are blocked. And except the "Copy" button, nothing works...
Really this app rocks but this limitation sucks. Everytime I need to download I use Vidalia back on the PC. Apple forbid you to implement a download button ? is it too complex to program ? More than the encryption and privacy part of your project ?! I'm looking forward for this cos' personnaly after 1.3.3 and 1.3.4 I don't think I'll buy any newer version that enable me to go fishing in deep sea without going home with some fish.
Thanks for the hard work. Good luck and please keep us informed wether it's an apple restriction or an improvement yet to come soon.

**Comment by ghost** [comment]
It needs a “share” button like all other browsers. Right now one cannot export/share e.g. sci-hub articles to a pdf viewer.
