### ISSUE TITLE
On-boarding security-level selection bug

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#252]
I've been reviewing "language" (for security) on other Tor browser platforms. I actually LIKE our current mechanism for communicating security settings BUT I seem to have a bug. 

From a fresh install, I work through the initial screens (no bridges) and arrive at page to set default security level. At base of page there's text "learn more". BUT I can not tap that text UNTIL I tap one of the security level settings. After tapping, say, MODERATE, the START BROWSING button turns green AND the "learn more" text becomes tappable. I'd WANT to see that text to help me make a selection. 

There is also a 2nd-order bug, here, too.  If (after selecting a security level) you tap "learn more", you are taken to a new browser tab that displays the full text of what each security level means.  This is GREAT (yes, I'll be working on actual words!).  But, the tab you WERE looking at (the security level selector page) has now transformed into the browser landing page.  MEANING that after you read the "learn more" text, you no longer have the option to set your level.

**Comment by m4mb01t4l14n0** [comment]
![IMG_0012](https://user-images.githubusercontent.com/34868071/76333581-3d523380-62c8-11ea-9f44-ea13ec063e30.PNG)
![IMG_0013](https://user-images.githubusercontent.com/34868071/76333585-3deaca00-62c8-11ea-90c7-98a66103f94c.PNG)
![IMG_0014](https://user-images.githubusercontent.com/34868071/76333587-3e836080-62c8-11ea-9fac-652e90ff738b.PNG)
![IMG_0015](https://user-images.githubusercontent.com/34868071/76333592-3f1bf700-62c8-11ea-8792-2b5bcdc49ec6.PNG)

**Comment by tladesignz** [comment]
Ok, ok, admitted: That was a stupid idea. Now you have an extra view controller popping up, which shows the page.
Note: It uses `WKWebView`... ;-)
