### ISSUE TITLE
NextCloud Bookmarks - can't connect to sync

### ISSUE THREAD

**Issue by m4mb01t4l14n0** [OnionBrowser/iOS-OnionBrowser#255]
I logged into desktop/web NextCloud (changed password!) and created some bookmarks.  I then fired up OB and made several attempts to sync.  I verified user/pass and URL several times.  Failure, screen attached.  I had security level set to 2 though I don't think that matters.    iPad Mini Retina running 13.3.1.

![IMG_0016](https://user-images.githubusercontent.com/34868071/77583056-ce273280-6eb6-11ea-9ae9-d4c1ca24bc04.PNG)

**Comment by tladesignz** [comment]
Only enter the host, not a complete URL! Remove the scheme!

**Comment by m4mb01t4l14n0** [comment]
operator error!
