### ISSUE TITLE
Opens in wrong language, can't change 

### ISSUE THREAD

**Issue by Johnoaa** [OnionBrowser/iOS-OnionBrowser#258]
Upon first launch, onion browser interface has another language than English. It's the language of the country I am currently in, which unfortunately does not use Latin letters. To change the language seems impossible.

My phone's language and region settings are not of this country.

**Comment by tladesignz** [comment]
That's interesting. There's no special language handling done, really. Maybe a library used messes things up.

I'd like to reproduce this but for that I need to know, which languages we're talking about.
Can you contact me via PM, if you don't want to state it publicly?
You can find contact details here: https://benjaminerhart.com/ueber-mich/

Besides that, please check your "preferred language order" in:
Settings -> General -> Language & Region

**Comment by Johnoaa** [comment]
Thank you for your quick response. I followed your advice to check preferred language order and to my severe embarrassement found that this language was ordered above English (due to a recent ambitions to learn it). Changing the order solved the issue. 

Thank you again and my apologies, I should have been able to sort this out by myself.
