### ISSUE TITLE
'OnionBrowser-Swift.h' file not found

### ISSUE THREAD

**Issue by jozxing** [OnionBrowser/iOS-OnionBrowser#265]
file：URLBlockerRuleController.m
#import "OnionBrowser-Swift.h"   error：'OnionBrowser-Swift.h' file not found

Xcode Version 11.5
ios：13.5

**Comment by tladesignz** [comment]
That‘s an auto-generated file which is never really visible, only for the build products.

If this error happens, you messed up the project config. Please follow the instructions in BUILD.md.

If you don’t understand all the concepts and run into problems, please google them. This is not a board for learning iOS development. Thanks!
