### ISSUE TITLE
Duduckgo search are broke from the iOS app

### ISSUE THREAD

**Issue by kristianpaul** [OnionBrowser/iOS-OnionBrowser#267]
Not sure how to reproduce othe way than opening the Onion App in iOS, from home click on ddg link, search and get this

![7ycj8hrpxqx41](https://user-images.githubusercontent.com/326463/83594818-d12d4780-a525-11ea-8870-907a144503e2.jpg)

**Comment by tladesignz** [comment]
1. Judging from the color of the security level shield, it seems you're not running the latest version. Please update!

2. Since you use security level 3, maybe you want to try [DuckDuckGo HTML](https://duckduckgo.com/html/) or [DuckDuckGo Lite](https://duckduckgo.com/lite). (See also Settings -> Search Engine)

3. Besides that - that shouldn't happen, but you could always run into an adversarial Tor node which tries something bad. Try switching circuits!

**Comment by kristianpaul** [comment]
@tladesignz thats the latest version i could get for iOS

**Comment by tladesignz** [comment]
That seems strange. Can you please tell me the iOS version you're running, the device type and the Onion Browser version? You can find the latter in the settings scene at the very bottom. (Press the gear icon at the bottom right to enter the settings scene.)

How did you get the app? From Apple's app store? Can you post the link to that here?

(I'm wondering if there's someone ripping our work and maybe tries to hijack it...)

**Comment by kristianpaul** [comment]
2.6.0 in both iphone 7 plus and ipad pro. https://apps.apple.com/co/app/onion-browser/id519296448

**Comment by tladesignz** [comment]
Hmmm. Strange.

So you're browsing out of Colombia?

Can you reproduce this, tap the onion icon to show the circuit and do a screenshot with that?

I'm inclined to point my finger at an exit node. Maybe it's one DDG doesn't like. (Often, shady persons try to do tricks esp. with search engines. E.g. build a search result ranking for certain keywords. They burn a lot of IP addresses with these endeavors and sometimes use Tor to gain more.)

Other questions: 
- Are you trying to run through a VPN? That might also play a role in some edge cases.
- Can you access DDG via your normal Internet connection?

**Comment by kristianpaul** [comment]
![image](https://user-images.githubusercontent.com/326463/84603142-c5108680-ae51-11ea-97aa-57c18d46c595.jpeg)![image](https://user-images.githubusercontent.com/326463/84603146-cb9efe00-ae51-11ea-839c-d973243ef3d9.jpeg)

**Comment by kristianpaul** [comment]
- No vpn
- I can access DDG via normal internet connection and also by tor from systems that run Linux

**Comment by tladesignz** [comment]
Oh man. Sorry, I put you through all this.

Took a while until I understood how to reproduce it and finally found a bugfix.

But this is really big. I think a lot of people have issues in the "gold" level, and this might be a fix which helps a lot with that.

Unfortunately, you have to wait until the next Onion Browser release in a few weeks. (Should be 2.6.1)

Thank you so much for your help!

**Comment by kristianpaul** [comment]
![532B47F1-A28A-461B-B4E4-1007BC8FE310](https://user-images.githubusercontent.com/326463/90303138-2d3f1100-de71-11ea-8468-30942ed87205.png)

![58B4F7CF-8EA0-4B1A-AAEB-78641C9AE9B7](https://user-images.githubusercontent.com/326463/90303178-91fa6b80-de71-11ea-90df-60ce99090fae.png)
![9D98310D-5574-4564-80A5-EC2E86F4FFF4](https://user-images.githubusercontent.com/326463/90303180-93c42f00-de71-11ea-9796-bb6fbe7b1c7f.png)
![98BD10EE-EDBE-4899-BA1D-E5E89ECAC82F](https://user-images.githubusercontent.com/326463/90303182-945cc580-de71-11ea-8c61-383027edcfcf.png)

**Comment by tladesignz** [comment]
Please try setting the default search engine to DDG HTML or Lite in Settings -> Search Engine!
JavaScript is disabled in gold security level, so normal DDG can't work properly there.

**Comment by tladesignz** [comment]
And just search with the search bar, then it works. Sorry, no idea atm., why this is still a problem.

**Comment by kristianpaul** [comment]
Looks like it works when selecting silver mode
