### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by kapil0408** [OnionBrowser/iOS-OnionBrowser#268]
I have downloaded the project and install the pods. when I am running it. it is showing error.

I have done with pod deintegrate and again pod install
also tried option for Keychain to lock and unlock as described on StackoverFlow.
but not succeed.

Any one please help me. how to fix it.

Please see the attached screen shot.
![Screenshot 2020-06-05 at 1 31 11 PM](https://user-images.githubusercontent.com/7668570/83852160-00fc6b00-a731-11ea-9bef-360aa2633f39.png)

**Comment by tladesignz** [comment]
Did you follow the instructions in [BUILD.md](/OnionBrowser/OnionBrowser/blob/2.X/BUILD.md)?

**Comment by kapil0408** [comment]
Thanks for this. Resolved
