### ISSUE TITLE
Cannot "Lock App with Touch ID/Face ID or Device Passcode" on iPad Pro (12.9-inch) (2020)

### ISSUE THREAD

**Issue by MissRarity** [OnionBrowser/iOS-OnionBrowser#269]
In the application settings for Onion Browser on iPad Pro (12.9-inch) (2020), it is not possible to toggle the option for "Lock App with touch ID/Face ID or Device Passcode" as once enabled, it immediately disables itself and the entire line for the option in the interface becomes greyed out and inaccessible.

Please implement change or messages to user for fix/workaround.

**Comment by tladesignz** [comment]
Hm, that's interesting. This should only happen, if there's no secure enclave available.
Are you running it on a real device? Or a simulator? If it's a real device, is it jailbroken?

**Comment by MissRarity** [comment]
> Hm, that's interesting. This should only happen, if there's no secure enclave available.
> Are you running it on a real device? Or a simulator? If it's a real device, is it jailbroken?

It is an indeed real, nonjailbroken, directly-from-Apple, non-emulated iPad Pro (12.9-inch) (2020) running 13.5.1.

Interestingly, upon further investigation, it seems to work when Face ID is configured. Prior, I was using the device with a password only. So it seems that the program does not like it when that setting is toggled without Face ID set? Sample size of 1, but that's all the new information I got. Perhaps you can replicate it on your end with configuring Onion Browser on a new iPad Pro without Face ID set up?

**Comment by tladesignz** [comment]
Thanks a lot for digging this up! I checked this with my iPhone XS and it indeed didn't work without enrolled FaceID. With the fix, it now works, enrolled or not. Will be contained in the next release in a few weeks!
