### ISSUE TITLE
[Feature Request] Systemwide VPN

### ISSUE THREAD

**Issue by Man-with-Arrow** [OnionBrowser/iOS-OnionBrowser#277]
As this is (AFAIK) the only official TOR implementation for iOS, and there is no way to route all traffic through TOR on iOS (à la Orbot on Android) - how complex would it be to add a systemwide VPN option?

**Comment by tladesignz** [comment]
Complex, unfortunately.

https://github.com/iCepa
https://github.com/tladesignz/iCepa
https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

We're working on it with the Tor Project, but the memory constraints are very difficult to reach for what needs to be done.

**Comment by tladesignz** [comment]
Closing this, as we track this problem in other issues, already.
