### ISSUE TITLE
Improve MOAT requests

### ISSUE THREAD

**Issue by n8fr8** [OnionBrowser/iOS-OnionBrowser#278]
Could we use libcurl to do the direct HTTPS request to the moat server with the modified host header?

HTTP custom header example:
https://curl.haxx.se/libcurl/c/httpcustomheader.html

libcurl build for iOS:
https://github.com/gcesarmza/curl-android-ios

**Comment by tladesignz** [comment]
There is a CocoaPods library, which bundles libcurl and encapsulates it with a nice Objective-C API:

https://cocoapods.org/pods/YMHTTP

It looks like it can do domain fronting, but I do get 400 errros, when I try it the very simple way.

Need to check back with our Tor contact via mail what to do here.

**Comment by tladesignz** [comment]
With the help of the Tor folks, I finally nailed it: Onion Browser will now do requests to the MOAT service via its dedicated Meek proxy.
