### ISSUE TITLE
When pasting onion sites into address bar it just does a search

### ISSUE THREAD

**Issue by Deadsoonx** [OnionBrowser/iOS-OnionBrowser#282]
Instead of going to onion site it just searches in DuckDuckGo. Not sure why.

**Comment by tladesignz** [comment]
Similar issue: #271 
And again: Can't reproduce. I can paste a .onion domain just fine, I can paste a full fledged .onion URL just fine.

@Deadsoonx, can you please specify all the steps and settings that are necessary? Screenshots are welcome, too!

**Comment by tladesignz** [comment]
Closing this, as there's no response.
