### ISSUE TITLE
[Feature request] Support for onion-location header

### ISSUE THREAD

**Issue by neilzone** [OnionBrowser/iOS-OnionBrowser#284]
In Tor Browser, if you browse to the clear web URL of a site which sends an onion-location header, you are redirected automatically to the .onion service specified in that header.

For example, if, using Tor Browser, you were to visit https://decoded.legal, the server will send back an onion-location header of "dlegal66uj5u2dvcbrev7vv6fjtwnd4moqu7j6jnd42rmbypv3coigyd.onion", and the browser will automatically connect to the onion service.

Testing this on Onion Browser, I don't think that it is currently supported? If not, perhaps this could be added?

**Comment by tladesignz** [comment]
D'oh! Thanks for that hint!
If we had known about that, I'd had at least implemented this when trying to do #148.

https://community.torproject.org/onion-services/advanced/onion-location/

Unfortunately, we ran out of the last funding round, but I'll try to get time for it!

**Comment by neilzone** [comment]
Well, at least it's not just me getting something wrong :)

For what it's worth — and I think that this is consistent with #148 — I don't think the alt-srv header we send is acted on either.

**Comment by tladesignz** [comment]
@n8fr8 This is easy to do, can we find some money/time so I can do it?
