### ISSUE TITLE
Apple declined app because of link to donations outside App Store

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#289]
This is so fucking ridiculous!

> 3. 1.1 Business: Payments - In-App Purchase
> Guideline 3.1.1 - Business - Payments - In-App Purchase
> 
> 
> We noticed that your app allows users to contribute donations to the development of your app with a mechanism other than the in-app purchase API, which is not appropriate for the App Store.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to use the in-app purchase API to pay for this type of transaction. Please note that even though tipping another individual is optional, the tip is connected to or associated with the receipt of digital content or services in your app and must be purchased through in-app purchase in accordance with guideline 3.1.1 of the App Store Review Guidelines.
> 
> 
> 
> Please see attached screenshots for details.
<img width="834" alt="Screenshot-0908-175359" src="https://user-images.githubusercontent.com/117089/92566270-407cab00-f27c-11ea-9838-1df1d50824ce.png">
<img width="834" alt="Screenshot-0908-175346" src="https://user-images.githubusercontent.com/117089/92566291-48d4e600-f27c-11ea-8d3e-5bb9ce243469.png">

**Comment by tladesignz** [comment]
@mtigas, @n8fr8, I guess I will resolve this by linking the "Donate to Onion Browser" to the in-app purchase scene.

Any additional thoughts on this?

**Comment by mtigas** [comment]
Yeah I think removing the link in-app is probably the way to go.

My guess on this is that they've made their app review teams crack down non-IAP (in app purchase) revenue since the [Epic Games thing that's been going on](https://www.macrumors.com/guide/epic-games-vs-apple/).

**Comment by tladesignz** [comment]
Not sure if that will help their case, if they additionally try to squeeze NGOs. Grrr.
