### ISSUE TITLE
Dread Captcha Broken

### ISSUE THREAD

**Issue by VectorABC** [OnionBrowser/iOS-OnionBrowser#295]
Other iPhone tor browsers show all the icon circles. This browser only shows two of them. But most of those other browsers such as OrNET crash when you get through the two layer captcha. 

http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion

![8DF2E994-D980-4CEC-8E63-0223FDDF440B](https://user-images.githubusercontent.com/49097685/94878796-73a1fc80-042c-11eb-8698-5934d5788ef0.jpeg)

**Comment by tladesignz** [comment]
Ok, I finally got round to taking a deeper look into this website.

The problem is just that it's CSS is broken in a way WebKit doesn't like:

```css
.captchav2 > .inputWrap > div.c2 {
        top: 0;
        left: 60;
    }
```

But it should probably be `left: 60px` or some other sensible unit.

Sorry, can't help you there. You will need to talk to the website operators.
