### ISSUE TITLE
Will not connect to TOR at loading screen

### ISSUE THREAD

**Issue by notrackingme** [OnionBrowser/iOS-OnionBrowser#298]
Hi. Upon launching the app it cycles through the loading screen trying to connect then says unable. I have tried various VPNs, LTE, and WiFi to no avail. All other internet traffic works. Uninstalled and reinstalled app. Running iOS 14. Any ideas?  Thank you.

**Comment by tladesignz** [comment]
It might just be that your country blocks Tor. Did you try following the advise which pops up after a while that you should try using a bridge? Try the button "Request Bridges from torproject.org". That should give you the best results, if it works. If that doesn't work, try using the built-in obfs4 proxies. If that doesn't work, try Snowflake. If that doesn't work, try meek-azure!

All reachable via the gear icon in the top right!

**Comment by notrackingme** [comment]
I'm in the US and it was working until today. Thank you for the idea though.

**Comment by tladesignz** [comment]
Did you mess with the advanced Tor settings? You can remove these in the same bridge scene using the gear icon.

**Comment by notrackingme** [comment]
Hi. No. I hadn't made any changes. Trying to troubleshoot I even removed and reinstalled the app and it didn't work. 

Not sure if it's repeated or not but prior to this I had noticed some odd bugs. One that stood out was that I couldn't tap the shield to change the security level. 

Oddly I just tried logging on again and it let me. It had been down for about a day though.
