### ISSUE TITLE
Last translation update for UIWebView version

### ISSUE THREAD

**Issue by tladesignz** [OnionBrowser/iOS-OnionBrowser#301]

**Comment by Mr-zombie8145** [comment]
does anyone work on updating UIWebView to WKWebView?

**Comment by tladesignz** [comment]
> does anyone work on updating UIWebView to WKWebView?

Yes, a lot of people. Of course you can give it a shot yourself.
Hint: The problem is *not* to replace `UIWebView` with `WKWebView` calls. (In fact, I already did that experimentally in a [branch](https://github.com/OnionBrowser/OnionBrowser/tree/WKWebView).)

The actual problem is described here: #47

Please try not to hijack issues about different topics the next time! Thanks!
