### ISSUE TITLE
A new browser would like to find and connect to devices on your local network

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#305]
While browsing I got a pop-up saying “ Onionbrowser would like to find and connect to devices on your local network” is this intended? Users may see this as a privacy vulnerability.

![4B9A1BD5-BE1A-4443-B4EC-7B98A33E2ED6](https://user-images.githubusercontent.com/10781882/100379049-1e680e80-2fc9-11eb-81c4-83684b235589.png)
Onion browser 2.7.1

**Comment by tladesignz** [comment]
Well, it's a browser. Do you know of any browser which can't connect to devices on your local network? 

Technically, it's correct. It for sure sounds dangerous to the untrained ear, I give you that.

Do you have any idea how to avoid it?

**Comment by DanGould** [comment]
It seems v2.7.2 resolves this issue. The permission is no longer prompted or used as far as I can tell in device privacy settings.

[this apple forums thread](https://developer.apple.com/forums/thread/663874) lists what triggers this permission but I haven't yet found the exact change that resolved this issue exactly. Upgrading to Tor.framework v404.6.2 alone does not solve this issue in my app. Does anyone know what changed to stop this prompt?

**Comment by tladesignz** [comment]
I didn't change anything specifically. It was probably just the recompile with the latest Xcode.
