### ISSUE TITLE
Orbot and Tor Browser?

### ISSUE THREAD

**Issue by angakkoq** [OnionBrowser/iOS-OnionBrowser#306]
![Screenshot_20201201_091416_com.huawei.hidisk.jpg](https://user-images.githubusercontent.com/73338924/100714123-a2e5d300-33b5-11eb-8e25-fe1602bc3752.jpg)

**Comment by angakkoq** [comment]
![Screenshot_20201201_091316_com.huawei.systemmanager.jpg](https://user-images.githubusercontent.com/73338924/100714246-c7da4600-33b5-11eb-89ad-c63c406ee974.jpg)

**Comment by angakkoq** [comment]
![Screenshot_20201201_091259_com.huawei.systemmanager.jpg](https://user-images.githubusercontent.com/73338924/100714260-ce68bd80-33b5-11eb-8087-a458019b9b2b.jpg)

**Comment by angakkoq** [comment]
![Screenshot_20201201_091249_com.huawei.systemmanager.jpg](https://user-images.githubusercontent.com/73338924/100714274-d6286200-33b5-11eb-880b-d0f318d09ce1.jpg)

**Comment by angakkoq** [comment]
![Screenshot_20201130_112041_com.huawei.systemmanager.jpg](https://user-images.githubusercontent.com/73338924/100714380-f48e5d80-33b5-11eb-9213-3561e2a64828.jpg)

**Comment by tladesignz** [comment]
Completely wrong project. Closing this.
