### ISSUE TITLE
add support for a security policy for vulnerability disclosure

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#307]
there should be a security policy for what to do when you find a security vulnerability that affects or only affects onion browser as it could reduce the risk of an attacker to use a security vulnerability for their own gain.

https://github.com/OnionBrowser/OnionBrowser/security/policy

**Comment by tladesignz** [comment]
You're completely right and I'm very grateful, that you took the time.

My embarrassingly long reaction time to this is, well, very embarrassing. I'm sorry.
