### ISSUE TITLE
wvthash/user-agent not matching in  JAHPAuthenticatingHTTPProtocol

### ISSUE THREAD

**Issue by Shahbaz-Akram** [OnionBrowser/iOS-OnionBrowser#312]
I am replacing proxyURLProtocl with JAHPAuthenticatingHTTPProtocol 
Issue:  "wvthash from "NSURLRequest request" and from browser controller tab hash not matching". 

**Method Name:**  - (id)initWithRequest:(NSURLRequest *)request cachedResponse:(NSCachedURLResponse *)cachedResponse client:(id <NSURLProtocolClient>)client{}
**Class:**  JAHPAuthenticatingHTTPProtocol

**Comment by tladesignz** [comment]
It's a mechanism to only allow white-listed traffic. Search for `wvthash` in the Onion Browser source code to understand how it's used.
