### ISSUE TITLE
Custom bridges list doesn't change

### ISSUE THREAD

**Issue by not-mms** [OnionBrowser/iOS-OnionBrowser#313]
I use my own guard node as a single item in custom bridges. For some reason I had to change the OR port of the node, but I cannot change it in the Onion Browser.

To be a bit more specific, here's what I currently have as bridges:
```
1.2.3.4:9001
```
and I want to change it to:
```
1.2.3.4:10010
```
but I can't! It doesn't show me any errors, but the list resets to the first variant each time I try to change it.

**Comment by tladesignz** [comment]
Did you hit "Connect" in the top right corner after changing it? If not, it gets reset.

**Comment by not-mms** [comment]
Of course I hit "Connect" after changing the value in the input field but it seems like the app keeps trying to use the old value anyway. And when I open "Bridge Configuration" after that again I see the old value in the input.

**Comment by not-mms** [comment]
Onion Browser v2.7.2
iOS 14.4
iPhone SE 2020

**Comment by not-mms** [comment]
@tladesignz I've figured it out: the thing is that I have to push "back" right after changing the custom bridges input field, only after that push "connect". I've got a bit confused by such behaviour and I may be not the only one.

I can attach some screenshots if my explaination is not clear.

Just want to make the app a bit better :)

**Comment by tladesignz** [comment]
You're totally right. I apologize. Thanks for persevering and bearing with me! Fix will be contained in the next release!
