### ISSUE TITLE
Connection problems when using torbox

### ISSUE THREAD

**Issue by diepoe** [OnionBrowser/iOS-OnionBrowser#315]
When I want to use Onion Browser with my [torbox](https://www.torbox.ch) network, the browser behaves very strange and following things are happening:
- sometimes long launch times
- the app is prompting connection errors 

---
_Device:_
Apple iPad Pro 11" 2020 iPadOS 14.5

**Comment by tladesignz** [comment]
Don't run Tor over Tor. That doesn't make a lot of sense.
