### ISSUE TITLE
Add exceptions for prioritizing .onion services

### ISSUE THREAD

**Issue by iam-cult** [OnionBrowser/iOS-OnionBrowser#318]
I find it extremely annoying that I cannot navigate to https://vid.puffyan.us without it redirecting to http://grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad.onion, which doesn't have a working account system. There should be an option in the settings to add an exception for prioritizing .onion addresses.

**Comment by tladesignz** [comment]
Thanks for letting us know!

Note to self: This is due to Onion Browser automatically redirecting to an address given in a `Onion-Location` header:

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/Psiphon/JAHPAuthenticatingHTTPProtocol.m#L1283-L1317

**Comment by tladesignz** [comment]
You will be able to switch off this behavior either for all or per site in the next release!
