### ISSUE TITLE
Tor Browser

### ISSUE THREAD

**Issue by angakkoq** [OnionBrowser/iOS-OnionBrowser#320]
Server check.torproject.org abuse?![Screenshot_20210324_074545_org.torproject.torbrowser.jpg](https://user-images.githubusercontent.com/73338924/112267235-6fd19300-8c75-11eb-8470-e693234ec646.jpg)![Screenshot_20210324_074612_org.torproject.torbrowser.jpg](https://user-images.githubusercontent.com/73338924/112267271-79f39180-8c75-11eb-91e6-e376a021a39e.jpg)

**Comment by tladesignz** [comment]
Man, you're on the wrong project here! Go away! This is Onion Browser for iOS, **not** Tor Browser for Android!
