### ISSUE TITLE
How can I set up ClientOnionAuthDir on my iPhone?

### ISSUE THREAD

**Issue by Dynablade** [OnionBrowser/iOS-OnionBrowser#321]
How can I set up ClientOnionAuthDir on my iPhone? I want access my control panel anywhere through tor. Do I need jailbreak?

**Comment by Dynablade** [comment]
Can I use Client Authorization for v3 onion service?

**Comment by tladesignz** [comment]
You may find Settings -> Advanced Tor Configuration useful.

Besides that: This is not a Tor support forum. Please consult the [Tor docs](https://www.torproject.org/docs/tor-manual.html) and your preferred search engine!
