### ISSUE TITLE
I have some issues with git?

### ISSUE THREAD

**Issue by mldMoldovan** [OnionBrowser/iOS-OnionBrowser#324]
<img width="592" alt="Screenshot 2021-05-11 at 19 22 30" src="https://user-images.githubusercontent.com/39867408/117851165-b6fbfd80-b28e-11eb-890a-3c4c2c1bd427.png">
<img width="592" alt="Screenshot 2021-05-11 at 19 22 45" src="https://user-images.githubusercontent.com/39867408/117851181-b9f6ee00-b28e-11eb-89d2-028a72038285.png">

Please help me solve these. I tried making the directory a repo but it doesnt fix it. Thanks in advance

**Comment by tladesignz** [comment]
Sorry, these screenshots show nothing I can make sense of.

Did you follow the build instructions?

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/BUILD.md

**Comment by mldMoldovan** [comment]
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Why cant i access the repo?

**Comment by tladesignz** [comment]
Sorry, this is no beginner support channel. I guess you make yourself familiar with the git docs first.
