### ISSUE TITLE
More in depth settings

### ISSUE THREAD

**Issue by yokillb** [OnionBrowser/iOS-OnionBrowser#326]
I am trying to access a site and even with security set to highest setting website is asking me to type about:config in the search bar then search for Java script and disable it. It works on my desktop when I do this, but not on my iOS app. How do I make it work on app? Thanks in advance.

**Comment by tladesignz** [comment]
Currently not at all, I'm sorry. This is a duplicate of #272, please read and follow up there on further questions/suggestions. Thank you!
