### ISSUE TITLE
The app is not running in the background?

### ISSUE THREAD

**Issue by ma7ly** [OnionBrowser/iOS-OnionBrowser#332]
Hello.. there is a big problem with the application that does not work in the background?  When I close the application for a few seconds and return to it again it starts connecting again and all the pages disappear?

Please add the feature to run the application in the background until this problem is resolved

Problem #2 Request to add browsing to computer mode

Please add the feature to browse the computer mode because there are some sites that need this mode

**Comment by tladesignz** [comment]
For legacy and maximum security reasons, the default setting is to forget all the tabs. Please go to Settings (gear icon) -> Tab Security -> Remember Tabs.

The decision of web servers, which version of their homepage they want to serve you, is based upon the so called "User-Agent header". You can change that manually for all pages with Settings -> "Security Level" -> "User Agent" or for a specific page by Settings -> Custom Site Security -> Add Site -> etc...

Search for e.g. "Safari desktop user agent string" to find an adequate User-Agent string to use or for some other browser's like Firefox, Chrome or Internet Explorer. Again, for security reasons, this is not standardized in Onion Browser. (When everybody uses an individual user-agent, fingerprinting is thwarted.)
