### ISSUE TITLE
Browser unusable after waking iPhone from sleep.

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#334]
When you have a tab open with “forget tabs in background” setting enabled, putting iPhone to sleep (lock) and unlocking the device with Onion Browser open makes the app unable to function or do anything unless you force close and reopen.

**Comment by tladesignz** [comment]
I'm sorry, I can't reproduce that. I use the latest published version (2.7.4) on latest iOS 14.6 on an iPhone XS and it works just fine for me. All the tabs are gone, but I can get a new one by typing in a URL or by tapping the tabs button and the plus button.

Can you get more specific about details? App version, iOS version, device type? Anything else you maybe did or did not?

**Comment by tladesignz** [comment]
I just recognized, the bottom bar might be gone. You still can recover from that by typing in a new URL and load that. The bar will come back, then. I recognize, that's a subpar experience.

We'll need a check, that it is forced to show again, if there's no tab open. Or better, yet, show the default empty tab again, if there's none. I'll fix that. It'll be in the next release! Thanks for your patience!

**Comment by tladesignz** [comment]
Please reopen, if this was actually about something else!
