### ISSUE TITLE
Please update address bar search to the DuckDuckGo v3 onion address

### ISSUE THREAD

**Issue by ChaiTRex** [OnionBrowser/iOS-OnionBrowser#338]
In settings, I have the search engine set to DuckDuckGo. When I search using the address bar, it uses an old, short v2 address that [will be unusable very, very soon](https://support.torproject.org/onionservices/v2-deprecation/).

Please switch to their new v3 onion address, https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/. This can be verified as the official onion address by clicking "Visit our onion address" on https://duckduckgo.com/?q=duckduckgo+tor&ia=answer.

**Comment by tladesignz** [comment]
We were having the same thought:

https://github.com/OnionBrowser/OnionBrowser/commit/37faa940628a7c0aa4a4959e2d91df14c8ec5ed5

But thanks a lot for caring, anyway!
