### ISSUE TITLE
Desktop website support on iPadOS.

### ISSUE THREAD

**Issue by Destroyinator69420** [OnionBrowser/iOS-OnionBrowser#339]

**Comment by tladesignz** [comment]
Webservers provide different types of websites by analyzing the `User-Agent` HTTP header. You can easily set your own:

- Browse to the site in question, leave it as the top tab.
- Then, go to `Settings` -> `Custom Site Security` -> `Add Site` -> `+`
- Add a suitable desktop `User Agent` string in the last form field.

Here are some examples of suitable user agent strings: https://www.whatismybrowser.com/guides/the-latest-user-agent/safari

HTH!
