### ISSUE TITLE
Update DuckDuckGo’s onion to the new V3 Address

### ISSUE THREAD

**Issue by Baccount** [OnionBrowser/iOS-OnionBrowser#340]
If you use Tor, know that DuckDuckGo Search has a new v3 address:
https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion

The message above was posted officially by DuckDuckGo staff on Reddit [reddit post](https://old.reddit.com/r/duckduckgo/comments/oc07wj/news_duckduckgo_search_now_available_via_tor/)￼

@tladesignz

**Comment by Baccount** [comment]
After testing the V3 address at security level 1, it immediately redirects to the non-onion website after an initial search
￼

**Comment by tladesignz** [comment]
Closed, because duplicate. #338
Thanks for taking care, anyway!

**Comment by KOCHUUNDERWORLD** [comment]
I dont know more inter net knowledge
U wil help me i will assist u 👍
