### ISSUE TITLE
Updated to the latest version but don't see Very Strict.

### ISSUE THREAD

**Issue by spirulin** [OnionBrowser/iOS-OnionBrowser#343]
All I have is Gold, Silver, Bronze.

Deleted and installed the app hoping to be some bug but still not there.

**Comment by tladesignz** [comment]
Haha. Yeah, no. Turned out, the right place wasn't a new level, but a specialized setting. Go to Settings -> Default Security -> Content Policy -> Very Strict (JavaScript completely off; no context menu)
