### ISSUE TITLE
Feature request: disable all or some swipe motions on ipadOS

### ISSUE THREAD

**Issue by eruciform** [OnionBrowser/iOS-OnionBrowser#346]
The swipe commands are quite odd, I can't even figure out what all of them are, but they inevitably do strange things I don't intend, like auto-sharing things to Safari, or just completely closing the current viewed page. I believe hold and swipe right closes the current page whenever you don't have a "next" page to go to, but that's pretty confusing and annoying, as there's no way to get it back. If these could be turned off one by one, or even all of them altogether, it would be much less confusing.

**Comment by tladesignz** [comment]
See my comment on issue #344. This seems interference from iOS' multitasking features. You can disable that system-wide.
You might also try iOS 15. They changed multitasking a lot, there.
