### ISSUE TITLE
When following links from ProtonMail: Could not connect to the server. (code: -1004, domain: NSURLErrorDomain)

### ISSUE THREAD

**Issue by mjgardner** [OnionBrowser/iOS-OnionBrowser#350]
The above has happened on several links selected from ProtonMail when Onion Browser is selected as my browser in the app. Links have been from https://medium.com/, https://tilde.news/, and others. It happens on both iOS and iPadOS, and only on the latter when both apps are full-screen; if I have ProtonMail as a popover window, I don’t see the error.

**Comment by tladesignz** [comment]
Oh, wow. That's quite an honor. I didn't know, that we're an official part of the Proton Mail app! :-) Just created an account there, and there is the option! Who would have known? Thanks for letting me know. I will investigate this.

**Comment by tladesignz** [comment]
Will be contained in the next release (which will probably take some more weeks.) Thank you for your patience!
