### ISSUE TITLE
Has full permission to files and photos on iOS

### ISSUE THREAD

**Issue by seaman-divine-0r** [OnionBrowser/iOS-OnionBrowser#354]
Permanent iOS settings needed to toggle on/off permission to files and photos. 

The developer should get the data-collecting claims verified by Apple.

**Comment by seaman-divine-0r** [comment]
Also has vanishing background tiles.

**Comment by tladesignz** [comment]
> Permanent iOS settings needed to toggle on/off permission to files and photos.
> 
> The developer should get the data-collecting claims verified by Apple.

No idea what you're talking about here. Do you want to elaborate?

> Also has vanishing background tiles.

You mean in the tab overview? Yeah, that's a known bug. I have no idea what's causing this. Sorry, but currently there's no budget to work on this.
