### ISSUE TITLE
Changing BBC V2 URL in landing page 

### ISSUE THREAD

**Issue by abdallahalsalmi** [OnionBrowser/iOS-OnionBrowser#356]
Hi is it possible to change the BBC v2 url on the landing page with the v3 one? 

The new URL is:

https://www.bbcnewsd73hkzno2ini43t4gblxvycyac5aw4gnv7t2rccijh7745uqd.onion

Thanks

**Comment by tladesignz** [comment]
Ahhh, yeah! Thank you very much, we were waiting on that one!
