### ISSUE TITLE
[feature request]: Sync bookmarks with private self-hosted nextcloud server

### ISSUE THREAD

**Issue by zefr0x** [OnionBrowser/iOS-OnionBrowser#359]
It seems that the bookmarks are synced with nextcloud over the Tor network, while there are many people who are hosting their server in a private network that is not reachable from the internet or they connect to it over a VPN.

It is true that Tor is secure and private and every request in Onion Browser must be transferred through it, but locally hosted services are more private and secure than any service on the Internet, even via Tor.

I don't know the architecture of the application and I don't know if this is applicable, but it would be great to have a **button to switch** between synchronizing bookmarks via **Tor** or via **local-network**.  It will be appropriate to place the button in `Advanced Sync Settings` menu.

It's worth to mention that in recent IOS versions there is an option in the privacy settings to access the local-network so there is a kill switch from the OS itself that provides reassurance to the user if he did't want to use this feature.

Some may use a local DNS record to facilitate access to the nextcloud server so it might be a good idea to add an option to make a DNS request without Tor.

Note that when hosting a local-server that uses **https** of course everyone will use a **self-signed SSL certificate**, and IOS users will install a configuration profile for a **Root Certificate** and they will enable it from (General->About->Certificate Trust Settings) so that iPhone apps can identify & trust the server. Therefore, if Onion Browser uses another certificate storege it must use system's for this process so that no error occurs when connecting with the local-server.

**Comment by tladesignz** [comment]
Thank you for engaging with us. I can see why this might sound like a good idea in certain circumstances, but I'm sorry, this is not going to get implemented.

Every data traffic we can catch in Onion Browser runs through Tor, and for reasons of security and safety, it will stay that way. Making compromises on that is just too much of a risk of introducing vulnerabilities.

I suggest to run an onion service in front of your Nextcloud server. That's an easy and a very secure way of hosting stuff on the net.

Onion Browser 2.7.6 (due for release soon) will also support onion v3 authentication, so you can rest assured, that nobody else is able to connect to your service.
