### ISSUE TITLE
Give Feedback after a Bridge is Configured

### ISSUE THREAD

**Issue by cstiens** [OnionBrowser/iOS-OnionBrowser#361]
@tladesignz Here's the wording for the 'Trying a bridge' view

```
Trying a bridge...

This may take time. If it doesn’t work after 5 minutes, choose a different bridge.
```

I just chose 5 minutes. We could also say 'if it doesn't work after a while...'. It's hard to give an accurate idea since the internet bandwidth could be slow for the user overall. 

<img width="1151" alt="Screen Shot 2021-11-03 at 11 11 23 PM" src="https://user-images.githubusercontent.com/1434597/140256718-f1b8c85c-e60c-4d5a-8cbf-8d1b31f44740.png">

**Comment by tladesignz** [comment]
I used "…after a while…", because I really feel uncomfortable given any number here. It can vary widely, depending on network circumstances.
