### ISSUE TITLE
Gold Level Security Blocks Search Results on iOS and iPadOS

### ISSUE THREAD

**Issue by js-7711** [OnionBrowser/iOS-OnionBrowser#362]
Whether I use DuckDuckGo or StartPage, search results are missing completely on highest security level (1). 

Is this normal?

**Comment by niStee** [comment]
Have the same issue with torbrowser on my pc.
I believe the Issue is with DuckDuckGo and Startpage.

You can report DuckDuckGo security issues via https://hackerone.com/duckduckgo?type=team

Startpage support:
https://support.startpage.com/index.php?/Tickets/Submit/RenderForm

**Comment by tladesignz** [comment]
Yes, that's normal.
You will need to switch your search engine to "DuckDuckGo HTML" or "DuckDuckGo Lite" under Settings -> Search Engine

Reason is, that web pages aren't allowed to execute JavaScript in gold security level, which both DDG and Startpage use normally.
