### ISSUE TITLE
The app icon doesn't correctly fit the icon box in the App Store

### ISSUE THREAD

**Issue by pharaone** [OnionBrowser/iOS-OnionBrowser#364]
The app icon doesn't correctly fit the icon box in the App Store, there are little white spaces.
I don't think it's just me cause it's been at least since iOS 14 that I am experiencing this problem, i don't it's an App Store bug because no other app has the same problem.
![IMG_3067](https://user-images.githubusercontent.com/17162630/142590448-cb515316-77a0-41b0-af16-fdc1945ec190.PNG)
Thank you for making Onion Browser!

**Comment by tladesignz** [comment]
Thanks for catching this! You're right: Apple changed how they treat app icons. Because they constantly changed the corner rounding, they now finally do it themselves, so we need to provide sharp corners.

Will change with the next release.

**Comment by amadejpapez** [comment]
With 2.7.9 there still appear to be small white spaces on sides.

![image](https://user-images.githubusercontent.com/63184600/161636383-9312ce2d-6e81-4401-bc47-4aea07f3f900.jpeg)

**Comment by tladesignz** [comment]
Thank you for being so persistent! After some more digging, I realized, the icon files still had these two light borders on the top and left. Almost undetectable on light backgrounds and with graphics tools which always draw a border around the selected image layer. Grmpf.

**Comment by amadejpapez** [comment]
I specifically checked for this when I saw the new update haha. Although the icon was better, I still wanted to report so this can get fully resolved. Thank you for updating it so quickly!
