### ISSUE TITLE
The zoom feature resets position

### ISSUE THREAD

**Issue by StarliteTechs** [OnionBrowser/iOS-OnionBrowser#365]
While zooming a webpage after a certain threshold is reached the entire screen resets to the top left corner and therefore annihilating any zoom or presence of content.  Rather, it’s born Slippy.

**Comment by tladesignz** [comment]
Sorry, we don't have any influence over that. That's a feature of iOS' `UIWebView`, we must use here.
Also, websites themselves can interfere with the zoom through JavaScript.
