### ISSUE TITLE
Specify node

### ISSUE THREAD

**Issue by soshimee** [OnionBrowser/iOS-OnionBrowser#371]
I use Tor browser on desktop for country-locked content, but with this I have to "roll" countries and wish for the best. I think there should be a way to specify entry/exit nodes, either specifically or by country.

**Comment by tladesignz** [comment]
You're lucky! There is one:

- Go to Settings -> Advanced Tor Configuration
- In one line add "--ExitNodes"
- In the second line add country codes. E.g.: "us,de,fr"
- Hit "Save" in the top right corner.

Find further documentation here:
https://2019.www.torproject.org/docs/tor-manual.html.en#ExitNodes


I agree, the UX for this is sub-par. Noted.
