### ISSUE TITLE
Deutsche Welle v3 Onion URL for Landingpage

### ISSUE THREAD

**Issue by OliverDWelle** [OnionBrowser/iOS-OnionBrowser#376]
We would very much appreciate it if we could also be listed on the landing page with our Onion Service. Deutsche Welle is blocked in Russia and other countries. 

https://www.dwnewsgngmhlplxy6o2twtfgjnrnjxbegbwqx6wnotdhkzt562tszfid.onion

Many Thanks
Oliver Linow from DW

**Comment by tladesignz** [comment]
Wonderful! Sure do!

Please note:
- You will only show up on a fresh install. We don't inject bookmarks in user's existing bookmarks.
- Next release might take a while. We just released 2.7.8.

**Comment by OliverDWelle** [comment]
Great, many thanks!

**Comment by OliverDWelle** [comment]
Could we update the DW app logo, because the current button is in our old design? I just need to know the resolution and format and I would send it to someone or in this conversation. Many Thanks! Oliver

**Comment by tladesignz** [comment]
The icon is loaded from your website. It will be populated, if it's not found in cache.

You'll need to make sure that all icon references are good there. We use a library which somewhat dynamically decides for the best icon reference (There's the apple-app-icon, the favicon and some more, I think...)

Then, if you want to see it updated on a specific device, you will need to kill the icon cache. I think you could achieve this by deleting and re-adding the bookmark. Definitely by deleting and reinstalling the app. :-)
