### ISSUE TITLE
Onion Browser with Orbot not conecting.

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#383]
While using the Onion Browser for iOS It's unable to connect if we have Orbot enabled.

Edit: 
Wops I should have read the other issues before posting.

**Comment by n8fr8** [comment]
Good to report this however. We are trying to improve the interop between the two apps.

**Comment by tladesignz** [comment]
If you're using an Obfs4 bridge, it will actually work, though... :-)

**Comment by ghost** [comment]
@tladesignz 
Yeah I can confirm this outcome. Couldn't there be a way to blacklist apps from going through *Orbot* and just ship it with defaut ignoring Onion Browser? Since it is a sepperate instance ie and app and orbot is considered an VPN (system wide).

**Comment by tladesignz** [comment]
Orbot just sees IP packets. No way to distinguish them by apps. (which is an intentional design from Apple, I would guess...)
Anyway. Onion Browser v3 is on its way, which will actually be *based* on Orbot.
