### ISSUE TITLE
How to change Tor nodes?

### ISSUE THREAD

**Issue by SUICIDEB0YS** [OnionBrowser/iOS-OnionBrowser#386]
Hi I want to know how to change the Tor nodes in the Onion Browser like it's done here on the desktop version: https://www.wikihow.com/Set-a-Specific-Country-in-a-Tor-Browser

Thanks!

**Comment by tladesignz** [comment]
Incidentally, I just explained it here 2 days ago: https://github.com/OnionBrowser/OnionBrowser/issues/385#issuecomment-1111952210

Hth!
