### ISSUE TITLE
Toolbar Blues

### ISSUE THREAD

**Issue by VectorABC** [OnionBrowser/iOS-OnionBrowser#387]
The bottom toolbar required to access tabs hides itself and there’s no way to get it back except to scroll way back to the top of an often very long forum thread. On the Dread site and I assume others, the browser lacks any inertial scrolling so scrolling is always 1:1 and thus laborious. Since I can’t set a font size either, some forum threads collapse into one a few characters as they become repeatedly indented. That makes scrolling back to the top just to close a tab very frustrating. Then the tabs gallery page lacks any useful highlighting to indicate which the current tab is, so I must check the tab title to find it. Really I’d just like an option for normal tabs instead of a silly gallery view. And that I can keep it from ever being hidden. Like a normal browser!

**Comment by tladesignz** [comment]
> The bottom toolbar required to access tabs hides itself and there’s no way to get it back except to scroll way back to the top of an often very long forum thread. 

That is strange, as, when I just do a tiny movement upwards, the bottom toolbar typically reappears immediately.

Can you give some more circumstances, so we can identify the conditions for your edge case properly?

> On the Dread site and I assume others, the browser lacks any inertial scrolling so scrolling is always 1:1 and thus laborious. 

I'm afraid, we can't do anything about that. The Website is displayed inside a [`UIWebView`](https://developer.apple.com/documentation/uikit/uiwebview) which is beyond our control. *Every* browser on iOS needs to do that (or use the newer `WKWebView`). Apple doesn't allow anything else.

We somewhat started working on v3 which will use `WKWebView`. Maybe the behaviour you mention is better there.

Could also be, that some site's JavaScript is interfering somewhat.

> Since I can’t set a font size either, some forum threads collapse into one a few characters as they become repeatedly indented. That makes scrolling back to the top just to close a tab very frustrating. 

Interesting proposal. Can you give an example webpage where this feature would help?

> Then the tabs gallery page lacks any useful highlighting to indicate which the current tab is, so I must check the tab title to find it. 

Ah. Another good feature idea. Thank you!

> Really I’d just like an option for normal tabs instead of a silly gallery view. 

"Normal tabs"? Safari on iOS does a tab gallery just the same, at least in portrait mode, depending on the exact device.
Unfortunately, copying all the fanciness Safari does with tabs is really painfully hard and a lot of work. Not sure, if we're able to invest a lot there.

> And that I can keep it from ever being hidden. Like a normal browser!

What now? A potential tab bar? Or are you talking about the bottom toolbar now?

What is the device you are mostly working with Onion Browser? An iPad? If so, I'd see the point. On iPhone/iPod I can't fully follow you. We need to support really small devices like the iPhone SE1, too. There's no way things like tab bars fit there in a sensible fashion and pages still remain readable.

**Comment by tladesignz** [comment]
Just re-read this. Not sure I can get anything out of it anymore.
Besides, while going through it, I had a related idea which might be of help and might possibly cheaply to implement: #426
