### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by nika-maisashvili** [OnionBrowser/iOS-OnionBrowser#393]
I have been using for a while now and now it keeps crashing can’t even open it, black screen and crash I tried reinstalling it , restarting the phone . Does anyone else have this problem

**Comment by tladesignz** [comment]
Weird. Can you describe the circumstances in more detail?

- What OS version, which device? What network is used?
- Which region/country you're using it in?
- Which version did you install exactly? Official release from app store or a TestFlight?

**Comment by tladesignz** [comment]
Closed due to no response.
