### ISSUE TITLE
Cannot connect with either without a bridge. Error: An SSL error has occurred and a secure connection to the server cannot be made. 

### ISSUE THREAD

**Issue by alemens** [OnionBrowser/iOS-OnionBrowser#398]
Cannot connect with either without a bridge. Error: An SSL error has occurred and a secure connection to the server cannot be made. 

See the screenshots below 

![4402FF00-A95F-4B0E-9E34-92ED3EEC0465](https://user-images.githubusercontent.com/20490756/185530259-78d0f648-c88b-46dc-81e9-12a929cb7894.png)
![02B30119-68C2-465A-87FA-A3862FFAB481](https://user-images.githubusercontent.com/20490756/185530265-d241c509-44c2-4447-a8eb-16a932847d56.png)

**Comment by tladesignz** [comment]
Can you disclose in which country/city/location you are?

**Comment by alemens** [comment]
NYC

> Can you disclose in which country/city/location you are?

**Comment by tladesignz** [comment]
New York City? And you're using your mobile operator, as it seems, not some WiFi?

Is your operator trying to interject your TLS connections? Hmmmmmmm.

@mtigas, @n8fr8, do you have any experience with US mobile network operators trying to interfere with TLS connections. Or connections to Tor-related stuff?

**Comment by n8fr8** [comment]
I had seen this problem a week ago myself, but now seems resolved. I think it may have been related to a certificate issue on Tor side for circumvention API or Moat.

**Comment by tladesignz** [comment]
@alemens, can you confirm that it works now? Or does it still persist for you?

**Comment by alemens** [comment]
@tladesignz via LTE it does not

**Comment by tladesignz** [comment]
Well, then, if WiFi at home works but your LTE connection not, obviously your mobile ISP is trying to do something "clever". Could by they try to read your traffic to sell the learnings to ad target data aggregators, or could be you are on a plan which includes some Internet "security" offer.

Sorry, I can't come up with anything else to help you. Can we close this?

**Comment by tladesignz** [comment]
Closed due to no response.
