### ISSUE TITLE
edit bookmarks crashes app

### ISSUE THREAD

**Issue by mattlikespie** [OnionBrowser/iOS-OnionBrowser#399]
tor 2.8.1, post-ios 16 upgrade, iPhone 13. updating URL in bookmarks crashes the application. seems to happen after the : in https://...

this happens for both existing and newly created bookmarks.

**Comment by tladesignz** [comment]
Thank you for catching this! The fix will be contained in the next release, which might take a few more weeks.

**Comment by mattlikespie** [comment]
Happy to help out with the small stuff! Thanks for the quick turn around!
