### ISSUE TITLE
[Feature Request] Allow users to disable screenshot prevention protection

### ISSUE THREAD

**Issue by ericswpark** [OnionBrowser/iOS-OnionBrowser#403]
From issue #402, it would be great if users (who know what they are doing) could disable the screenshot prevention protection. This could be some toggle in settings that is disabled by default.

**Comment by tladesignz** [comment]
See my comment, why this won't get implemented: https://github.com/OnionBrowser/OnionBrowser/issues/402#issuecomment-1302356589

**Comment by ericswpark** [comment]
@tladesignz thanks, I've read your comment in the other thread.

While I do understand that the screenshot blocking is not the real reason behind the delay on resumption, it would still be great to have an option to disable the function, just like other apps that implement this feature. It could be useful if I need to reference data in Tor Browser while going through the app switcher. Can this feature request be re-opened?

**Comment by tladesignz** [comment]
Wish granted! Will be released, soon.

**Comment by ericswpark** [comment]
Thanks!

**Comment by yeyeyeyeyyeyeyeyey** [comment]
Yeah, you're welcome!
