### ISSUE TITLE
Can't resume without force close

### ISSUE THREAD

**Issue by ehcorn** [OnionBrowser/iOS-OnionBrowser#404]
Running 16.1.1 on a 12 mini fresh update, standard release. When I go to the home or switch to another app when I come back to onion it's blurry and unresponsive. Not sure if this is a feature or a bug, but I can't seem to find anything about it in settings.

**Comment by yeyeyeyeyyeyeyeyey** [comment]
I think it is a bug.

**Comment by yeyeyeyeyyeyeyeyey** [comment]
I will see if I can fix it

**Comment by tladesignz** [comment]
Not sure who's this yeyeye figure. This person/bot has nothing to do with this repo.

**Comment by tladesignz** [comment]
@ehcorn, this behaviour is to be expected. When returning, Tor needs to be restarted, that takes a while. Sorry, but we won't improve anymore, because there's a new version on the horizon which leverages Orbot. Stay tuned!
