### ISSUE TITLE
G App Launcher gets reset on every launch

### ISSUE THREAD

**Issue by toineenzo** [OnionBrowser/iOS-OnionBrowser#408]
The extension G App Launcher (Google™ Shortcuts) on Firefox and G App Launcher (Customizer for Google™) on Chrome, get reset every time I relaunch Orion Browser
https://addons.mozilla.org/en-US/firefox/addon/google-shortcuts-all-google-se/
https://chrome.google.com/webstore/detail/g-app-launcher-customizer/ponjkmladgjfjgllmhnkhgbgocdigcjm

I'm using Version Orion 0.99.122-beta (WebKit 615.1.11.7) on a MacBook Pro 2020 M1 with macOS Ventura 13.1

**Comment by tladesignz** [comment]
I'm sorry, I have no idea what you're talking about.

If you're looking for the [Orion Browser](https://browser.kagi.com) help desk, I suggest to restart your search.

**Comment by toineenzo** [comment]
Oops, I thought I was on the correct GitHub, but. I meant Orion. Pardon my stupidness

**Comment by yeyeyeyeyyeyeyeyey** [comment]
Hah, I did that once too. Do not worry.

**Comment by tladesignz** [comment]
No worries! Have a good day!
