### ISSUE TITLE
Can't proxy applications like Telegram through Tor?

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#410]
### Is it possible to route applications through Tor proxy on IOS?

I tried to setting `SocksPort 9050` in the *Advanced Tor Configuration* settings which i assume is the torrc equivalent for IOS version. 

Then setting the proxy in telegram to use `127.0.0.1 port 9050.` while the OnionBrowser is still open. *It never worked*. 

**Is this even possible to do using OnionBrowser on IOS to proxy applications that have proxy options?**

**Comment by tladesignz** [comment]
Nope, it's not. Apps are stopped by iOS very soon after they go into the background. So the Tor inside Onion Browser is stopped, too, of course.

Additionally, AFAIR, user settings are applied first, then the needed settings of Onion Browser, which means, your `SocksPort` setting is overridden. This is to make sure, users don't break functionality of the app.

If you need to bring an App into Tor on iOS, you might want to look into https://orbot.app No need for a proxy mode there. Device traffic fully routed through Tor!

**Comment by ghost** [comment]
@tladesignz 
Thanks didn't even know this existed on IOS, thought it was only Anrdoid only lol.
