### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by gathomas766** [OnionBrowser/iOS-OnionBrowser#412]
The onion web browser supposed to allow me to get onto the Internet and the dark web. However, the possibility of my phone been hacked. On my iOS with iPhone 11, I don’t seem to be able to get online or the dark web. The one time I was able to get online and search how to get on the dark web, and told me that I need VPNs, etc. and Tor.  But I already have Tor through the onion app.  

Please advise!!

Can also text at 909-649-2670

**Comment by tladesignz** [comment]
Sorry, this is not a user support forum. Additionally, I'm confused as what you're actual request is. Maybe you could make use of [Orbot](https://orbot.app), which tunnels *all* device traffic through Tor? Beware: It *doesn't* currently work yet with Onion Browser, so you will have to switch it off while working in Onion Browser.
