### ISSUE TITLE
( URGENT )I can’t acces lots of websites in onion browser

### ISSUE THREAD

**Issue by shotslinger1** [OnionBrowser/iOS-OnionBrowser#413]
There has been an error for onion browser that I think is only happening to me, yes before you ask the app is updated to date, my date is on point, and my connection is secure. So my problem is that after the update When I try to access websites it says “Checking if the site connection is secure” and it happens to a lot of websites and on the bottom it says (the website) needs to review the security of your connection before proceeding and after the 1.1.1.1 logo appears with a box to check mark it I check mark it but it just keeps realoading. Here is the image below:

![B3BF3E65-432C-4D5E-A5CB-12513FBD96BC](https://user-images.githubusercontent.com/130939527/232349088-32c2b96a-8e75-43ea-9310-f79ebbb20736.png)
 me into the same page (it does the same thing over and over again) I can’t access websites please help me or a fix.

**Comment by tladesignz** [comment]
Uh. That's Cloudflare intercepting you. It wants to see the proper User-Agent header. You can circumvent this problem if you go to Settings (The little gear icon in the bottom right corner) -> Default Security -> Popular User Agents: Tor Browser Mobile Android

Cheers!
