### ISSUE TITLE
Settings and any other apps needed

### ISSUE THREAD

**Issue by Sammydton** [OnionBrowser/iOS-OnionBrowser#414]
I am new to all this. I have an iPhone 11. What are the best settings I should use on onion browser? (and) are there any other free apps I can combine to achieve the closest thing to privacy? Could you tell me what I should set the options to on those as well?

I only want advice that has to do with keeping my browsing that I do on OnionBrowser as close to private as reasonably possible without having to root my phone or have a technical background so if you can keep it simple I will be grateful. 

I don’t expect any guarantees, just help from someone who knows more than me. I am a newbie. Thanks 

thank you. 
samantha

**Comment by yeyeyeyeyyeyeyeyey** [comment]
Hello, Sammydton. This is the best app you can use. Any other apps will not give you any privacy. (That I know of right now.) Sorry. Also if I am being totally honest, I wouldn't go aimlessly searching, as it could ask you to download and will give you malware viruses. I also recommend using a computer if you want to go deeper into this website. Some people may disagree, but personally, it is harder to navigate. You may just want to download T.O.R. If you respond with your intentions to this website, I may be able to help you further (Like if you want to code or just browse.)
Sorry if this did not help.
-yeyeyeyeyeyeye 
Have a good day.

**Comment by tladesignz** [comment]
Sorry, this is not a general how-to-stay-private-on-the-net support. I left this open, since there seemed to start a community discussion, but that dried down, obviously, so I'm closing it.
