### ISSUE TITLE
Can't download file from an onionshare URL

### ISSUE THREAD

**Issue by Davem734** [OnionBrowser/iOS-OnionBrowser#420]
Trying to send a file from Onion Share (running on a desktop) to Onion Browser (running on an iPad).

Using Onion Browser to open the Onion Share link.
The Onion Share download page opens. 
Clicking the download button results in the (binary) file being opened in another tab as random text. 
No option to save the file or download file.

The onion link works correctly on another device using the Tor Browser.
 
  iOS: 16.4.1(a)
  Onion Browser: 2.8.3
 
See also: 
  Can't download files from onion service #293 
  Unable to save files since upgrading to iOS 14 #292

**Comment by tladesignz** [comment]
Ok, I see.

When OnionShare sends something, which Onion Browser recognizes as something it can display in the web view, it will show it.

The share sheet then only allows to share the URL, instead of the content. So you can't store the content in the "Files" app or in similar apps. (Except, when it's images.)

I'll look into it.

**Comment by Davem734** [comment]
OK. I am beyond impressed. Fastest bug fix ever :)
What is the expected release date for 3.0.0 so I can give it a test drive?
Thank you for all of the awesome work you have put into making the digital world a safer place...

**Comment by tladesignz** [comment]
> OK. I am beyond impressed. Fastest bug fix ever :)

You're just lucky. ;-) I'm currently working on it, and sharing/storing seems to be a big thing among users. So I gave it another thought.

> What is the expected release date for 3.0.0 so I can give it a test drive?

Less then a month, I'd expect. But "it's ready, when it's done!" So no pressure, please.

Here's a TestFlight, if you want to use it early: https://testflight.apple.com/join/90DvGBOE
(I'm not sure you can run old and new versions in parallel. And you will need Orbot!)

> Thank you for all of the awesome work you have put into making the digital world a safer place...

Thanks for the flowers! I take great delight in working on this, but getting feedback like this makes it even more awesome!
