### ISSUE TITLE
auth_private keys are forgotten.

### ISSUE THREAD

**Issue by visskiss** [OnionBrowser/iOS-OnionBrowser#421]
On the tor browser on macOS there is no issue memorizing and retaining auth_private keys for authenticated hidden services. However onion browser forgets these. Either there is a bug or this functionality is missing or excluded. Can we please retain these keys?

**Comment by tladesignz** [comment]
Won‘t fix. This is going to be obsolete with Onion Browser 3 which is going to be released within weeks.

OB3 relies on Orbot, and Orbot has UI to manage authentication keys.
