### ISSUE TITLE
V3.0 Feedback

### ISSUE THREAD

**Issue by cstiens** [OnionBrowser/iOS-OnionBrowser#422]
Here are a few things I found:

- [x] Each time I open the Onion Browser app, it says 'Orbot installed! One more step.' Even though I have already given permission for Orbot to use Onion Browser.
- [x] I have Orbot installed. The first screen I see is 'Orbot installed! One more step.' We need a different starting point in this case (existing user that has Orbot installed). I can map this case out in Figma. The ticket and design for this case are here: https://github.com/OnionBrowser/OnionBrowser/issues/423
- [x] In Orbot, in the access request view, the name of the app is 'com.miketigas.OnionBrowser'. It should only be Onion Browser.
- [x] The implementation skips the 'Welcome to Onion Browser' view, it shows 'Install Orbot' first.
- [x] The 4 dots in Onboarding are not swipe-able, and I want to swipe them. :/ I think we need to change the visual. That's on me. Will you remove it for now?
- [x] After I install Orbot and connect, it doesn't take me automatically back to Onion Browser. Is this still possible to do?
- [x] After I grant access I'm taken to the browsing view in Onion Browser. I see a white blank-ish screen. I should see the Onion Browser home page right? If I search for a website, it renders. So it seems it's not broken.
- [x] I think it's important that we address security levels in the first release. It's tied to to change in the overall model that's requiring them to have Orbot. What is the easiest thing we can do?

**Cases to test:**
- Existing OnionBrowser user updating to v3; does not have Orbot installed
- I already have Orbot installed and am upgrading OnionBrowser

**Comment by tladesignz** [comment]
> * Each time I open the Onion Browser app, it says 'Orbot installed! One more step.' Even though I have already given permission for Orbot to use Onion Browser.

That means, the permission token was not stored. This should not happen. (And does not happen for me.) Can you explain exactly, step-by-step, what you're doing to achieve this situation?

Please make sure, you're not running multiple copies of Onion Browser and Orbot!

> * I have Orbot installed. The first screen I see is 'Orbot installed! One more step.' We need a different starting point in this case.

This should also not happen. The very first thing you should see, right after freshly installing Onion Browser (or the first time after an upgrade from 2.x) is the "Welcome to Onion Browser / You're one step closer to private browsing." scene.

This is only shown once, of course. The next start doesn't show this scene.

Are you sure, that's what you're doing? Deleting Onion Browser completely from the device, then reinstalling from Testflight?


> * In Orbot, in the access request view, the name of the app is 'com.miketigas.OnionBrowser'. It should only be Onion Browser.

Good catch! Fixed.

**Comment by cstiens** [comment]
@tladesignz Here's a screen record of a fresh install on my device: https://drive.google.com/drive/u/1/folders/1qKUjD5cBKkqEb0BAAz1QOnqlL2LY6_Uu

- Orbot was not installed.
- I didn't get the blank screen this time in the Browser view.
- Since I'm following the steps to install Orbot from Onion Browser, it's giving me the app store version (rather than test flight), which is right. But if there are changes in the test flight version those aren't reflected here.

**Comment by tladesignz** [comment]
> Each time I open the Onion Browser app, it says 'Orbot installed! One more step.' Even though I have already given permission for Orbot to use Onion Browser.

Pretty sure that's on your side. I see in your video, that you still have an old version installed which gets triggered on return. **Remove all version of Onion Browser** before testing this!

> The implementation skips the 'Welcome to Onion Browser' view, it shows 'Install Orbot' first.

I see in your video recording, that it's shown. Then the app gets intercepted by the TestFlight scenes. After that, we return to the app and the app switches to the next scene.
I fixed the logic, so that it's only considered "shown", when the user hits the "next" button.

> The 4 dots in Onboarding are not swipe-able, and I want to swipe them. :/ I think we need to change the visual. That's on me. Will you remove it for now?

Yeah, can't make them interactive, that would destroy the needed logic of moving the user forward through necessary steps. Removed.

>  After I install Orbot and connect, it doesn't take me automatically back to Onion Browser. Is this still possible to do?

Orbot needed some fixes. This will work fully in the next version of Orbot.

> After I grant access I'm taken to the browsing view in Onion Browser. I see a white blank-ish screen. I should see the Onion Browser home page right? If I search for a website, it renders. So it seems it's not broken.

> After I grant access I'm taken to the browsing view in Onion Browser. I see a white blank-ish screen. I should see the Onion Browser home page right? If I search for a website, it renders. So it seems it's not broken.

There seems to be some issue with tab restoration. I added some shotgun debugging to try to fix this problem.

> I think it's important that we address security levels in the first release. It's tied to to change in the overall model that's requiring them to have Orbot. What is the easiest thing we can do?

I have no idea at what you're aiming... Probably discuss in chat. I'll text you.

**Comment by tladesignz** [comment]
>  I think it's important that we address security levels in the first release. It's tied to to change in the overall model that's requiring them to have Orbot. What is the easiest thing we can do?

There's an issue about it: #418

I'll close this, and we continue discussion there!
