### ISSUE TITLE
Onion Browser requiring passcode for iOS

### ISSUE THREAD

**Issue by mattlikespie** [OnionBrowser/iOS-OnionBrowser#425]
iOS 16.5 (20F66)
Onion Browser - 2.8.3

Launching Onion Browser for iOS is requiring passcode. As best I can tell I don't have any restrictions on the app. No Downtime, no App Limits. Onion Browser is in Always Allowed. Content and Privacy Restrictions is turned off.

**Comment by tladesignz** [comment]
You may have selected to lock the app with FaceID/TouchID/device passcode and forgot about it.
That's in the settings. Disable it again, then you're good.

**Comment by mattlikespie** [comment]
Checked that too. I don't use Face ID and only use Passcode for the device, not individual apps. 

https://github.com/OnionBrowser/OnionBrowser/assets/113533724/f11f34f2-2e1a-4234-ab79-5a61528101a8

**Comment by tladesignz** [comment]
If you don't have FaceID enabled, it falls back to the passcode.

This very much looks like you enabled the lock feature in Onion Browser. Esp. the 3 repeats.

Disable it in Settings.

I'm talking about the in-app settings when pressing the gear icon. Not the Settings app.

**Comment by mattlikespie** [comment]
thanks, and my apologies for submitting this. issue resolved. i wasn't too keen to enter the passcode because i didn't (intentionally) set that.
