### ISSUE TITLE
Orbot dependency breaks Onion Browser

### ISSUE THREAD

**Issue by R-a-l-f** [OnionBrowser/iOS-OnionBrowser#427]
Hi,

Orbot cannot establish an Internet connection.

iPad Pro MTFR2FD/A
iPadOS 16.5
location Germany

I added a comment to [ Orbot not working under ipados 16.5 #61 ](https://github.com/guardianproject/orbot-apple/issues/61)

Regards,
Ralf

**Comment by tladesignz** [comment]
An update to Orbot is coming which should resolve the situation somewhat. Although, the root cause seems to be on Apple's side.

Here's the center of investigation for this problem:
https://github.com/guardianproject/orbot-apple/issues/67
