### ISSUE TITLE
Orbot disables wifi/won't connect (iOS)

### ISSUE THREAD

**Issue by rjaxx-0900** [OnionBrowser/iOS-OnionBrowser#433]
iPhone 13 Pro
iOS 16.5
VPN: ipVanish (disabled before using Orbot; have deleted the VPN permissions for ipVanish with no change.

Have tried other Tor iOS apps just to see if they can connect to Tor, which they do (they don't place nice with CloudFlare, however)

I am attempting to use OnionBrowser, but Orbot is getting in the way. Every connection type I try results in:

-loss of wifi connection
-Orbot continuously loops to connect but never does (it worked ONCE but I have no idea why and I don't have the log for that)

UPDATE: deleted/reinstalled/reconfigured both Onion and Orbot. Orbot was able to connect via direct connect, but Onion was not connected to Tor. Disconnected Orbot and could not get it to reconnect. 

Log (working, sorta, and then... not):
Jun 19 17:58:16.000 [notice] Tor 0.4.7.13 opening new log file.
Jun 19 17:58:16.927 [notice] We compiled with OpenSSL 1010114f: OpenSSL 1.1.1t  7 Feb 2023 and we are running with OpenSSL 1010114f: 1.1.1t. These two versions should be binary compatible.
Jun 19 17:58:16.931 [notice] Tor 0.4.7.13 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1t, Zlib 1.2.11, Liblzma 5.4.2, Libzstd N/A and Unknown N/A as libc.
Jun 19 17:58:16.931 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 19 17:58:16.931 [notice] Configuration file "/private/var/mobile/Containers/Data/PluginKitPlugin/B9999252-B2F9-4AC9-8042-E13E44FA8382/.torrc" not present, using reasonable defaults.
Jun 19 17:58:16.933 [warn] MaxMemInQueues is set to a low value; if your client doesn't work, this may be the reason why.
Jun 19 17:58:16.935 [notice] Opening Socks listener on 127.0.0.1:0
Jun 19 17:58:16.936 [notice] Socks listener listening on port 49471.
Jun 19 17:58:16.936 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49471
Jun 19 17:58:16.936 [notice] Opening DNS listener on 127.0.0.1:0
Jun 19 17:58:16.936 [notice] DNS listener listening on port 61492.
Jun 19 17:58:16.936 [notice] Opened DNS listener connection (ready) on 127.0.0.1:61492
Jun 19 17:58:16.936 [notice] Opening Control listener on 127.0.0.1:0
Jun 19 17:58:16.936 [notice] Control listener listening on port 49472.
Jun 19 17:58:16.936 [notice] Opened Control listener connection (ready) on 127.0.0.1:49472
Jun 19 17:58:16.000 [notice] {GENERAL} Parsing GEOIP IPv4 file /var/containers/Bundle/Application/B0D183CC-7193-4BE8-A4D4-3A0794945914/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip.
Jun 19 17:58:17.000 [notice] {GENERAL} Parsing GEOIP IPv6 file /var/containers/Bundle/Application/B0D183CC-7193-4BE8-A4D4-3A0794945914/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip6.
Jun 19 17:58:17.000 [notice] {CONTROL} Bootstrapped 0% (starting): Starting

Orbot NOT working:

Log: 
Jun 19 14:58:41.000 [notice] Tor 0.4.7.13 opening new log file.
Jun 19 14:58:40.992 [notice] We compiled with OpenSSL 1010114f: OpenSSL 1.1.1t  7 Feb 2023 and we are running with OpenSSL 1010114f: 1.1.1t. These two versions should be binary compatible.
Jun 19 14:58:40.998 [notice] Tor 0.4.7.13 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1t, Zlib 1.2.11, Liblzma 5.4.2, Libzstd N/A and Unknown N/A as libc.
Jun 19 14:58:40.998 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 19 14:58:40.998 [notice] Configuration file "/private/var/mobile/Containers/Data/PluginKitPlugin/62320674-0531-4913-BC2B-34C2F2E8C62C/.torrc" not present, using reasonable defaults.
Jun 19 14:58:41.000 [warn] MaxMemInQueues is set to a low value; if your client doesn't work, this may be the reason why.
Jun 19 14:58:41.001 [warn] Client authorization encoded base32 private key length is invalid: 
Jun 19 14:58:41.003 [notice] Opening Socks listener on 127.0.0.1:0
Jun 19 14:58:41.003 [notice] Socks listener listening on port 65389.
Jun 19 14:58:41.003 [notice] Opened Socks listener connection (ready) on 127.0.0.1:65389
Jun 19 14:58:41.003 [notice] Opening DNS listener on 127.0.0.1:0
Jun 19 14:58:41.003 [notice] DNS listener listening on port 62176.
Jun 19 14:58:41.003 [notice] Opened DNS listener connection (ready) on 127.0.0.1:62176
Jun 19 14:58:41.003 [notice] Opening Control listener on 127.0.0.1:0
Jun 19 14:58:41.003 [notice] Control listener listening on port 65390.
Jun 19 14:58:41.003 [notice] Opened Control listener connection (ready) on 127.0.0.1:65390
Jun 19 14:58:41.000 [warn] {REND} Client authorization encoded base32 private key length is invalid: 
Jun 19 14:58:41.000 [notice] {GENERAL} Parsing GEOIP IPv4 file /var/containers/Bundle/Application/68C01B19-2E96-4832-83B2-E266406F8E62/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip.
Jun 19 14:58:41.000 [notice] {GENERAL} Parsing GEOIP IPv6 file /var/containers/Bundle/Application/68C01B19-2E96-4832-83B2-E266406F8E62/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip6.
Jun 19 14:58:41.000 [notice] {CONTROL} Bootstrapped 0% (starting): Starting

**Comment by jimmyherron** [comment]
Pretty much same as above, except Orbot disconnects my wifi then attempts to connect over mobile data and fails between 10/30% during which time the device is disconnected from basically all networks. Very frustrating

**Comment by tladesignz** [comment]
Sorry, folks.

It seems, this is a problem Apple introduced with iOS 16.5.

See https://github.com/guardianproject/orbot-apple/issues/67 for the central node to all discussions.

As per all my researches, it looks like the "VPN" process doesn't get killed, but iOS thinks it was. This breaks restarting. It looks like the old process gets killed after about 1 minute. Then it should work again.
What also seems to help is to clear the cache, maybe because this triggers an earlier kill of that zombie process. (In Orbot -> Settings -> Clear Tor Cache, at the very bottom.)

The short WiFi-on/off behaviour is to be expected. I don't think the device really does stop the WiFi connection. After the "VPN" is established, my devices show WiFi connection again. I guess, this behaviour is due to the captive portal tester for WiFi connections. Even though you're already connected to a WiFi, iOS won't say so, until it can reach a certain Apple website. It does this to test, if it gets redirected. If so, iOS will show you a dialog containing the captive portal of the WiFi hotspot, where you can check the "I have read the terms and agree" flag.

**Comment by rjaxx-0900** [comment]
Thank you! 
Should I give it another try, or is the issue on-going?

**Comment by tladesignz** [comment]
> Thank you!
> Should I give it another try, or is the issue on-going?

I released a fix. It will automatically retry, if the OS stopped the VPN again to remedy some strange behaviour of iOS 16.5. It also contains a "Clear Tor Cache" button right on the main scene, so you can try that quickly. Should work better now, but "your milage may vary"...

**Comment by bensig** [comment]
Having a lot of disconnections on iOS 16.6 - Onion Browser totally unusable and Orbot just seems to die after connecting.

**Comment by tladesignz** [comment]
> Having a lot of disconnections on iOS 16.6 - Onion Browser totally unusable and Orbot just seems to die after connecting.

Sorry to hear. Orbot update is on the way! Unfortunately, we suddenly have a lot of issues since iOS 16.5 which very much looks like Apple is the cause for. I'll try to work it out with them, but it's difficult.

I have also speculations that the behaviour/the traffic of the Tor network changed so much in recent months, that it makes the client consume too much memory for a Network Extension (which Apple limits to a pretty low 50 MB) so I'm also working with Tor to improve the clients behaviour there.

**Comment by xahon** [comment]
I worked fine in a regular OnionBrowser app without Orbot, why is it a required thing now? It's literally impossible to connect now because outer VPN gets disabled and local ISP blocks all request no matter what bridges are used

**Comment by tladesignz** [comment]
https://github.com/OnionBrowser/OnionBrowser/issues/47
https://github.com/OnionBrowser/OnionBrowser/issues/231

Sorry, @xahon, unfortunately, Apple makes your use case impossible.

**Comment by hampus1010** [comment]
Haven't been solved unfortunately

**Comment by tladesignz** [comment]
> Haven't been solved unfortunately

Yes, and it won't be solved, soon. Sorry. We're cornered here and we need to wait until some major development happens at Tor Project. Use iOS 17 and the built-in Tor the latest Onion Browser now is able to provide again. That doesn't have the resource constraints. (But is less secure. 🤷)

**Comment by xahon** [comment]
@tladesignz Did Apple do some major changes in the same OS version (15) so that Onion Browser stopped working the same way as it did before? I don't think they could break something that hard in a minor update. My old iPhone doesn't even update to 16 version, let alone version 17

**Comment by tladesignz** [comment]
We were forced to move away from `UIWebView` to the newer renderer `WKWebView`. And that does support proxying through a local Tor only from iOS 17 onwards.

**Comment by JTheMan** [comment]
> In Orbot -> Settings -> Clear Tor Cache, at the very bottom.



> > Haven't been solved unfortunately
> 
> Yes, and it won't be solved, soon. Sorry. We're cornered here and we need to wait until some major development happens at Tor Project. Use iOS 17 and the built-in Tor the latest Onion Browser now is able to provide again. That doesn't have the resource constraints. (But is less secure. 🤷)

How do you set this up in Onion browser? Just curious. I didn't know it had a TOR VPN option.
