### ISSUE TITLE
Crashes When trying to play videos 

### ISSUE THREAD

**Issue by pheonixfirewingz** [OnionBrowser/iOS-OnionBrowser#434]
I’m using the app store v3 and when i try playing videos in the browser it crashes the app i can’t give much information as i don’t know what the cause could be? Thought i would raise the issue.

**Comment by cpwjosh** [comment]
Works fine for me on v3.0.1 (iOS 16.5.1)

**Comment by pheonixfirewingz** [comment]
I'm on 16.6.4 beta

**Comment by tladesignz** [comment]
Works fine for me, too. Sorry, I'm not battling with beta versions. I'll have another look, when 16.6 arrives.

**Comment by tladesignz** [comment]
Related: #437 Can you check please? The reporter said, it had to do with his user agent string.
