### ISSUE TITLE
Onion does NOT work now

### ISSUE THREAD

**Issue by MusicWhore** [OnionBrowser/iOS-OnionBrowser#435]
I got Orbot because the browser said I absolutely HAD to get it to keep using the browser, so I got it and set it up, but when I go back to Onion and tap on “request access”, absolutely NOTHING happens. What the hell, man? I just want to use Tor.

**Comment by tladesignz** [comment]
Sorry, that you have such an annoying experience. You might be frustrated now, but we're actually not doing this on purpose just to get nice messages like this.

For others it works, so you might have a setup, which is unusual. If you want to get it working and/or if you want to help others in the same situation, you will need to provide some detailed information:

- Which device are you running?
- Which version of the operating system?
- Is this device under any company or parental control?
- Which version of Orbot do you have installed?
- Which version of Onion Browser do you have installed?

A screen recording of the problem would be super awesome, which also shows Orbot running.

Here's how you do that:
https://support.apple.com/en-us/HT207935

Thank you!

**Comment by lostbeta** [comment]
Same issue here. Request Access button does nothing. If I tap Why and then tap Request Access in the popup window, the popup is dismissed and nothing else happens.

- iPad gen 9
- iPadOS 16.5.1
- No device management or parental control
- Orbot 1.6.1
- Onion browser 3.0.1

![image](https://github.com/OnionBrowser/OnionBrowser/assets/9974657/2cb03fad-7fb7-4924-985f-18490e1bb286)

**Comment by tladesignz** [comment]
Hmmmm. Can you uninstall Orbot and reinstall it? Orbot uses a "website association". There's special URLs which point to `https://orbot.app/rc/` which are getting caught by the installed Orbot app. Maybe, the website wasn't reachable, when Orbot was installed/updated and that association broke?

(Just guessing here, but that's the only thing I can come up with right now.

I have an idea on how to improve the robustness. Will deploy next week, if it works as I think it should.

**Comment by lostbeta** [comment]
Thanks for the suggestion. Weirdly, it works now after reinstalling Orbot even though I had just installed it when I had the issue last time. The only thing I did differently this time is to request access before starting the VPN connection in Orbot. For the sake of troubleshooting I denied that initial request in Orbot, then started the VPN connection and requested access from Onion again and it worked the second time too, so I'm not sure if this has anything to do with the issue.

**Comment by tladesignz** [comment]
Maybe fixed with 7019add682484bfbbed136c6fadb9d8cb9c4ffd4.

**Comment by jeremygaither** [comment]
Same issue. Should I wait for the next release using the new pod?

**Comment by tladesignz** [comment]
> Same issue. Should I wait for the next release using the new pod?

Just uninstall and reinstall Orbot. Make sure, you do it, while you have a good connection to the internet, and your device can reach https://orbot.app.
