### ISSUE TITLE
Cant access any .onion sites.

### ISSUE THREAD

**Issue by R3DACTDgithub** [OnionBrowser/iOS-OnionBrowser#436]
No .onion sites open for me, it gets stuck on loading. Ive tried using bronze but it doesn't do anything. I am on ipad, ios 15, not sure which version specifically.

**Comment by tladesignz** [comment]
Are you sure you are running Orbot iOS, and you have it installed from here:
https://apps.apple.com/us/app/orbot/id1609461599
?

Can you post the Tor log from Orbot here after you started and tried to reach a .onion site? (Left top button with the lines in Orbot.)

**Comment by coelhoZikaDev** [comment]
Good afternoon

I'm trying to use the Tor Browser on a network, but it doesn't connect to any bridge.


11/7/23, 15:52:45.716 [WARN] Proxy Client: unable to connect to 38.229.1.78:80 ("general SOCKS server failure")
11/7/23, 15:52:45.718 [WARN] Proxy Client: unable to connect to 193.11.166.194:27020 ("general SOCKS server failure")
11/7/23, 15:52:45.718 [WARN] Proxy Client: unable to connect to 85.31.186.26:443 ("general SOCKS server failure")
11/7/23, 15:52:45.718 [WARN] Proxy Client: unable to connect to 193.11.166.194:27015 ("general SOCKS server failure")
11/7/23, 15:52:45.719 [WARN] Proxy Client: unable to connect to 192.95.36.142:443 ("general SOCKS server failure")
11/7/23, 15:52:45.721 [WARN] Proxy Client: unable to connect to 37.218.245.14:38224 ("general SOCKS server failure")
11/7/23, 15:52:45.721 [WARN] Proxy Client: unable to connect to 38.229.33.83:80 ("general SOCKS server failure")
11/7/23, 15:52:45.722 [WARN] Proxy Client: unable to connect to 144.217.20.138:80 ("general SOCKS server failure")
11/7/23, 15:52:45.722 [WARN] Proxy Client: unable to connect to 45.145.95.6:27015 ("general SOCKS server failure")
11/7/23, 15:52:45.722 [WARN] Proxy Client: unable to connect to 209.148.46.65:443 ("general SOCKS server failure")
11/7/23, 15:52:45.722 [WARN] Proxy Client: unable to connect to 85.31.186.98:443 ("general SOCKS server failure")
11/7/23, 15:52:45.722 [WARN] Proxy Client: unable to connect to 51.222.13.177:80 ("general SOCKS server failure")
11/7/23, 15:52:45.723 [WARN] Proxy Client: unable to connect to 146.57.248.225:22 ("general SOCKS server failure")
11/7/23, 15:52:45.723 [WARN] Proxy Client: unable to connect to 193.11.166.194:27025 ("general SOCKS server failure")
11/7/23, 15:53:07.630 [WARN] Proxy Client: unable to connect to 193.11.166.194:27020 ("general SOCKS server failure")
11/7/23, 15:53:07.630 [WARN] Proxy Client: unable to connect to 146.57.248.225:22 ("general SOCKS server failure")
11/7/23, 15:53:07.631 [WARN] Proxy Client: unable to connect to 45.145.95.6:27015 ("general SOCKS server failure")
11/7/23, 15:53:07.631 [WARN] Proxy Client: unable to connect to 192.95.36.142:443 ("general SOCKS server failure")
11/7/23, 15:53:07.631 [WARN] Proxy Client: unable to connect to 209.148.46.65:443 ("general SOCKS server failure")
11/7/23, 15:53:08.555 [WARN] Proxy Client: unable to connect to 193.11.166.194:27015 ("general SOCKS server failure")
11/7/23, 15:53:09.559 [WARN] Proxy Client: unable to connect to 144.217.20.138:80 ("general SOCKS server failure")
11/7/23, 15:53:13.622 [WARN] Proxy Client: unable to connect to 85.31.186.26:443 ("general SOCKS server failure")
11/7/23, 15:53:15.628 [WARN] Proxy Client: unable to connect to 38.229.1.78:80 ("general SOCKS server failure")
11/7/23, 15:53:15.628 [WARN] Proxy Client: unable to connect to 85.31.186.98:443 ("general SOCKS server failure")
11/7/23, 15:53:17.628 [WARN] Proxy Client: unable to connect to 37.218.245.14:38224 ("general SOCKS server failure")
11/7/23, 15:53:17.628 [WARN] Proxy Client: unable to connect to 51.222.13.177:80 ("general SOCKS server failure")
11/7/23, 15:53:20.629 [WARN] Proxy Client: unable to connect to 193.11.166.194:27025 ("general SOCKS server failure")
11/7/23, 15:53:44.164 [WARN] Proxy Client: unable to connect to 2a0c:4d80:42:702::1:27015 ("general SOCKS server failure")
11/7/23, 15:54:05.196 [WARN] Proxy Client: unable to connect to 38.229.1.78:80 ("general SOCKS server failure")
11/7/23, 15:54:05.198 [WARN] Proxy Client: unable to connect to 37.218.245.14:38224 ("general SOCKS server failure")
11/7/23, 15:54:05.198 [WARN] Proxy Client: unable to connect to 85.31.186.26:443 ("general SOCKS server failure")
11/7/23, 15:54:05.199 [WARN] Proxy Client: unable to connect to 146.57.248.225:22 ("general SOCKS server failure")
11/7/23, 15:54:05.199 [WARN] Proxy Client: unable to connect to 193.11.166.194:27015 ("general SOCKS server failure")
11/7/23, 15:54:05.200 [WARN] Proxy Client: unable to connect to 192.95.36.142:443 ("general SOCKS server failure")
11/7/23, 15:54:05.200 [WARN] Proxy Client: unable to connect to 51.222.13.177:80 ("general SOCKS server failure")
11/7/23, 15:54:05.200 [WARN] Proxy Client: unable to connect to 85.31.186.98:443 ("general SOCKS server failure")
11/7/23, 15:54:05.202 [WARN] Proxy Client: unable to connect to 193.11.166.194:27020 ("general SOCKS server failure")
11/7/23, 15:54:05.202 [WARN] Proxy Client: unable to connect to 38.229.33.83:80 ("general SOCKS server failure")
11/7/23, 15:54:05.203 [WARN] Proxy Client: unable to connect to 193.11.166.194:27025 ("general SOCKS server failure")
11/7/23, 15:54:05.214 [WARN] Proxy Client: unable to connect to 209.148.46.65:443 ("general SOCKS server failure")
11/7/23, 15:54:05.214 [WARN] Proxy Client: unable to connect to 144.217.20.138:80 ("general SOCKS server failure")
11/7/23, 15:54:19.770 [WARN] Proxy Client: unable to connect to 45.145.95.6:27015 ("general SOCKS server failure")


How do I get it to connect?

**Comment by tladesignz** [comment]
@coelhoZikaDev, please don't hijack other issues. Also, please don't comment on commits! Instead, open your own issue!

You seem to get blocked. Try the various bridge offerings to find one which works.
