### ISSUE TITLE
Not able to load videos (iOS 17.0 Beta)

### ISSUE THREAD

**Issue by fcc5e870057** [OnionBrowser/iOS-OnionBrowser#437]
I have tried to load videos on Onion Browser v3.0.1, but it stuck loading and won't play. Haven't had this issue in iOS 16, and I have enabled JavaScript. Just need some help.

**Comment by fcc5e870057** [comment]
Actually, just found the fix, it is to do with the user agent. It won't load videos unless set to Safari Browser. I wanted to load via desktop user agent, but unfortunately, not possible.

**Comment by tladesignz** [comment]
Thanks for this info, this is valuable information, esp. since you managed to fix it.
