### ISSUE TITLE
Crashes when clicking link that opens popup tabs.

### ISSUE THREAD

**Issue by manphiz** [OnionBrowser/iOS-OnionBrowser#438]
iPhone 12 Pro iOS 16.6 (20G75)
Onion Browser: Version 3.0.1 (75022.391958010)

Onion browser seems to crash when a link opens a popup window/tab.  Example URL: https://m.manhuagui.com/comic/7708/

This is a Chinese manga website with popup ads.  Clicking on the image ads leads to crash reliably.  (Note that you may need to refresh for the ads to show up.)

No workaround found yet.  Please let me know if more info is needed.

**Comment by tladesignz** [comment]
Thank you very much! That was a very valuable hint! I could fix multiple crashes here.
