### ISSUE TITLE
Tor Browser for iOS - Clear Data and Tab Security issue(s)

### ISSUE THREAD

**Issue by mattlikespie** [OnionBrowser/iOS-OnionBrowser#441]
Tor for iOS 3.0.1 (75022.391958010)
iOS 16.6 (20G75)

When using the Clear Data long-press on the Tor icon, tabs are not closed and data is not cleared if the app is still open.
After closing the app and relaunching it, the previously closed session shows briefly.
When closing the app completely and using the long-press Clear Data option the previous session screen does not appear.

Note: After relaunching the app and getting to the Start Page (after the brief previous session is shown) and repeating the close app / relaunch sequence, the previous session in not displayed.

Tab Security is set to Forget at Shutdown.
This happens even when I use the Clear Tor Cache option in Orbot.

**Comment by tladesignz** [comment]
I'm still struggling a little with the multi-window support which doesn't fall back gracefully on iPhones in every corner.

This should be fixed in version 3.0.3 due for release soon.

Thank you for reporting this!
