### ISSUE TITLE
Use of Orbot forced; no toggle or other VPN options available

### ISSUE THREAD

**Issue by todd-a-jacobs** [OnionBrowser/iOS-OnionBrowser#443]
Some VPNs natively support Tor even on iOS, or allow tunneling Tor over non-Tor VPN connections. However, Onion Browser now requires Orbot; meanwhile, Orbot disables all other active VPNs, preventing Onion Browser from running over anything but Orbot.

Unless there's a security implication for using a different primary VPN (besides the obvious: you are trusting the VPN provider, but you're doing that anyway whether or not the primary VPN is Orbot), there should be a toggle for bypassing Orbot or enabling its use through existing VPN connections.

I have no issues with the Orbot dependency as such, although it *may not be needed* in all cases. However, disabling the ability to use Onion Browser without the option to use a different primary or other Tor-enabled VPN, or just tunneling Onion Browser traffic instead of forcing all traffic over Orbot seems like it actually *reduces* system security in some cases.

Onion Browser should be allowed to work over or through other VPNs. While some of the problem may lie upstream with Orbot wanting sole control of the VPN connection, Onion Browser is currently the app forcing the use of an Orbot-only VPN. This should be fixed.

**Comment by tladesignz** [comment]
Unfortunately, it is not as easy as deciding to "fix" something. The situation is as it is now for reasons:

- Apple switched from the old `UIWebView` rendering engine to `WKWebView` rendering engine some iOS versions ago and marked the old one deprecated. However, they never provided the needed feature set for an app like Onion Browser until now.

- The reason, why they wanted to split browser apps and network tunneling apps, is, that the architecture of iOS has a security hole there: audio and video streaming is and was always handled by another component, which was never tunnel-able. 

- On iOS, unfortunately, there can always only be one "VPN" app running. There's no possibility to chain VPNs. (Which use the so called "Network Extensions" architecture, btw.)

Hence the split in Onion Browser 3: We developed Orbot to work as a full-device traffic pseudo-VPN tunneling app to finally make sure, there's no traffic leaked. (Or almost none - Apple again, of course, reserves the right to bypass any VPN 🙄 - and makes use of it, too: https://github.com/eycorsican/leaf/issues/302#issuecomment-1595304354)

And then there's Onion Browser, which is the browser part and adds some special safeguards around browsing on, or via, the Tor network. Which is, first and foremost: deny traffic as soon as Tor goes away.

Anyway, you got lucky, at least a little. Apple had a change of mind and finally added proxy support to `WKWebView`. So, here you are: An Onion Browser TestFlight which uses that and where you can switch between an in-app Tor and the use of Orbot (as long as you have iOS 17): https://testflight.apple.com/join/90DvGBOE


Regarding security considerations:

Orbot is not a "VPN provider". Orbot is a Tor client which uses the "Network Extensions" infrastructure of iOS and macOS, which Apple dubbed "VPN" in its user interface. You don't need to trust any "provider". What you do need to trust is the protocol and policy design around the Tor network itself and the good will and the competency of the people who implemented it. Or you go and read all of it and audit the open sourced code. Or you trust a whole bunch of other people with no tied interests to the Tor project who did this and continue to do this.

That's quite a different story than trusting any "VPN provider". Which are mostly private companies who want to make a cut.


AFAIK, there's no other app in the app store, which is open source and uses Tor and which is also endorsed by the Tor Project itself.

All these "VPN + Tor" apps are probably doing some really shady things to make it work. Like actually terminating Tor on their servers or patching the Tor binary in a way which makes it unsafe.

They try to make money off of the popularity of Tor Project, and the security they offer is dubious. We also never received any contributions of any of them (be it financially or in code), although they profit from Onion Browser and Orbot, too.

Onion Browser will positively never allow being used with any of these projects, and potentially risk the security of our users, as long as they're not publishing their code and start cooperating with us.

If you really want to use one of these other apps which allow to combine VPNs and Tor, we won't stop you, however. You can use their apps and combine them with a normal browser, even with Safari. (Obviously ou can do that with Orbot, too, btw.)

Onion Browser, however, is dedicated to make sure you stay on the Tor Network in a secure fashion. Also, it totally doesn't make sense for us to try to compete with other browser implementations over browser features.
