### ISSUE TITLE
WebTunnel and Conjure support

### ISSUE THREAD

**Issue by SpaceBurn** [OnionBrowser/iOS-OnionBrowser#444]
This might more be an issue to bring up with the Orbot team, but will OnionBrowser ever support WebTunnel, Conjure or any other experimental pluggable transports?

**Comment by tladesignz** [comment]
There's no roadmap for that. Not for Onion Browser, not for Orbot. Looking forward to your pull requests! :-) (Be aware, though, the architecture is somewhat complicated, and there's a lot to think about.)
