### ISSUE TITLE
[SECURITY][WARNING] Javascript ALWAYS enabled on Gold Security Level!

### ISSUE THREAD

**Issue by ghost** [OnionBrowser/iOS-OnionBrowser#445]
.

**Comment by ghost** [comment]
Hey! No one will look at that security risk?!

**Comment by cyrneko** [comment]
> Hey! No one will look at that security risk?!

This is a much smaller project than the "primary" Tor Browser, as such I cannot condfidently say that security issues here are addressed nearly as quickly.

In other words, I am asking you to be more patient.

**Comment by tladesignz** [comment]
Ok, just check this. 

Have to admit, it's confusing.

The page you originally posted doesn't check, if JavaScript is available by using JavaScript but by doing this with HTML and CSS:


```html
    <noscript>
        <style>
        #js-warning {
            display: none;
        }
        </style>
    </noscript>
```

What Onion Browser uses (and needs to use, the `WKWebView` API is very limited), is this, though:

https://developer.apple.com/documentation/webkit/wkwebpagepreferences/3552422-allowscontentjavascript

> The default value of this property is true. If you change the value to false, the web view doesn’t execute JavaScript code referenced by the web content. That includes JavaScript code found in inline <script> elements, javascript: URLs, and all other referenced JavaScript content.

Note: It only says 

> code referenced by the web content

So, technically, JavaScript is still on, hence the `<noscript>` tag is not honoured by the rendering engine, but for all practical purposes, the webpage itself *cannot* use it.

You can confirm this with a better test, which actually tries to use JavaScript:

https://www.whatismybrowser.com/detect/is-javascript-enabled


HtH
