### ISSUE TITLE
Built-in translation plug-in

### ISSUE THREAD

**Issue by zdll311** [OnionBrowser/iOS-OnionBrowser#448]
It is recommended to have a built-in translation plug-in, otherwise it will be difficult to use.

**Comment by tladesignz** [comment]
Sorry, that probalby won't happen anytime soon. It would mean, that we send your content to a translation service, which would probably want to charge us for it. At least, probably soon after we released it. Not talking about the effort to extract text and replace it properly. 

Browser extensions unfortunately are only supported by Safari on iOS. Not by lower technologies like the `WKWebView` we're using here. If Apple ever decides to make that possible, you will be set. Until then...
