### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by MichaelSokolov** [OnionBrowser/iOS-OnionBrowser#451]
I followed all the steps in the [BUILD.md](https://github.com/OnionBrowser/OnionBrowser/blob/3.X/BUILD.md) but still have the error: 'Command PhaseScriptExecution failed with a nonzero exit code'.

Xcode 15.0.1

![Screenshot 2024-01-16 at 16 08 36](https://github.com/OnionBrowser/OnionBrowser/assets/23324527/930b7c88-e778-497a-a43e-089123112674)

**Comment by tladesignz** [comment]
When you open the project configuration, select the "OBVersion" target, the "Build Phases" tab and the "Run Script" section, you'll notice that this executes `"$SRCROOT"/build-util/mk_build_versions.sh`.

You could also check out the "Report Navigator" tab in the left column of Xcode.

I don't know why this doesn't work on your machine, but with the information I gave you, you might be able to find out why.

This was a small lesson in how to use Xcode. I won't do that again. So if you think about asking another question, make sure it is about Onion Browser, not about your unwillingness to explore Xcode on your own. Thanks
