### ISSUE TITLE
Error: Could not connect to the server (Code - 1004 domain NSURLErrorDomain) 

### ISSUE THREAD

**Issue by 13Nina** [OnionBrowser/iOS-OnionBrowser#457]
While browsing, I've spotted that I get the error at some websites like instagram.
I only get the error when I use Wi-Fi, when I'm browsing using my mobile internet - I do not get such error.

**Comment by tladesignz** [comment]
Well, in that case, I guess that's an issue with your home setup. In general, when googling for this error, a lot of mentions come up, so it doesn't sound like it particulary has to do something with Onion Browser.

E.g. see here for some general steps to bugfix:
https://discussions.apple.com/thread/255366443?sortBy=best
