### ISSUE TITLE
Unable to Donate through App Store

### ISSUE THREAD

**Issue by nafoiw1410** [OnionBrowser/iOS-OnionBrowser#461]
Hello.

I suspect there are issues arising from the billing API, which leads to my donation attempts getting rejected by Apple every time. It’s not a card related issue as I’ve made multiple in-app purchase recently with no issues.

**Comment by tladesignz** [comment]
Hey, thanks for letting us know!

@mtigas, you set this up. Could you check? Is this just about accepting some updated agreements with Apple in https://appstoreconnect.apple.com ?

**Comment by mtigas** [comment]
I accepted the newest agreement (that went up on Monday after the keynote). Maybe that'll fix it? If not, I can poke around some more in the coming days.

**Comment by nafoiw1410** [comment]
I just tried again, still not working on my end

**Comment by mtigas** [comment]
You know what, I'd been putting off the [EU DSA Trader disclosures](https://developer.apple.com/help/app-store-connect/manage-compliance-information/manage-european-union-digital-services-act-trader-requirements/) in App Store Connect and it might've been related to that. I just went in and filled out all the remaining agreements and disclosures.

Let's see if it works now.

**Comment by tladesignz** [comment]
Just made a payment over 0.99€ Can confirm, it works again.

**Comment by tladesignz** [comment]
Thank you for pushing us, @nafoiw1410!
