### ISSUE TITLE
Geolocation and Advanced HTML5 Features

### ISSUE THREAD

**Issue by visitor996** [OnionBrowser/iOS-OnionBrowser#486]
Hello! https://onionbrowser.com/about mentions under the “Geolocation and Advanced HTML5 Features” section mentions:

“Websites may use the HTML5 Geolocation API (to view your current GPS location) and other new HTML5 features unless "Strict" security mode is set. Users should also remain vigilant for any pop-ups asking for permission to access location data”

What I understand from this is: Websites can use an API to get your location and other stuff silently unless you enable strict mode. Is it correct? In that case, shouldn’t this get mentioned in the about:security-levels section? I feel like I’m misunderstanding something but I can’t see how. It would be really great if this was clarified more in the website. Thanks!

**Comment by tladesignz** [comment]
The other way round: The browser will always ask you if you want to allow that. In strict mode, it's silently dropped.
