### ISSUE TITLE
C Compiler Cannot Create Executables After Updating to Xcode 16 

### ISSUE THREAD

**Issue by Ahmed-Mujahid** [OnionBrowser/iOS-OnionBrowser#490]
Hello,

I recently updated my development environment to Xcode 16 . Since the update, I have encountered an issue where the C compiler cannot create executables when trying build. Below are the details of the error:

Error Message:

configure: error: C compiler cannot create executables

<img width="600" alt="Screenshot 2024-09-25 at 10 57 39 AM" src="https://github.com/user-attachments/assets/1a189b28-01de-47e5-8fa3-897a592449c8">

Steps to Reproduce:

1. Update to Xcode 16.

2. Attempt to build.

Additional Information:
•  I have verified that the Command Line Tools are correctly set in Xcode Preferences.

•  I have tried reinstalling Xcode and the Command Line Tools, but the issue persists.

Any assistance or guidance on resolving this issue would be greatly appreciated.

Thank you!

**Comment by tladesignz** [comment]
@Ahmed-Mujahid, thanks for pointing this out! This is an issue with the `Tor.framework` dependency. I released an update, which fixes it: https://github.com/iCepa/Tor.framework/releases/tag/v408.12.2

I also updated Onion Browser (as you can see in the issue history).

Make sure to `pod install` and in Xcode do `Product` -> `Clean Build Folder...`

Happy hacking!

**Comment by Ahmed-Mujahid** [comment]
Thankyou its resolved by updating tor to 408.12.2.
