### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by paragmajum** [OnionBrowser/iOS-OnionBrowser#61]
Does `OnionBrowser`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by mtigas** [comment]
It’s the latter. Unfortunately, iOS apps are still restricted from using anything other than UIWebView or WKWebView, which is very hard to override in terms of preferences like this.

(To wit, even Chrome uses the iOS UIWebView, but they also do implement their own network stack on top of it, which supports more advanced SSL ciphers such as [ECDHE-RSA-CHACHA20-POLY1305](https://www.imperialviolet.org/2013/10/07/chacha20.html). I don’t believe any third-party browser has been allowed to supply their own HTML rendering engine to run on the device.)
