### ISSUE TITLE
Screen not completely hidden by overlay in landscape

### ISSUE THREAD

**Issue by JRomainG** [OnionBrowser/iOS-OnionBrowser#78]
When some devices enter background in landscape mode, the screen isn't entirely hidden by the image. This happens on devices which don't have a landscape overlay (iPhone 6, iPhone 5/5S/5C, iPhone 4/4S).

You could use the landscape image of another device and set the imageView's content mode to UIViewContentModeScaleAspectFill. However, this would crop part of the image, making the transition less nice.

I guess the best way would be to include other images for those specific devices to avoid this issue.

**Comment by tladesignz** [comment]
New version 2 is completely different. Version 1 won't be worked on anymore.
