### ISSUE TITLE
[2.X] Basic tor configuration logic (import from Onion Browser 1.X)

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#80]
from 1.X branch, see torrc and the `updateTorrc` in AppDelegate. This one is mostly about the base torrc, however. See #82 regarding the `updateTorrc` bits for bridges/ipv6 settings. (Separating these out because I think the latter is a bit more work and we'll want to think about it some more.)

**Comment by n8fr8** [comment]
Do we have access to torrc config in OB2?
