### ISSUE TITLE
[2.X] meta-ticket: consolidate Tor Controller (& rethink config/control port logic)

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#84]
In 1.X, Tor is managed by a thing called [TorController](https://github.com/mtigas/OnionBrowser/blob/1.X/OnionBrowser/TorController.m) (although the code is horrendous and a lot of configuration logic [happens in AppDelegate](https://github.com/mtigas/OnionBrowser/blob/f4d185c36051337ccbcd14081e23898661feb59a/OnionBrowser/OnionBrowser/AppDelegate.m#L449-L535).

more or less, we want to:

* move the configuration and initial `[torThread start]` ([see here](https://github.com/mtigas/OnionBrowser/blob/377ce39da83a16a7f07a10fb118e18b8d7e421e2/Endless/AppDelegate.m#L41-L53)) out of AppDelegate and into a manager (controller?) class -- #80
* move [this code](https://github.com/mtigas/OnionBrowser/blob/377ce39da83a16a7f07a10fb118e18b8d7e421e2/Endless/AppDelegate.m#L57-L99) out of AppDelegate and actually use it to poll the connection status to show a "Connecting..." dialog -- #81 

any such manager/controller will have some other tasks in the future (tickets TBD)
* retrieving connection info and parsing out a Tor circuit diagram so we can show it to user
* watching connection state so that we deal with changing network connectivity (see also #2)
* some function to do "new tor circuit" so that the user can trigger this
* probably some other things

**Comment by tladesignz** [comment]
Although it's not as nice as sketched here, we now have something which probably qualifies as this and we also released version 2 some months ago, so I'll close this ticket and the milestone. We can always open up new ones, if need be.
