### ISSUE TITLE
[2.X] Prompt for automatic use of bridges after 15 seconds

### ISSUE THREAD

**Issue by mtigas** [OnionBrowser/iOS-OnionBrowser#85]
Possible new feature:

After 15 seconds of stalled initialization, automatically prompt user to try to use bridges (using obfs4 by default?)

Cuts out step where user has to wait and get frustrated that app isn't working, and then go into the bridge prompt and _then_ have to figure out what to do.

**Comment by samisharafeddine** [comment]
Perhaps after 30~45 secs, considering the slow internet connection speeds for some users.

**Comment by mtigas** [comment]
@xNightDev Perhaps a better wording is: "15 seconds if no progress has been made". 

At least, during the first phases of Tor connection, between 0% and 80% or something like that — connection to directories, fetching descriptors, start of circuit building. Even a very slow mobile data connection will increment progress during that phase (a slow network will take some time to fetch the descriptors, but % progress should still increase).

But if the process is stalled and no progress is made, either the network is offline _or_ Tor is possibly being blocked on the user's network.

**Comment by cstiens** [comment]
@mtigas @tladesignz Is it correct that we no longer need the user to restart the app?

> After 15 seconds of stalled initialization, automatically prompt user to try to use bridges (using obfs4 by default?)

Is the option to automatically connecting to a bridge out of the question for now?

**Comment by tladesignz** [comment]
@cstiens Mike hopes, that he can achieve that, yes. But it's not done, yet, and we will only know for sure, then.

**Comment by tladesignz** [comment]
I now envision a fairly easy solution: When no progress for 15 seconds, remove cartoons and cartoon subtext and instead show something like "Seems, Tor can't connect. Maybe you need to configure a bridge? Tap here to do so." or something. 

Also, I would then drop the 30 second timeout red screen which says "Looks like we got stuck! Quit. Then restart the app." Can @kckthx do the wording?

**Comment by tladesignz** [comment]
@kckthx:

Can you please sign this off or improve?

![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-02-13 at 12 46 08](https://user-images.githubusercontent.com/117089/74432698-41bd3500-4e5f-11ea-888c-ad11cc8a08d2.png)

**Comment by kckthx** [comment]
@tladesignz would there be another option for action? 
or if they don't configure bridges, they would just shut down the app?

**Comment by tladesignz** [comment]
> @tladesignz would there be another option for action?
> or if they don't configure bridges, they would just shut down the app?

Yeah, there's no way to continue here. Either Tor connects in the end, through bridges or without, or they can't continue to use the app.

**Comment by kckthx** [comment]
@tladesignz we came up with this language
![OB_DEL-ON-Bridge-Config-Restart](https://user-images.githubusercontent.com/36669955/74572650-114fc680-4f45-11ea-8d26-1f1de3276d3d.png)

**Comment by tladesignz** [comment]
@kckthx, should I change the image and background color to these specific ones, or just use the last which was on rotation?

**Comment by tladesignz** [comment]
@kckthx, and why is the progress bar hidden? Tor is still trying to connect in the background and it could succeed any time, as the delay might be just due to a very slow connection.

**Comment by tladesignz** [comment]
How about this?
![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2020-02-18 at 12 39 05](https://user-images.githubusercontent.com/117089/74732994-b28f9300-524b-11ea-9279-9e01ad21b83b.png)

**Comment by tladesignz** [comment]
@kckthx Ping

**Comment by kckthx** [comment]
hey @tladesignz I think this will work if we take off the second "connecting to Tor." 
I was struggling with the idea of telling the user to close the app if it can still start to work at any moment. But they don't really need that many options. I think it would be best for them to default to restarting the app still. 

<img width="377" alt="Screen Shot 2020-02-21 at 8 36 33 AM" src="https://user-images.githubusercontent.com/36669955/75043204-47310580-5485-11ea-806a-aa3e10fb6e92.png">
