### ISSUE TITLE
[2.X] Compile error: Tor/Tor.h not found

### ISSUE THREAD

**Issue by ponychicken** [OnionBrowser/iOS-OnionBrowser#87]
I am trying to compile the 2.X branch. I checked out all submodules and installed the pods. I get one error when compiling, xCode doesn't seem to find the Tor.h file, even though the Tor.framework is in place.

**Comment by tladesignz** [comment]
Did you also use Carthage? https://github.com/Carthage/Carthage

Here's my guide, which I compiled a few days ago:

## Steps to build OnionBrowser
```bash
$ git clone git@github.com:mtigas/OnionBrowser.git
$ cd OnionBrowser
$ git checkout 2.X
$ pod repo update
$ pod install
$ carthage update --platform iOS --use-submodules
$ open OnionBrowser2.xcworkspace
```

**Comment by mtigas** [comment]
After doing the above, if you're still having issues (and you're not doing a fresh checkout as above), I notice there are sometimes issues depending on how the git submodules were checked out.

You can do `rm -rf Carthage/Checkouts Carthage/Build` to wipe away the submodules and then do the last two commands (starting at `carthage update...`) from the above post and see if that helps.

**Comment by SergeyPakhandrin** [comment]
Hi!

I'm trying to compile 2.X using the list of commands above but get the error 

carthage update --platform iOS --use-submodules
*** Cloning Tor.framework
*** Checking out Tor.framework at "tor0.3.0.6-libevent2.1.8-openssl1.0.2k"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.b7sZyi.log
*** Building scheme "Tor-iOS" in Tor.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sergey/UntdGroup/OnionBrowser/Carthage/Checkouts/Tor.framework/Tor.xcodeproj -scheme Tor-iOS -configuration Release -derivedDataPath /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/Tor.framework/tor0.3.0.6-libevent2.1.8-openssl1.0.2k -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.b7sZyi.log

Could you please help to fix this?

**Comment by synth3** [comment]
Thanks a lot! 

Could you please put that kind of info in the readme.md?

**Comment by tladesignz** [comment]
Just stumbled over this in mail marked mails list.
It's noted here: https://github.com/OnionBrowser/OnionBrowser/blob/2.X/BUILD.md
