### ISSUE TITLE
Text typed in address bar persists as keyboard predictions

### ISSUE THREAD

**Issue by daxelrod** [OnionBrowser/iOS-OnionBrowser#93]
It appears that the iOS keyboard will suggest words previously typed into the Onion Browser address bar. This allows sensitive information, such as what domain names a user has visited, to be saved on the device after a user could reasonably expect it to have been purged.

### To Reproduce
1. Open Settings App
   1. General -> Reset -> Reset Keyboard Dictionary (then enter password, and Reset Dictionary)
   1. General -> Keyboard
      1. Keyboards -> Ensure English is active
      1. Ensure "Predictive" and "Character Preview" are turned on
1. Notes App -> Create a note
   1. Begin typing `taylorsw`, note that at no point is `taylorswift` suggested above the keyboard
1. Onion Browser App
   1. Type `taylorswift.horse` into the address bar and click "Go"
1. Notes app -> Create a note
   1. Type `tayl`. `Taylorswift` is suggested above the keyboard

Surprisngly, visitng a domain name once is enough for this to happen. I haven't been able to reproduce this with ".com" domain names, only other TLDs.

### Versions
**iOS**: 9.3.5 (I know that there were keyboard prediction overhauls in iOS 10, so I'm not sure if this affects iOS 10)
**Onion Browser**: 1.7.3 (20170221.1)
**Device**: iPhone 6

### Workaround

Reset Keyboard Dictionary after using Onion Browser.

### Thank you

Onion Browser continues to be awesome.

**Comment by daxelrod** [comment]
I'm not an iOS programmer, but I found a [Keylogging and the Autocorrection Database](https://books.google.com/books?id=g7CPCwAAQBAJ&lpg=PA176&ots=cJjMUCTjs1&dq=setSecureTextEntry&pg=PA175#v=onepage&q=setSecureTextEntry&f=false) section of David Thiel's 2016 book *iOS Application Security: The Definitive Guide for Hackers*. I'm not sure if the technique it describes is up to date.

**Comment by daxelrod** [comment]
On iOS 10.3.2 and Onion Browser 1.7.4, step 3 must be repeated twice before the keyboard will start suggesting the domain name.

**Comment by mtigas** [comment]
This has been fixed since the 2.X release. https://github.com/mtigas/OnionBrowser/blob/v2.0.3/Endless/WebViewController.m#L125-L126

**Comment by daxelrod** [comment]
Awesome, thank you very much!
