### ISSUE TITLE
[2.X] Cannot save pdf file

### ISSUE THREAD

**Issue by ponychicken** [OnionBrowser/iOS-OnionBrowser#94]
When navigating to a PDF file online it is displayed fine in the browser, but there is no way to save it/share it to another app. In safari there is a button on the left top corner of the pdf which allows you to do that.

**Comment by ghost** [comment]
Yes, onionbrowser seriously needs a “share” button. Right now one cannot export/share e.g. sci-hub articles to a pdf viewer.

**Comment by tladesignz** [comment]
Related: #10

**Comment by tladesignz** [comment]
Actually fixed with current development version.
