### ISSUE TITLE
build libevent failed

### ISSUE THREAD

**Issue by szuwest** [OnionBrowser/iOS-OnionBrowser#96]
Using libevent-2.0.22-stable.tar.gz
Building without ccache
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking build system type... i386-apple-darwin16.5.0
checking host system type... i386-apple-darwin16.5.0
checking for gcc... /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -arch i386 -miphoneos-version-min=8.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/west/Downloads/OnionBrowser-master/build/src/libevent-2.0.22-stable':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by szuwest** [comment]
[Uploading config.txt…]()
config.log

**Comment by szuwest** [comment]
[config.txt](https://github.com/mtigas/OnionBrowser/files/951790/config.txt)
config.log

**Comment by tladesignz** [comment]
I had some issues with the latest build, also.

Please check out my updates to the build instructions:

https://github.com/mtigas/OnionBrowser/blob/2.X/BUILD.md

Does that help?
