### ISSUE TITLE
Missing Cancel button in bridge settings

### ISSUE THREAD

**Issue by JRomainG** [OnionBrowser/iOS-OnionBrowser#99]
This screen mentions a Cancel button, but there doesn't seem to be any in the nav bar

Also, the tableview's content offset doesn't take into account the navigation bar, so part of the header is hidden.

![img_1649](https://cloud.githubusercontent.com/assets/7504819/26444100/44c13456-413b-11e7-965f-b81f8327f4de.PNG)

**Comment by tladesignz** [comment]
Resolved with commit d632012aa6457e092a10bb5a516c956a8548faa5
